
CREATE VIEW [view_org_arenda]
AS
SELECT
    [ar].[arenda_id]
   ,[ar].[org_renter_id]
   ,[ar].[org_balans_full_name]
   ,[ar].[org_renter_full_name]
   ,[ar].[org_giver_full_name]
   ,[ar].[purpose_group]
   ,[ar].[purpose]
   ,[ar].[is_privat]
   ,[ar].[agreement_kind]
   ,[ar].[agreement_date]
   ,[ar].[agreement_num]
   ,[ar].[floor_number]
   ,[ar].[cost_narah]
   ,[ar].[cost_payed]
   ,[ar].[cost_debt]
   ,[ar].[cost_agreement]
   ,[ar].[cost_expert_1m]
   ,[ar].[cost_expert_total]
   ,[ar].[pidstava]
   ,[ar].[pidstava_date]
   ,[ar].[pidstava_num]
   ,[ar].[rent_start_date]
   ,[ar].[rent_finish_date]
   ,[ar].[rent_actual_finish_date]
   ,[ar].[rent_rate_percent]
   ,[ar].[rent_rate_uah]
   ,[ar].[rent_square]
   ,[ar].[rishennya_code]
   ,[ar].[is_subarenda]
   ,[ar].[payment_type]
   ,[b].[street_full_name]
   ,[b].[addr_nomer]
   ,[b].[district]
   ,[b].[addr_zip_code]
   ,[b].[condition]
   ,[b].[bti_code]
   ,[b].[history]
   ,[b].[object_type]
   ,[b].[object_kind]
   ,[b].[sqr_total]
   ,[b].[facade]
FROM
    [GUKV].[dbo].[view_arenda] AS ar
    INNER JOIN view_buildings b ON ar.building_id = b.building_id
