//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUKV.ImportToolUtils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUKV.ImportToolUtils.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса.
        /// </summary>
        internal static string AppendixColTitleAddress {
            get {
                return ResourceManager.GetString("AppendixColTitleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Балансова Вартість.
        /// </summary>
        internal static string AppendixColTitleBalansCost {
            get {
                return ResourceManager.GetString("AppendixColTitleBalansCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік побудови.
        /// </summary>
        internal static string AppendixColTitleBuildYear {
            get {
                return ResourceManager.GetString("AppendixColTitleBuildYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристика.
        /// </summary>
        internal static string AppendixColTitleCharacteristics {
            get {
                return ResourceManager.GetString("AppendixColTitleCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Діаметр.
        /// </summary>
        internal static string AppendixColTitleDiameter {
            get {
                return ResourceManager.GetString("AppendixColTitleDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік введення в експлуатацію.
        /// </summary>
        internal static string AppendixColTitleExplYear {
            get {
                return ResourceManager.GetString("AppendixColTitleExplYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залишкова Вартість.
        /// </summary>
        internal static string AppendixColTitleFinalCost {
            get {
                return ResourceManager.GetString("AppendixColTitleFinalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Довжина.
        /// </summary>
        internal static string AppendixColTitleLength {
            get {
                return ResourceManager.GetString("AppendixColTitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Об&apos;єкт в БД.
        /// </summary>
        internal static string AppendixColTitleObject1NF {
            get {
                return ResourceManager.GetString("AppendixColTitleObject1NF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид Об&apos;єкту.
        /// </summary>
        internal static string AppendixColTitleObjKind {
            get {
                return ResourceManager.GetString("AppendixColTitleObjKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва Об&apos;єкту.
        /// </summary>
        internal static string AppendixColTitleObjName {
            get {
                return ResourceManager.GetString("AppendixColTitleObjName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип Об&apos;єкту.
        /// </summary>
        internal static string AppendixColTitleObjType {
            get {
                return ResourceManager.GetString("AppendixColTitleObjType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Призначення.
        /// </summary>
        internal static string AppendixColTitlePurpose {
            get {
                return ResourceManager.GetString("AppendixColTitlePurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Група Призначення.
        /// </summary>
        internal static string AppendixColTitlePurposeGroup {
            get {
                return ResourceManager.GetString("AppendixColTitlePurposeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площа.
        /// </summary>
        internal static string AppendixColTitleSquare {
            get {
                return ResourceManager.GetString("AppendixColTitleSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Права.
        /// </summary>
        internal static string AppendixColTitleTransfers {
            get {
                return ResourceManager.GetString("AppendixColTitleTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАДАНО.
        /// </summary>
        internal static string AppendixTransfersExist {
            get {
                return ResourceManager.GetString("AppendixTransfersExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НЕ ЗАДАНО.
        /// </summary>
        internal static string AppendixTransfersMissing {
            get {
                return ResourceManager.GetString("AppendixTransfersMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОБ&apos;ЄКТ НЕ ЗНАЙДЕНО.
        /// </summary>
        internal static string AppendixUnmatchedObject {
            get {
                return ResourceManager.GetString("AppendixUnmatchedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОТРЕБУЄ КОРЕГУВАННЯ.
        /// </summary>
        internal static string BalansTransferFail {
            get {
                return ResourceManager.GetString("BalansTransferFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАДАНО КОРЕКТНО.
        /// </summary>
        internal static string BalansTransferOK {
            get {
                return ResourceManager.GetString("BalansTransferOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВІД .
        /// </summary>
        internal static string DocTextDatePrefix {
            get {
                return ResourceManager.GetString("DocTextDatePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИЇВСЬКА МІСЬКА ДЕРЖАВНА АДМІНІСТРАЦІЯ.
        /// </summary>
        internal static string DocTextKMDA {
            get {
                return ResourceManager.GetString("DocTextKMDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИЇВСЬКА МІСЬКА РАДА.
        /// </summary>
        internal static string DocTextKMR {
            get {
                return ResourceManager.GetString("DocTextKMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КИЇВ.
        /// </summary>
        internal static string DocTextKyiv {
            get {
                return ResourceManager.GetString("DocTextKyiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N .
        /// </summary>
        internal static string DocTextNumPrefix {
            get {
                return ResourceManager.GetString("DocTextNumPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РІШЕННЯ.
        /// </summary>
        internal static string DocTextRishennya {
            get {
                return ResourceManager.GetString("DocTextRishennya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РОЗПОРЯДЖЕННЯ.
        /// </summary>
        internal static string DocTextRozp {
            get {
                return ResourceManager.GetString("DocTextRozp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СЕСІЯ.
        /// </summary>
        internal static string DocTextSession {
            get {
                return ResourceManager.GetString("DocTextSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Заповнювати не потрібно).
        /// </summary>
        internal static string Inaplicable {
            get {
                return ResourceManager.GetString("Inaplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К..
        /// </summary>
        internal static string KorpusPrefix {
            get {
                return ResourceManager.GetString("KorpusPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер Розпорядження, до якого відноситься Акт.
        /// </summary>
        internal static string LabelMasterDocAct {
            get {
                return ResourceManager.GetString("LabelMasterDocAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер Документу, в який вносяться зміни.
        /// </summary>
        internal static string LabelMasterDocRozp {
            get {
                return ResourceManager.GetString("LabelMasterDocRozp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВУЛ..
        /// </summary>
        internal static string StreetAddrPrefix {
            get {
                return ResourceManager.GetString("StreetAddrPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АДРЕСА:.
        /// </summary>
        internal static string TransferTooltipFormatAddr {
            get {
                return ResourceManager.GetString("TransferTooltipFormatAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОБ&apos;ЄКТ НА БАЛАНСІ: Знайдено.
        /// </summary>
        internal static string TransferTooltipFormatBalansFound {
            get {
                return ResourceManager.GetString("TransferTooltipFormatBalansFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОБ&apos;ЄКТ НА БАЛАНСІ: НЕ ЗНАЙДЕНО.
        /// </summary>
        internal static string TransferTooltipFormatBalansNotFound {
            get {
                return ResourceManager.GetString("TransferTooltipFormatBalansNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВІД:.
        /// </summary>
        internal static string TransferTooltipFormatFrom {
            get {
                return ResourceManager.GetString("TransferTooltipFormatFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРАВО:.
        /// </summary>
        internal static string TransferTooltipFormatRight {
            get {
                return ResourceManager.GetString("TransferTooltipFormatRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПЛОЩА:.
        /// </summary>
        internal static string TransferTooltipFormatSqr {
            get {
                return ResourceManager.GetString("TransferTooltipFormatSqr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДО:.
        /// </summary>
        internal static string TransferTooltipFormatTo {
            get {
                return ResourceManager.GetString("TransferTooltipFormatTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПЕРЕДАЧА:.
        /// </summary>
        internal static string TransferTooltipFormatType {
            get {
                return ResourceManager.GetString("TransferTooltipFormatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПРИЙНЯТТЯ НА БАЛАНС.
        /// </summary>
        internal static string TransferTypeCreate {
            get {
                return ResourceManager.GetString("TransferTypeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВІДЧУЖЕННЯ.
        /// </summary>
        internal static string TransferTypeDestroy {
            get {
                return ResourceManager.GetString("TransferTypeDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З БАЛАНСУ НА БАЛАНС.
        /// </summary>
        internal static string TransferTypeTransfer {
            get {
                return ResourceManager.GetString("TransferTypeTransfer", resourceCulture);
            }
        }
    }
}
