//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUKV.DataMigration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>п/п</string>
  <string>пп</string>
  <string>nn</string>
  <string>n</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColTypeRowIndex {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColTypeRowIndex"]));
            }
            set {
                this["ColTypeRowIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>адрес</string>\r\n  <string>місцезна</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColTypeAddress {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColTypeAddress"]));
            }
            set {
                this["ColTypeAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>довж</string>\r\n  <string>протяжність</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColTypeLength {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColTypeLength"]));
            }
            set {
                this["ColTypeLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>площ</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColTypeSquare {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColTypeSquare"]));
            }
            set {
                this["ColTypeSquare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>діам</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColTypeDiameter {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColTypeDiameter"]));
            }
            set {
                this["ColTypeDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>балансов</string>\r\n  <string>первинн</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColTypeBalansCost {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColTypeBalansCost"]));
            }
            set {
                this["ColTypeBalansCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>залишк</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColTypeFinalCost {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColTypeFinalCost"]));
            }
            set {
                this["ColTypeFinalCost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>рік побудови</string>\r\n  <string>рік прокладки</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColTypeBuildYear {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColTypeBuildYear"]));
            }
            set {
                this["ColTypeBuildYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>рік введення в експлуатацію</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColTypeExplYear {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColTypeExplYear"]));
            }
            set {
                this["ColTypeExplYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ПО ВУЛ</string>
  <string>НА ВУЛ</string>
  <string>ЗА АДРЕСОЮ ВУЛ</string>
  <string>, ВУЛ</string>
  <string>АДРЕСА:</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AddressDividers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AddressDividers"]));
            }
            set {
                this["AddressDividers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>назва</string>\r\n  <string>найменування</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ColTypeObjectName {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColTypeObjectName"]));
            }
            set {
                this["ColTypeObjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ВСЬОГО</string>\r\n  <string>ЗАГАЛЬНА ПЛОЩ</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TotalsRowPrefixes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TotalsRowPrefixes"]));
            }
            set {
                this["TotalsRowPrefixes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>СІЧ</string>
  <string>ЛЮТ</string>
  <string>БЕРЕЗ</string>
  <string>КВІТ</string>
  <string>ТРАВ</string>
  <string>ЧЕРВ</string>
  <string>ЛИП</string>
  <string>СЕРП</string>
  <string>ВЕРЕС</string>
  <string>ЖОВТ</string>
  <string>ЛИСТ</string>
  <string>ГРУД</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MonthNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MonthNames"]));
            }
            set {
                this["MonthNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>СКЛАД=24/362/3/2</string>
  <string>ПРОХІДН=4/51/5/2</string>
  <string>ГАРАЖ=20/289/3/11</string>
  <string>КОТЕЛЬН=21/314/3/2</string>
  <string>ГАЗОПРОВ=21/454/6/9</string>
  <string>КАНАЛІЗАЦ=21/500/6/6</string>
  <string>КАБЕЛЬН=21/450/6/14</string>
  <string>ТЕПЛОВА МЕР=21/452/6/5</string>
  <string>ТЕПЛОВІ МЕР=21/452/6/5</string>
  <string>ВОДОПРОВ=21/501/6/8</string>
  <string>ВОДОПОСТ=21/501/6/8</string>
  <string>ЛАБОРАТОР=17/265/9/2</string>
  <string>ЖИТЛОВИЙ БУДИНОК=1/2/3/4</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ObjectTypeCodes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ObjectTypeCodes"]));
            }
            set {
                this["ObjectTypeCodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ШОСЕ</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StreetHighwayPrefixList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StreetHighwayPrefixList"]));
            }
            set {
                this["StreetHighwayPrefixList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>НАБЕРЕЖНА</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StreetRiverBankPrefixList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StreetRiverBankPrefixList"]));
            }
            set {
                this["StreetRiverBankPrefixList"] = value;
            }
        }
    }
}
