//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressAPITest001
{
    using System;
    using System.Collections.Generic;
    
    public partial class adresesUrbio_street_geolocation
    {
        public System.Guid street_id { get; set; }
        public int rownpp { get; set; }
        public decimal lat { get; set; }
        public decimal lon { get; set; }
    
        public virtual adresesUrbio_street adresesUrbio_street { get; set; }
    }
}
