//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressAPITest001
{
    using System;
    using System.Collections.Generic;
    
    public partial class adresesUrbio_address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adresesUrbio_address()
        {
            this.adresesUrbio_address_geolocation = new HashSet<adresesUrbio_address_geolocation>();
            this.adresesUrbio_address_history = new HashSet<adresesUrbio_address_history>();
            this.adresesUrbio_address_incorrect = new HashSet<adresesUrbio_address_incorrect>();
        }
    
        public System.Guid address_id { get; set; }
        public string fullName { get; set; }
        public string shortName { get; set; }
        public string fullToponym { get; set; }
        public string shortToponym { get; set; }
        public bool isToponymBeforeName { get; set; }
        public string secondLevel_fullName { get; set; }
        public string secondLevel_shortName { get; set; }
        public string secondLevel_fullToponym { get; set; }
        public string secondLevel_shortToponym { get; set; }
        public bool secondLevel_isToponymBeforeName { get; set; }
        public string thirdLevel_fullName { get; set; }
        public string thirdLevel_shortName { get; set; }
        public string thirdLevel_fullToponym { get; set; }
        public string thirdLevel_shortToponym { get; set; }
        public bool thirdLevel_isToponymBeforeName { get; set; }
        public string category_fullText { get; set; }
        public string category_shortText { get; set; }
        public string zip { get; set; }
        public Nullable<System.Guid> street_id { get; set; }
        public string street_fullName { get; set; }
        public string street_shortName { get; set; }
        public string street_fullToponym { get; set; }
        public string street_shortToponym { get; set; }
        public bool street_isToponymBeforeName { get; set; }
        public Nullable<System.Guid> district_id { get; set; }
        public string district_fullName { get; set; }
        public string district_shortName { get; set; }
        public string district_fullToponym { get; set; }
        public string district_shortToponym { get; set; }
        public bool district_isToponymBeforeName { get; set; }
        public string asString { get; set; }
        public string locale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adresesUrbio_address_geolocation> adresesUrbio_address_geolocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adresesUrbio_address_history> adresesUrbio_address_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adresesUrbio_address_incorrect> adresesUrbio_address_incorrect { get; set; }
    }
}
