CREATE TABLE [yurdep].[stp] (
    [stp_id]    INT           NOT NULL,
    [delo_id]   INT           NULL,
    [styp]      VARCHAR (30)  NULL,
    [dat]       DATETIME      NULL,
    [num]       VARCHAR (100) NULL,
    [otdel]     VARCHAR (255) NULL,
    [predmet]   TEXT          NULL,
    [vdat]      DATETIME      NULL,
    [vnum]      VARCHAR (100) NULL,
    [sud]       VARCHAR (255) NULL,
    [rdat]      DATETIME      NULL,
    [viddoc]    VARCHAR (255) NULL,
    [vimoga]    TEXT          NULL,
    [smon]      FLOAT (53)    NULL,
    [prim]      TEXT          NULL,
    [prokur]    VARCHAR (255) NULL,
    [uusr]      VARCHAR (255) NULL,
    [ztime]     DATETIME      NULL,
    [rez]       SMALLINT      NULL,
    [zp_smon]   FLOAT (53)    NULL,
    [zp_vimoga] TEXT          NULL,
    [zp_rez]    SMALLINT      NULL,
    [skarg]     VARCHAR (255) NULL,
    [vstan]     SMALLINT      NULL,
    [vikonav]   VARCHAR (255) NULL,
    [lsud_all]  VARCHAR (255) NULL,
    [lsud_1]    VARCHAR (255) NULL,
    [lsud_2]    VARCHAR (255) NULL,
    [lsud_3]    VARCHAR (255) NULL,
    [lsud_4]    VARCHAR (255) NULL,
    [lsud_5]    VARCHAR (255) NULL,
    [lsud_6]    VARCHAR (255) NULL,
    [lsud_7]    VARCHAR (255) NULL,
    [rusr]      VARCHAR (255) NULL,
    [rusrrv]    VARCHAR (255) NULL,
    CONSTRAINT [stp_x] PRIMARY KEY CLUSTERED ([stp_id] ASC)
);

