
SET NAMES WIN1251;

/* SORG_1NF modifications */

ALTER TABLE SORG_1NF ADD EIS_ADDR_STREET_ID INTEGER;
ALTER TABLE SORG_1NF ADD EIS_DIRECTOR_EMAIL VARCHAR(100);
ALTER TABLE SORG_1NF ADD EIS_PHYS_ADDR_STREET_ID INTEGER;
ALTER TABLE SORG_1NF ADD EIS_PHYS_ADDR_DISTRICT_ID INTEGER;
ALTER TABLE SORG_1NF ADD EIS_PHYS_ADDR_NOMER VARCHAR(60);
ALTER TABLE SORG_1NF ADD EIS_PHYS_ADDR_ZIP_CODE VARCHAR(24);
ALTER TABLE SORG_1NF ADD EIS_PHYS_ADDR_MISC VARCHAR(150);
ALTER TABLE SORG_1NF ADD EIS_CONTRIB_RATE INTEGER;
ALTER TABLE SORG_1NF ADD EIS_BUH_EMAIL VARCHAR(100);

ALTER TABLE SORG_1NF ADD EIS_BUDGET_NARAH_50_UAH NUMERIC(15,3);
ALTER TABLE SORG_1NF ADD EIS_BUDGET_ZVIT_50_UAH NUMERIC(15,3);
ALTER TABLE SORG_1NF ADD EIS_BUDGET_PREV_50_UAH NUMERIC(15,3);
ALTER TABLE SORG_1NF ADD EIS_BUDGET_DEBT_30_50_UAH NUMERIC(15,3);
ALTER TABLE SORG_1NF ADD EIS_IS_SPECIAL_ORG INTEGER;
ALTER TABLE SORG_1NF ADD EIS_PAYMENT_BUDGET_SPECIAL NUMERIC(15,3);
ALTER TABLE SORG_1NF ADD EIS_KONKURS_PAYMENTS NUMERIC(15,3);
ALTER TABLE SORG_1NF ADD EIS_UNKNOWN_PAYMENTS NUMERIC(15,3);
ALTER TABLE SORG_1NF ADD EIS_UNKNOWN_PAYMENT_NOTE VARCHAR(510);

ALTER TABLE TAR_SORG_1NF ADD EIS_ADDR_STREET_ID INTEGER;
ALTER TABLE TAR_SORG_1NF ADD EIS_DIRECTOR_EMAIL VARCHAR(100);
ALTER TABLE TAR_SORG_1NF ADD EIS_PHYS_ADDR_STREET_ID INTEGER;
ALTER TABLE TAR_SORG_1NF ADD EIS_PHYS_ADDR_DISTRICT_ID INTEGER;
ALTER TABLE TAR_SORG_1NF ADD EIS_PHYS_ADDR_NOMER VARCHAR(60);
ALTER TABLE TAR_SORG_1NF ADD EIS_PHYS_ADDR_ZIP_CODE VARCHAR(24);
ALTER TABLE TAR_SORG_1NF ADD EIS_PHYS_ADDR_MISC VARCHAR(150);
ALTER TABLE TAR_SORG_1NF ADD EIS_CONTRIB_RATE INTEGER;
ALTER TABLE TAR_SORG_1NF ADD EIS_BUH_EMAIL VARCHAR(100);

ALTER TABLE TAR_SORG_1NF ADD EIS_BUDGET_NARAH_50_UAH NUMERIC(15,3);
ALTER TABLE TAR_SORG_1NF ADD EIS_BUDGET_ZVIT_50_UAH NUMERIC(15,3);
ALTER TABLE TAR_SORG_1NF ADD EIS_BUDGET_PREV_50_UAH NUMERIC(15,3);
ALTER TABLE TAR_SORG_1NF ADD EIS_BUDGET_DEBT_30_50_UAH NUMERIC(15,3);
ALTER TABLE TAR_SORG_1NF ADD EIS_IS_SPECIAL_ORG INTEGER;
ALTER TABLE TAR_SORG_1NF ADD EIS_PAYMENT_BUDGET_SPECIAL NUMERIC(15,3);
ALTER TABLE TAR_SORG_1NF ADD EIS_KONKURS_PAYMENTS NUMERIC(15,3);
ALTER TABLE TAR_SORG_1NF ADD EIS_UNKNOWN_PAYMENTS NUMERIC(15,3);
ALTER TABLE TAR_SORG_1NF ADD EIS_UNKNOWN_PAYMENT_NOTE VARCHAR(510);

/* OBJECT_1NF modifications */

ALTER TABLE OBJECT_1NF ADD EIS_EXPL_ENTER_YEAR INTEGER;
ALTER TABLE OBJECT_1NF ADD EIS_BASEMENT_EXISTS INTEGER;
ALTER TABLE OBJECT_1NF ADD EIS_LOFT_EXISTS INTEGER;
ALTER TABLE OBJECT_1NF ADD EIS_LOFT_SQUARE NUMERIC(9,2);

ALTER TABLE TAR_OBJECT_1NF ADD EIS_EXPL_ENTER_YEAR INTEGER;
ALTER TABLE TAR_OBJECT_1NF ADD EIS_BASEMENT_EXISTS INTEGER;
ALTER TABLE TAR_OBJECT_1NF ADD EIS_LOFT_EXISTS INTEGER;
ALTER TABLE TAR_OBJECT_1NF ADD EIS_LOFT_SQUARE NUMERIC(9,2);

/* BALANS_1NF modifications */

ALTER TABLE BALANS_1NF ADD EIS_FREE_SQR_EXISTS INTEGER;
ALTER TABLE BALANS_1NF ADD EIS_FREE_SQR_USEFUL NUMERIC(9,2);
ALTER TABLE BALANS_1NF ADD EIS_FREE_SQR_CONDITION INTEGER;
ALTER TABLE BALANS_1NF ADD EIS_FREE_SQR_LOCATION VARCHAR(100);
ALTER TABLE BALANS_1NF ADD EIS_OWNERSHIP_DOC_TYPE INTEGER;
ALTER TABLE BALANS_1NF ADD EIS_OWNERSHIP_DOC_NUM VARCHAR(24);
ALTER TABLE BALANS_1NF ADD EIS_OWNERSHIP_DOC_DATE DATE;
ALTER TABLE BALANS_1NF ADD EIS_BALANS_DOC_TYPE INTEGER;
ALTER TABLE BALANS_1NF ADD EIS_BALANS_DOC_NUM VARCHAR(24);
ALTER TABLE BALANS_1NF ADD EIS_BALANS_DOC_DATE DATE;
ALTER TABLE BALANS_1NF ADD EIS_VIDCH_DOC_TYPE INTEGER;
ALTER TABLE BALANS_1NF ADD EIS_VIDCH_DOC_NUM VARCHAR(24);
ALTER TABLE BALANS_1NF ADD EIS_VIDCH_DOC_DATE DATE;
ALTER TABLE BALANS_1NF ADD EIS_VIDCH_TYPE_ID INTEGER;
ALTER TABLE BALANS_1NF ADD EIS_VIDCH_ORG_ID INTEGER;
ALTER TABLE BALANS_1NF ADD EIS_VIDCH_COST NUMERIC(15,3);
ALTER TABLE BALANS_1NF ADD EIS_SQR_ENGINEERING NUMERIC(9,2);
ALTER TABLE BALANS_1NF ADD EIS_OBJ_STATUS_ID INTEGER;

ALTER TABLE TAR_BALANS_1NF ADD EIS_FREE_SQR_EXISTS INTEGER;
ALTER TABLE TAR_BALANS_1NF ADD EIS_FREE_SQR_USEFUL NUMERIC(9,2);
ALTER TABLE TAR_BALANS_1NF ADD EIS_FREE_SQR_CONDITION INTEGER;
ALTER TABLE TAR_BALANS_1NF ADD EIS_FREE_SQR_LOCATION VARCHAR(100);
ALTER TABLE TAR_BALANS_1NF ADD EIS_OWNERSHIP_DOC_TYPE INTEGER;
ALTER TABLE TAR_BALANS_1NF ADD EIS_OWNERSHIP_DOC_NUM VARCHAR(24);
ALTER TABLE TAR_BALANS_1NF ADD EIS_OWNERSHIP_DOC_DATE DATE;
ALTER TABLE TAR_BALANS_1NF ADD EIS_BALANS_DOC_TYPE INTEGER;
ALTER TABLE TAR_BALANS_1NF ADD EIS_BALANS_DOC_NUM VARCHAR(24);
ALTER TABLE TAR_BALANS_1NF ADD EIS_BALANS_DOC_DATE DATE;
ALTER TABLE TAR_BALANS_1NF ADD EIS_VIDCH_DOC_TYPE INTEGER;
ALTER TABLE TAR_BALANS_1NF ADD EIS_VIDCH_DOC_NUM VARCHAR(24);
ALTER TABLE TAR_BALANS_1NF ADD EIS_VIDCH_DOC_DATE DATE;
ALTER TABLE TAR_BALANS_1NF ADD EIS_VIDCH_TYPE_ID INTEGER;
ALTER TABLE TAR_BALANS_1NF ADD EIS_VIDCH_ORG_ID INTEGER;
ALTER TABLE TAR_BALANS_1NF ADD EIS_VIDCH_COST NUMERIC(15,3);
ALTER TABLE TAR_BALANS_1NF ADD EIS_SQR_ENGINEERING NUMERIC(9,2);
ALTER TABLE TAR_BALANS_1NF ADD EIS_OBJ_STATUS_ID INTEGER;

/* ARENDA1NF modifications */

ALTER TABLE ARENDA1NF ADD EIS_AGREEMENT_STATE INTEGER;
ALTER TABLE ARENDA1NF ADD EIS_IS_INSURED INTEGER;
ALTER TABLE ARENDA1NF ADD EIS_INSURANCE_START DATE;
ALTER TABLE ARENDA1NF ADD EIS_INSURANCE_END DATE;
ALTER TABLE ARENDA1NF ADD EIS_INSURANCE_SUM NUMERIC(15,2);
ALTER TABLE ARENDA1NF ADD EIS_IS_LOAN_AGREEMENT INTEGER;

ALTER TABLE TAR_ARENDA1NF ADD EIS_AGREEMENT_STATE INTEGER;
ALTER TABLE TAR_ARENDA1NF ADD EIS_IS_INSURED INTEGER;
ALTER TABLE TAR_ARENDA1NF ADD EIS_INSURANCE_START DATE;
ALTER TABLE TAR_ARENDA1NF ADD EIS_INSURANCE_END DATE;
ALTER TABLE TAR_ARENDA1NF ADD EIS_INSURANCE_SUM NUMERIC(15,2);
ALTER TABLE TAR_ARENDA1NF ADD EIS_IS_LOAN_AGREEMENT INTEGER;

/* ARENDA_PRIM modifications */

ALTER TABLE ARENDA_PRIM ADD EIS_INVENT_NO VARCHAR(128);
ALTER TABLE ARENDA_PRIM ADD EIS_PRIM_STATUS INTEGER;

ALTER TABLE TAR_ARENDA_PRIM ADD EIS_INVENT_NO VARCHAR(128);
ALTER TABLE TAR_ARENDA_PRIM ADD EIS_PRIM_STATUS INTEGER;

/* New fields for long user names */

ALTER TABLE SORG_1NF ADD EIS_MODIFIED_BY VARCHAR(64);
ALTER TABLE TAR_SORG_1NF ADD EIS_MODIFIED_BY VARCHAR(64);

ALTER TABLE OBJECT_1NF ADD EIS_MODIFIED_BY VARCHAR(64);
ALTER TABLE TAR_OBJECT_1NF ADD EIS_MODIFIED_BY VARCHAR(64);

ALTER TABLE BALANS_1NF ADD EIS_MODIFIED_BY VARCHAR(64);
ALTER TABLE TAR_BALANS_1NF ADD EIS_MODIFIED_BY VARCHAR(64);

ALTER TABLE ARENDA1NF ADD EIS_MODIFIED_BY VARCHAR(64);
ALTER TABLE TAR_ARENDA1NF ADD EIS_MODIFIED_BY VARCHAR(64);
