//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUKV.DataMigration.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUKV.DataMigration.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Колонка.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Договори оренди.
        /// </summary>
        internal static string ColumnTreeArendaRoot {
            get {
                return ResourceManager.GetString("ColumnTreeArendaRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єкти на балансі.
        /// </summary>
        internal static string ColumnTreeBalansRoot {
            get {
                return ResourceManager.GetString("ColumnTreeBalansRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ця колонка походить з вхідного документу. Ви дійсно бажаєте видалити її?.
        /// </summary>
        internal static string ConfirmationDelSrcColumn {
            get {
                return ResourceManager.GetString("ConfirmationDelSrcColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РІГ.
        /// </summary>
        internal static string CrossRoadPrefix {
            get {
                return ResourceManager.GetString("CrossRoadPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка при відкритті документу.
        /// </summary>
        internal static string DocOpenError {
            get {
                return ResourceManager.GetString("DocOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка під час запису документу.
        /// </summary>
        internal static string DocSaveError {
            get {
                return ResourceManager.GetString("DocSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка при записі файлу. Можливо, файл є відкритим в іншій програмі..
        /// </summary>
        internal static string ErrorCannotSaveDoc {
            get {
                return ResourceManager.GetString("ErrorCannotSaveDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТОЧНЕ СПІВСТАВЛЕННЯ АДРЕСИ НЕ Є МОЖЛИВИМ. НЕОБХІДНА ПЕРЕВІРКА.
        /// </summary>
        internal static string ErrorInpreciseMatch {
            get {
                return ResourceManager.GetString("ErrorInpreciseMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь ласка, виберіть одну ячейку в стовпчику, який необхідно видалити.
        /// </summary>
        internal static string ErrorMultipleDelCells {
            get {
                return ResourceManager.GetString("ErrorMultipleDelCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь ласка, виберіть одну ячейку, що містить назву колонки з адресою.
        /// </summary>
        internal static string ErrorMultipleSelCells {
            get {
                return ResourceManager.GetString("ErrorMultipleSelCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь ласка, спочатку вкажіть колонку, в якій зберігається адреса об&apos;єктів.
        /// </summary>
        internal static string ErrorNoAddressColumn {
            get {
                return ResourceManager.GetString("ErrorNoAddressColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь ласка, спочатку відкрийте документ з переліком адрес об&apos;єктів.
        /// </summary>
        internal static string ErrorNoData {
            get {
                return ResourceManager.GetString("ErrorNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка під час з&apos;єднання з базою даних:.
        /// </summary>
        internal static string ErrorNoDbConnection {
            get {
                return ResourceManager.GetString("ErrorNoDbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не знайдено файл конфігурації. Робота програми неможлива..
        /// </summary>
        internal static string ErrorNoIniFile {
            get {
                return ResourceManager.GetString("ErrorNoIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані збережено.
        /// </summary>
        internal static string MsgDataSaved {
            get {
                return ResourceManager.GetString("MsgDataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОСП..
        /// </summary>
        internal static string StreetKindAvenueCorrect {
            get {
                return ResourceManager.GetString("StreetKindAvenueCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БУЛЬВ..
        /// </summary>
        internal static string StreetKindBoulevardCorrect {
            get {
                return ResourceManager.GetString("StreetKindBoulevardCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОВ..
        /// </summary>
        internal static string StreetKindLaneCorrect {
            get {
                return ResourceManager.GetString("StreetKindLaneCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЛ..
        /// </summary>
        internal static string StreetKindSquareCorrect {
            get {
                return ResourceManager.GetString("StreetKindSquareCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВУЛ..
        /// </summary>
        internal static string StreetSuffix1 {
            get {
                return ResourceManager.GetString("StreetSuffix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВУЛ.
        /// </summary>
        internal static string StreetSuffix2 {
            get {
                return ResourceManager.GetString("StreetSuffix2", resourceCulture);
            }
        }
    }
}
