//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUKV.DataMigration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>street_full_name=Назва Вулиці</string>
  <string>addr_nomer=Номер Будинку</string>
  <string>district=Район</string>
  <string>addr_zip_code=Поштовий Індекс</string>
  <string>num_floors=Кількість Поверхів</string>
  <string>construct_year=Рік Побудови</string>
  <string>history=Історична Цінність</string>
  <string>object_kind=Вид Об'єкту</string>
  <string>object_type=Тип Об'єкту</string>
  <string>sqr_total=Загальна Площа</string>
  <string>sqr_habit=Житлова Площа</string>
  <string>sqr_non_habit=Нежитлова Площа</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ObjectPropList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ObjectPropList"]));
            }
            set {
                this["ObjectPropList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>org_full_name=Повна Назва Балансоутримувача</string>\r\n  <string>org_short_" +
            "name=Коротка Назва Балансоутримувача</string>\r\n  <string>org_zkpo_code=Код ЄДРПО" +
            "У</string>\r\n  <string>org_industry=Галузь</string>\r\n  <string>org_occupation=Вид" +
            " Діяльності</string>\r\n  <string>district=Район Будинку</string>\r\n  <string>stree" +
            "t_full_name=Назва Вулиці</string>\r\n  <string>addr_nomer=Номер Будинку</string>\r\n" +
            "  <string>sqr_total=Загальна Площа (кв.м.)</string>\r\n  <string>sqr_pidval=Підвал" +
            "ьна Площа (кв.м.)</string>\r\n  <string>sqr_vlas_potreb=Площа Для Власних Потреб (" +
            "кв.м.)</string>\r\n  <string>sqr_free=Вільна Площа (кв.м.)</string>\r\n  <string>sqr" +
            "_in_rent=Площа Надана В Оренду (кв.м.)</string>\r\n  <string>sqr_privatizov=Приват" +
            "изована Площа (кв.м.)</string>\r\n  <string>sqr_not_for_rent=Площа Не Для Оренди (" +
            "кв.м.)</string>\r\n  <string>sqr_gurtoj=Площа Гуртожитку (кв.м.)</string>\r\n  <stri" +
            "ng>sqr_non_habit=Нежитлова Площа (кв.м.)</string>\r\n  <string>cost_balans=Балансо" +
            "ва Вартість (тис.грн.)</string>\r\n  <string>cost_expert_1m=Експертна Вартість За " +
            "Кв.м. (тис.грн.)</string>\r\n  <string>cost_expert_total=Експертна Вартість (тис.г" +
            "рн.)</string>\r\n  <string>cost_zalishkova=Залишкова Вартість (тис.грн.)</string>\r" +
            "\n  <string>num_rent_agr=Кількість Договорів Оренди</string>\r\n  <string>num_priva" +
            "t_apt=Кількість Приватизованих Приміщень</string>\r\n  <string>approval_by=Дозвіл " +
            "- Джерело</string>\r\n  <string>approval_num=Дозвіл - Номер</string>\r\n  <string>ap" +
            "proval_date=Дозвіл - Дата</string>\r\n  <string>bti_condition=Документація БТІ</st" +
            "ring>\r\n  <string>num_floors=Кількість Поверхів</string>\r\n  <string>org_maintaine" +
            "r_full_name=Повна Назва Утримуючої Організації</string>\r\n  <string>org_maintaine" +
            "r_short_name=Коротка Назва Утримуючої Організації</string>\r\n  <string>org_mainta" +
            "iner_zkpo_code=Код ЄДРПОУ Утримуючої Організації</string>\r\n  <string>otdel_gukv=" +
            "Відділ ДКВ</string>\r\n  <string>form_ownership=Форма Власності Об\'єкту</string>\r\n" +
            "  <string>ownership_type=Право</string>\r\n  <string>object_kind=Вид Об\'єкту</stri" +
            "ng>\r\n  <string>object_type=Тип Об\'єкту</string>\r\n  <string>condition=Стан Об\'єкт" +
            "у</string>\r\n  <string>purpose_group=Група Призначення</string>\r\n  <string>purpos" +
            "e=Призначення</string>\r\n  <string>history=Історична Цінність</string>\r\n  <string" +
            ">date_expert=Дата Експертної Оцінки</string>\r\n  <string>floors=Поверхи</string>\r" +
            "\n  <string>obj_bti_code=Код БТІ</string>\r\n  <string>memo=Додаткова Інформація</s" +
            "tring>\r\n  <string>note=Примітка</string>\r\n  <string>znos=Знос (грн.)</string>\r\n " +
            " <string>znos_date=Знос станом на</string>\r\n  <string>org_vedomstvo=Орган Управл" +
            "іння Балансоутримувача</string>\r\n  <string>org_ownership=Форма Власності Балансо" +
            "утримувача</string>\r\n  <string>input_date=Дата Актуальності</string>\r\n</ArrayOfS" +
            "tring>")]
        public global::System.Collections.Specialized.StringCollection BalansPropList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BalansPropList"]));
            }
            set {
                this["BalansPropList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>org_balans_full_name=Назва Балансоутримувача</string>\r\n  <string>org_balan" +
            "s_short_name=Коротка Назва Балансоутримувача</string>\r\n  <string>org_balans_zkpo" +
            "=Код ЄДРПОУ Балансоутримувача</string>\r\n  <string>org_balans_industry=Галузь Бал" +
            "ансоутримувача</string>\r\n  <string>org_balans_occupation=Вид Діяльності Балансоу" +
            "тримувача</string>\r\n  <string>balans_org_ownership=Форма Власності Балансоутриму" +
            "вача</string>\r\n  <string>org_renter_full_name=Назва Орендаря</string>\r\n  <string" +
            ">org_renter_short_name=Коротка Назва Орендаря</string>\r\n  <string>org_renter_zkp" +
            "o=Код ЄДРПОУ Орендаря</string>\r\n  <string>org_renter_industry=Галузь Орендаря</s" +
            "tring>\r\n  <string>org_renter_occupation=Вид Діяльності Орендаря</string>\r\n  <str" +
            "ing>org_giver_full_name=Назва Орендодавця</string>\r\n  <string>org_giver_short_na" +
            "me=Коротка Назва Орендодавця</string>\r\n  <string>org_giver_zkpo=Код ЄДРПОУ Оренд" +
            "одавця</string>\r\n  <string>org_giver_industry=Галузь Орендодавця</string>\r\n  <st" +
            "ring>org_giver_occupation=Вид Діяльності Орендодавця</string>\r\n  <string>distric" +
            "t=Район Будинку</string>\r\n  <string>street_full_name=Назва Вулиці</string>\r\n  <s" +
            "tring>addr_nomer=Номер Будинку</string>\r\n  <string>object_name=Використання Прим" +
            "іщення</string>\r\n  <string>object_note=Примітка</string>\r\n  <string>purpose_grou" +
            "p=Група Призначення</string>\r\n  <string>purpose=Призначення</string>\r\n  <string>" +
            "is_privat=Приватизовано</string>\r\n  <string>agreement_kind=Тип Договору Оренди</" +
            "string>\r\n  <string>agreement_date=Дата Договору Оренди</string>\r\n  <string>agree" +
            "ment_date_year=Дата Договору Оренди - Рік</string>\r\n  <string>agreement_date_qua" +
            "rter=Дата Договору Оренди - Квартал</string>\r\n  <string>agreement_num=Номер Дого" +
            "вору Оренди</string>\r\n  <string>floor_number=Поверх</string>\r\n  <string>cost_agr" +
            "eement=Орендна Плата по Договору (грн.)</string>\r\n  <string>cost_expert_1m=Експе" +
            "ртна Вартість За Кв.м. (грн.)</string>\r\n  <string>cost_expert_total=Експертна Ва" +
            "ртість (грн.)</string>\r\n  <string>pidstava_display=Підстави Для Оренди</string>\r" +
            "\n  <string>rent_start_date=Початок Оренди</string>\r\n  <string>rent_start_year=По" +
            "чаток Оренди - Рік</string>\r\n  <string>rent_start_quarter=Початок Оренди - Кварт" +
            "ал</string>\r\n  <string>rent_finish_date=Закінчення Оренди</string>\r\n  <string>re" +
            "nt_finish_year=Закінчення Оренди - Рік</string>\r\n  <string>rent_finish_quarter=З" +
            "акінчення Оренди - Квартал</string>\r\n  <string>rent_actual_finish_date=Фактичне " +
            "Закінчення Оренди</string>\r\n  <string>actual_finish_year=Фактичне Закінчення Оре" +
            "нди - Рік</string>\r\n  <string>actual_finish_quarter=Фактичне Закінчення Оренди -" +
            " Квартал</string>\r\n  <string>rent_rate_percent=Ставка</string>\r\n  <string>rent_r" +
            "ate_uah=Ставка (грн.)</string>\r\n  <string>rent_square=Площа (кв.м.)</string>\r\n  " +
            "<string>num_akt=Номер Акту</string>\r\n  <string>date_akt=Дата Акту</string>\r\n  <s" +
            "tring>is_subarenda=Субаренда</string>\r\n  <string>payment_type=Вид Розрахунків</s" +
            "tring>\r\n  <string>org_balans_vedomstvo=Орган Управління Балансоутримувача</strin" +
            "g>\r\n  <string>org_renter_vedomstvo=Орган Управління Орендаря</string>\r\n  <string" +
            ">org_giver_vedomstvo=Орган Управління Орендодавця</string>\r\n  <string>balans_sqr" +
            "_total=Загальна Площа На Балансі Балансоутримувача (кв.м.)</string>\r\n  <string>b" +
            "alans_num_rent_agr=Кількість Договорів Оренди Балансоутримувача</string>\r\n  <str" +
            "ing>balans_sqr_in_rent=Загальна Площа Балансоутримувача Надана В Оренду (кв.м.)<" +
            "/string>\r\n  <string>balans_form_ownership=Форма Власності Об\'єкту</string>\r\n</Ar" +
            "rayOfString>")]
        public global::System.Collections.Specialized.StringCollection ArendaPropList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ArendaPropList"]));
            }
            set {
                this["ArendaPropList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>org_balans=Балансоутримувач</string>\r\n  <string>org_balans_zkpo=Код ЄДРПОУ" +
            " Балансоутримувача</string>\r\n  <string>subord_code=Сфера Управління Об\'єкту</str" +
            "ing>\r\n  <string>subordination=Назва Сфери Управління Об\'єкту</string>\r\n  <string" +
            ">district=Район</string>\r\n  <string>street_full_name=Назва Вулиці</string>\r\n  <s" +
            "tring>addr_nomer=Номер Будинку</string>\r\n  <string>obj_name=Назва Об\'єкту</strin" +
            "g>\r\n  <string>org_name=Покупець</string>\r\n  <string>org_address=Адреса Покупця</" +
            "string>\r\n  <string>director_fio=ПІБ Директора Покупця</string>\r\n  <string>direct" +
            "or_phone=Тел. Директора Покупця</string>\r\n  <string>sqr_total=Загальна Площа Об\'" +
            "єкту (кв.м.)</string>\r\n  <string>obj_group=Група Об\'єкту</string>\r\n  <string>pri" +
            "vat_kind=Спосіб Приватизації</string>\r\n  <string>privat_state=Стан</string>\r\n  <" +
            "string>purpose_group=Група Призначення Об\'єкту</string>\r\n  <string>object_kind=В" +
            "ид Об\'єкту</string>\r\n  <string>object_type=Тип Об\'єкту</string>\r\n  <string>obj_f" +
            "loor=Поверх</string>\r\n  <string>cost=Вартість (грн.)</string>\r\n  <string>cost_ex" +
            "pert=Експертна Оцінка</string>\r\n  <string>expert_date=Дата Експертної Оцінки</st" +
            "ring>\r\n  <string>note=Примітка</string>\r\n  <string>rishennya_num=Номер Рішення</" +
            "string>\r\n  <string>rishennya_date=Дата Рішення</string>\r\n  <string>rishennya_top" +
            "ic=Назва Рішення</string>\r\n  <string>rishennya_search_name=Рішення</string>\r\n  <" +
            "string>agreement_num=Номер Договору</string>\r\n  <string>agreement_date=Дата Дого" +
            "вору</string>\r\n  <string>agreement_topic=Назва Договору</string>\r\n  <string>agre" +
            "ement_search_name=Договір</string>\r\n  <string>akt_num=Номер Акту</string>\r\n  <st" +
            "ring>akt_date=Дата Акту</string>\r\n  <string>akt_topic=Назва Акту</string>\r\n  <st" +
            "ring>akt_search_name=Акт Приймання-Передачі</string>\r\n  <string>object_history=І" +
            "сторична Цінність</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PrivatPropList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PrivatPropList"]));
            }
            set {
                this["PrivatPropList"] = value;
            }
        }
    }
}
