//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxHtmlEditor_v13_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxHtmlEditor_v13_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxHtmlEditor_v13_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constrain Proportions On.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_Alt_ConstrainProportions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.Alt_ConstrainProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constrain Proportions Off.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_Alt_ConstrainProportionsOff {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.Alt_ConstrainProportionsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonCancel {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonChange {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonInsert {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonOk {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ButtonSelect {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ButtonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ChangeImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Link.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ChangeLink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ChangeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ChangeTableColumn_Size {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ChangeTableColumn_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply CSS.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandApplyCss {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandApplyCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Color.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandBackColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandBold {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet List.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandBulletList {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandBulletList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Center.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCenter {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Spelling.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCheckSpelling {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCheckSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCopy {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandCut {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fore Color.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandForeColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandFullscreen {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandIndent {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandItalic {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandJustify {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Left.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandLeft {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered List.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandOrderedList {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdent.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandOutdent {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandOutdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandPaste {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from Word.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandPasteRtf {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandPasteRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandPrint {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandRedo {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Format.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandRemoveFormat {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandRemoveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Right.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandRight {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandStrikethrough {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandStrikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandSubscript {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandSubscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandSuperscript {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandSuperscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandUnderline {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandUndo {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Link.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_CommandUnlink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.CommandUnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_ChangeImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Link....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_ChangeLink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_ChangeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Properties....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_TableCellProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_TableCellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Properties....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_TableColumnProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_TableColumnProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Properties....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_TableProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_TableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Properties....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ContextMenu_TableRowProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ContextMenu_TableRowProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTML content is invalid.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DefaultErrorText {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DefaultErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Table.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DeleteTable {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Column.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DeleteTableColumn {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DeleteTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DeleteTableRow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DeleteTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_DesignViewTab {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.DesignViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Name.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_FontName {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_FontSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_HtmlViewTab {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.HtmlViewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create thumbnail.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_CreateThumbnail {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_CreateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom size.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_CustomSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_CustomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Description {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Height {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New image name.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_NewImageName {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_NewImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original image size.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_OriginalSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pixels.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Pixels {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Position {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_PositionCenter {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_PositionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-aligned.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_PositionLeft {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_PositionLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-aligned.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_PositionRight {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_PositionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Size {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_ImageProps_Width {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.ImageProps_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter image web address.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_EnterUrl {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_EnterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From your computer.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_FromLocal {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_FromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the web (URL).
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_FromWeb {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_FromWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More options.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_MoreOptions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_MoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image preview.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_Preview {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file to server.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_SaveToServer {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_SaveToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke a dialog allowing you to select an image.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_SelectImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse your computer for the image file to upload.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_UploadInstructions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_UploadInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap text around image.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertImage_UseFloat {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertImage_UseFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Link.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Properties.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_DisplayProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_DisplayProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Email {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail to.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_EmailTo {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_EmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new window.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_OpenInNewWindow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke a dialog allowing you to select a document.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_SelectDocument {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_SelectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Subject {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Text {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertLink_Url {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertLink_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Table....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Column to the Left.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTableColumnToLeft {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTableColumnToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Column to the Right.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTableColumnToRight {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTableColumnToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Row Above.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTableRowAbove {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTableRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Row Below.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTableRowBelow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTableRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Accessibility {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Alignment {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Alignment_Center {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Alignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Alignment_Left {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Alignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Alignment_Right {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Alignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Appearance {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to all cells in the table.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_ApplyToAllCell {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_ApplyToAllCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoFit to contents.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_AutoFitToContent {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_AutoFitToContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_BgColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_BgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border color.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_BorderColor {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border size.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_BorderSize {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_BorderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Both {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Caption {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell padding.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_CellPaddings {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_CellPaddings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell spacing.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_CellSpacing {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_CellSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Columns {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Custom {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal column widths.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_EqualColumnWidths {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_EqualColumnWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Column.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_FirstColumn {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_FirstColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Row.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_FirstRow {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_FirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full width.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_FullWidth {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_FullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Headers {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Height {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_HorzAlignment {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_HorzAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Layout {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_None {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Rows {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Size.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Size {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Summary {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_VAlignment_Bottom {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_VAlignment_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_VAlignment_Middle {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_VAlignment_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_VAlignment_Top {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_VAlignment_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_VertAlignment {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_VertAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InsertTable_Width {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InsertTable_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL format, or a file cannot be found using this URL.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_InvalidUrlErrorText {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.InvalidUrlErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Down.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_MergeTableCellDown {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.MergeTableCellDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Right.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_MergeTableCellHorizontal {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.MergeTableCellHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_Paragraph {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste inside the following box and hit OK..
        /// </summary>
        internal static string ASPxHtmlEditorStringId_PasteRtf_Instructions {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.PasteRtf_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strip font family.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_PasteRtf_StripFont {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.PasteRtf_StripFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_PreviewTab {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.PreviewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_RequiredFieldError {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content of the editor cannot be empty.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_RequiredHtmlContentError {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.RequiredHtmlContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Open XML (.docx).
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsDocx {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsDocx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to DOCX file and save it to a local disk.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsDocx_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsDocx_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME HTML (.mht).
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsMht {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsMht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to MHT file and save it to a local disk.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsMht_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsMht_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Document (.odt).
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsOdt {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsOdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to ODT file and save it to a local disk.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsOdt_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsOdt_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Document (.pdf).
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsPdf {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF file and save it to a local disk.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsPdf_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsPdf_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text (.rtf).
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsRtf {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsRtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to RTF file and save it to a local disk.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsRtf_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsRtf_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text (.txt).
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsTxt {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to TXT file and save it to a local disk.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SaveAsTxt_ToolTip {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SaveAsTxt_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SelectAll {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Document.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SelectDocument {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SelectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SelectImage {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Horizontally.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SplitTableCellHorizontal {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SplitTableCellHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Vertically.
        /// </summary>
        internal static string ASPxHtmlEditorStringId_SplitTableCellVertical {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.SplitTableCellVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Properties....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_TableCellProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.TableCellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Properties....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_TableColumnProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.TableColumnProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Properties....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_TableProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.TableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Properties....
        /// </summary>
        internal static string ASPxHtmlEditorStringId_TableRowProperties {
            get {
                return ResourceManager.GetString("ASPxHtmlEditorStringId.TableRowProperties", resourceCulture);
            }
        }
    }
}
