//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxGridView_v13_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxGridView_v13_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxGridView_v13_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Collapse].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_Collapse {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_DragAndDropHideColumnIcon {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_DragAndDropHideColumnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Expand].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_Expand {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Condition].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_FilterRowButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_FilterRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Filter].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_HeaderFilterButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_HeaderFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Filtered].
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_HeaderFilterButtonActive {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_HeaderFilterButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ascending).
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_SortedAscending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Descending).
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_SortedDescending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins with.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterBeginsWith {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterContains {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t contain.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterDoesNotContain {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterEndsWith {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterEquals {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterGreater {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than or equal to.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterGreaterOrEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLess {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than or equal to.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLessOrEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like (&apos;%&apos;, &apos;_&apos;).
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLike {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two wildcard symbols are supported:
        /// &apos;%&apos; substitutes zero or more characters;
        /// &apos;_&apos; substitutes a single character..
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLikeToolTip {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLikeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t equal.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterNotEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandCancel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandClearFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandDelete {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandEdit {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandNew {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandSelect {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandUpdate {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete?.
        /// </summary>
        internal static string ASPxGridViewStringId_ConfirmDelete {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Chooser.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationWindowCaption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        internal static string ASPxGridViewStringId_EmptyDataRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.EmptyDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column here....
        /// </summary>
        internal static string ASPxGridViewStringId_EmptyHeaders {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.EmptyHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Continued on the next page).
        /// </summary>
        internal static string ASPxGridViewStringId_GroupContinuedOnNextPage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.GroupContinuedOnNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header here to group by that column.
        /// </summary>
        internal static string ASPxGridViewStringId_GroupPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.GroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterCancelButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterOkButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select All).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterSelectAll {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowAllItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowAllItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blanks).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowBlanksItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowBlanksItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Non blanks).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowNonBlanksItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowNonBlanksItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond Next Month.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_BeyondNextMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_BeyondNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier this Month.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_EarlierThisMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_EarlierThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_LastMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_LastWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later this Month.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_LaterThisMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_LaterThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_NextMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_NextWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Older {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Weeks Ago.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_ThreeWeeksAgo {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_ThreeWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Weeks Away.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_ThreeWeeksAway {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_ThreeWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Today {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Tomorrow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Weeks Ago.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_TwoWeeksAgo {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_TwoWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Weeks Away.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_TwoWeeksAway {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_TwoWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Yesterday {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Form.
        /// </summary>
        internal static string ASPxGridViewStringId_PopupEditFormCaption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.PopupEditFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg={0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Average {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg of {1} is {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Average_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Average_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count={0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Count {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max={0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Max {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max of {1} is {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Max_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Max_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min={0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Min {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min of {1} is {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Min_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Min_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum={0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Sum {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of {1} is {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Sum_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Sum_OtherColumn", resourceCulture);
            }
        }
    }
}
