//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Договір Оренди.
        /// </summary>
        internal static string ArendaCardTitle {
            get {
                return ResourceManager.GetString("ArendaCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Архівний Стан Договору Оренди.
        /// </summary>
        internal static string ArendaCardTitleArch {
            get {
                return ResourceManager.GetString("ArendaCardTitleArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Об&apos;єкт На Балансі.
        /// </summary>
        internal static string BalansCardTitle {
            get {
                return ResourceManager.GetString("BalansCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Архівний Стан Об&apos;єкту На Балансі.
        /// </summary>
        internal static string BalansCardTitleArch {
            get {
                return ResourceManager.GetString("BalansCardTitleArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Створено новий Додаток: {0}.
        /// </summary>
        internal static string BPRishProjectAddAppendix {
            get {
                return ResourceManager.GetString("BPRishProjectAddAppendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Додано новий рядок до Додатку {0}.
        /// </summary>
        internal static string BPRishProjectAddAppItem {
            get {
                return ResourceManager.GetString("BPRishProjectAddAppItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Текст рядка: {0}.
        /// </summary>
        internal static string BPRishProjectAddAppItemText {
            get {
                return ResourceManager.GetString("BPRishProjectAddAppItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Додано нову колонку &apos;{0}&apos; в таблицю Додатку {1}.
        /// </summary>
        internal static string BPRishProjectAddColumn {
            get {
                return ResourceManager.GetString("BPRishProjectAddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как &apos;{0}&apos; на &apos;{1}&apos;.
        /// </summary>
        internal static string BPRishProjectAnyChange {
            get {
                return ResourceManager.GetString("BPRishProjectAnyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Об&apos;єкт.
        /// </summary>
        internal static string BPRishProjectAppendixObject {
            get {
                return ResourceManager.GetString("BPRishProjectAppendixObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как № п/п.
        /// </summary>
        internal static string BPRishProjectAppendixObjIndex {
            get {
                return ResourceManager.GetString("BPRishProjectAppendixObjIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Додаток {0}.
        /// </summary>
        internal static string BPRishProjectAppendixTitleSimple {
            get {
                return ResourceManager.GetString("BPRishProjectAppendixTitleSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Додаток {0}: {1}.
        /// </summary>
        internal static string BPRishProjectAppendixTitleWithNote {
            get {
                return ResourceManager.GetString("BPRishProjectAppendixTitleWithNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Змінено рядкок в Додатку {0}.
        /// </summary>
        internal static string BPRishProjectChangeAppItem {
            get {
                return ResourceManager.GetString("BPRishProjectChangeAppItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Змінено {0}.
        /// </summary>
        internal static string BPRishProjectChangeRecord {
            get {
                return ResourceManager.GetString("BPRishProjectChangeRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как дату Рішення на &apos;{0}&apos;.
        /// </summary>
        internal static string BPRishProjectDateChange {
            get {
                return ResourceManager.GetString("BPRishProjectDateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Видалено Додаток {0}.
        /// </summary>
        internal static string BPRishProjectDelAppendix {
            get {
                return ResourceManager.GetString("BPRishProjectDelAppendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Видалено рядок з Додатку {0}.
        /// </summary>
        internal static string BPRishProjectDelAppItem {
            get {
                return ResourceManager.GetString("BPRishProjectDelAppItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Видалено колонку &apos;{0}&apos; з таблиці Додатку {1}.
        /// </summary>
        internal static string BPRishProjectDelColumn {
            get {
                return ResourceManager.GetString("BPRishProjectDelColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Змінено текст вводної частини Рішення на: {0}.
        /// </summary>
        internal static string BPRishProjectIntroChange {
            get {
                return ResourceManager.GetString("BPRishProjectIntroChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как назву Рішення на &apos;{0}&apos;.
        /// </summary>
        internal static string BPRishProjectNameChange {
            get {
                return ResourceManager.GetString("BPRishProjectNameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как номер Рішення на &apos;{0}&apos;.
        /// </summary>
        internal static string BPRishProjectNumChange {
            get {
                return ResourceManager.GetString("BPRishProjectNumChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Змінено текст заключної частини Рішення на: {0}.
        /// </summary>
        internal static string BPRishProjectOutroChange {
            get {
                return ResourceManager.GetString("BPRishProjectOutroChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Попереднє значення: {0}.
        /// </summary>
        internal static string BPRishProjectPrevValue {
            get {
                return ResourceManager.GetString("BPRishProjectPrevValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Змінено текст пункту Рішення на: {0}.
        /// </summary>
        internal static string BPRishProjectPunktChange {
            get {
                return ResourceManager.GetString("BPRishProjectPunktChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Видалено пункт Рішення: {0}.
        /// </summary>
        internal static string BPRishProjectPunktDeleted {
            get {
                return ResourceManager.GetString("BPRishProjectPunktDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как стан на &apos;{0}&apos;.
        /// </summary>
        internal static string BPRishProjectStateChange {
            get {
                return ResourceManager.GetString("BPRishProjectStateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как картка.
        /// </summary>
        internal static string CardColumnTitle {
            get {
                return ResourceManager.GetString("CardColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Середня чисельність працюючих.
        /// </summary>
        internal static string ComparableFieldAvgNumWorkers {
            get {
                return ResourceManager.GetString("ComparableFieldAvgNumWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Середня заробітна плата.
        /// </summary>
        internal static string ComparableFieldAvgSalary {
            get {
                return ResourceManager.GetString("ComparableFieldAvgSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вартість активів.
        /// </summary>
        internal static string ComparableFieldCostAct {
            get {
                return ResourceManager.GetString("ComparableFieldCostAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поточні зобов&apos;язання.
        /// </summary>
        internal static string ComparableFieldCurZobov {
            get {
                return ResourceManager.GetString("ComparableFieldCurZobov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Дебіторська заборгованість.
        /// </summary>
        internal static string ComparableFieldDebitDebt {
            get {
                return ResourceManager.GetString("ComparableFieldDebitDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Кредиторська заборгованість.
        /// </summary>
        internal static string ComparableFieldDebtCredit {
            get {
                return ResourceManager.GetString("ComparableFieldDebtCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Чистий прибуток/збиток.
        /// </summary>
        internal static string ComparableFieldIncome {
            get {
                return ResourceManager.GetString("ComparableFieldIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Довгострокові кредити банків.
        /// </summary>
        internal static string ComparableFieldLongBankCredit {
            get {
                return ResourceManager.GetString("ComparableFieldLongBankCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Довгострокова дебіторська заборгованість.
        /// </summary>
        internal static string ComparableFieldLongDebitDebt {
            get {
                return ResourceManager.GetString("ComparableFieldLongDebitDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Довгострокові зобов&apos;язання.
        /// </summary>
        internal static string ComparableFieldLongZobov {
            get {
                return ResourceManager.GetString("ComparableFieldLongZobov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Прибуток-збиток фактичний.
        /// </summary>
        internal static string ComparableFieldPributokFact {
            get {
                return ResourceManager.GetString("ComparableFieldPributokFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Короткострокові кредити банків.
        /// </summary>
        internal static string ComparableFieldShortBankCredit {
            get {
                return ResourceManager.GetString("ComparableFieldShortBankCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Сукупні доходи (без ПДВ).
        /// </summary>
        internal static string ComparableFieldTotalNoPDV {
            get {
                return ResourceManager.GetString("ComparableFieldTotalNoPDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Сума відрахувань частки прибутку до бюджету.
        /// </summary>
        internal static string ComparableFieldVidrahuvannia {
            get {
                return ResourceManager.GetString("ComparableFieldVidrahuvannia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Загальний обсяг доходів.
        /// </summary>
        internal static string ComparableFieldZagalDohod {
            get {
                return ResourceManager.GetString("ComparableFieldZagalDohod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Динаміка: &apos;{0}&apos; та &apos;{1}&apos;.
        /// </summary>
        internal static string CompFieldColumn {
            get {
                return ResourceManager.GetString("CompFieldColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как _вiд_.
        /// </summary>
        internal static string DocDownloadTitleDate {
            get {
                return ResourceManager.GetString("DocDownloadTitleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Документ.
        /// </summary>
        internal static string DocDownloadTitleSimple {
            get {
                return ResourceManager.GetString("DocDownloadTitleSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Документ_№_.
        /// </summary>
        internal static string DocDownloadTitleWithNum {
            get {
                return ResourceManager.GetString("DocDownloadTitleWithNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как {0} (Форма &quot;{1}&quot;).
        /// </summary>
        internal static string FinFormTitle {
            get {
                return ResourceManager.GetString("FinFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как {0} (Форма &quot;{1}&quot; {2}).
        /// </summary>
        internal static string FinFormTitleWithType {
            get {
                return ResourceManager.GetString("FinFormTitleWithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Обробку завершено..
        /// </summary>
        internal static string FinishedProcessing {
            get {
                return ResourceManager.GetString("FinishedProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как НОРМАТИВ ВІДРАХУВАН.
        /// </summary>
        internal static string FinNormativVidrahuvannia {
            get {
                return ResourceManager.GetString("FinNormativVidrahuvannia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как http://185.151.105.59/gukv.
        /// </summary>
        internal static string GlobalWebSiteURL {
            get {
                return ResourceManager.GetString("GlobalWebSiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Звіт згенеровано {0:g} з наступними показниками: {1}.
        /// </summary>
        internal static string GridFilterExportPrefixFiltered {
            get {
                return ResourceManager.GetString("GridFilterExportPrefixFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Звіт згенеровано {0:g}.
        /// </summary>
        internal static string GridFilterExportPrefixSimple {
            get {
                return ResourceManager.GetString("GridFilterExportPrefixSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вставити адресу....
        /// </summary>
        internal static string HtmlEditorInsertAddr {
            get {
                return ResourceManager.GetString("HtmlEditorInsertAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вставити назву об&apos;єкту....
        /// </summary>
        internal static string HtmlEditorInsertObject {
            get {
                return ResourceManager.GetString("HtmlEditorInsertObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вставити назву організації, від якої передається об&apos;єкт.
        /// </summary>
        internal static string HtmlEditorInsertOrgFrom {
            get {
                return ResourceManager.GetString("HtmlEditorInsertOrgFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вставити назву організації, до якої передається об&apos;єкт.
        /// </summary>
        internal static string HtmlEditorInsertOrgTo {
            get {
                return ResourceManager.GetString("HtmlEditorInsertOrgTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как К.
        /// </summary>
        internal static string KorpusPrefixCheck {
            get {
                return ResourceManager.GetString("KorpusPrefixCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как К..
        /// </summary>
        internal static string KorpusPrefixCorrect {
            get {
                return ResourceManager.GetString("KorpusPrefixCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как січня.
        /// </summary>
        internal static string Month1 {
            get {
                return ResourceManager.GetString("Month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как жовтня.
        /// </summary>
        internal static string Month10 {
            get {
                return ResourceManager.GetString("Month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как листопада.
        /// </summary>
        internal static string Month11 {
            get {
                return ResourceManager.GetString("Month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как грудня.
        /// </summary>
        internal static string Month12 {
            get {
                return ResourceManager.GetString("Month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как лютого.
        /// </summary>
        internal static string Month2 {
            get {
                return ResourceManager.GetString("Month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как березня.
        /// </summary>
        internal static string Month3 {
            get {
                return ResourceManager.GetString("Month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как квітня.
        /// </summary>
        internal static string Month4 {
            get {
                return ResourceManager.GetString("Month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как травня.
        /// </summary>
        internal static string Month5 {
            get {
                return ResourceManager.GetString("Month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как червня.
        /// </summary>
        internal static string Month6 {
            get {
                return ResourceManager.GetString("Month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как липня.
        /// </summary>
        internal static string Month7 {
            get {
                return ResourceManager.GetString("Month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как серпня.
        /// </summary>
        internal static string Month8 {
            get {
                return ResourceManager.GetString("Month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как вересня.
        /// </summary>
        internal static string Month9 {
            get {
                return ResourceManager.GetString("Month9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как АБВГДЕЖ.
        /// </summary>
        internal static string ObjectGroups {
            get {
                return ResourceManager.GetString("ObjectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Аукціон.
        /// </summary>
        internal static string PrivatKindAuction {
            get {
                return ResourceManager.GetString("PrivatKindAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Викуп.
        /// </summary>
        internal static string PrivatKindSell {
            get {
                return ResourceManager.GetString("PrivatKindSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Будь ласка, не закривайте браузер, доки виконується надсилання усіх змінених договорів надання в оренду....
        /// </summary>
        internal static string ProcessingArendaObjects {
            get {
                return ResourceManager.GetString("ProcessingArendaObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Будь ласка, не закривайте браузер, доки виконується надсилання усіх змінених об&apos;єктів на балансі....
        /// </summary>
        internal static string ProcessingBalansObjects {
            get {
                return ResourceManager.GetString("ProcessingBalansObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Будь ласка, не закривайте браузер, доки виконується надсилання усіх змінених відчужених об&apos;єктів....
        /// </summary>
        internal static string ProcessingDeletedBalansObjects {
            get {
                return ResourceManager.GetString("ProcessingDeletedBalansObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Будь ласка, не закривайте браузер, доки виконується надсилання усіх змінених договорів орендування....
        /// </summary>
        internal static string ProcessingRentedObjects {
            get {
                return ResourceManager.GetString("ProcessingRentedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как район.
        /// </summary>
        internal static string RentAddressDistrict {
            get {
                return ResourceManager.GetString("RentAddressDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как  від .
        /// </summary>
        internal static string RentAgreementDate {
            get {
                return ResourceManager.GetString("RentAgreementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Орендодавець.
        /// </summary>
        internal static string RentAgreementGiver {
            get {
                return ResourceManager.GetString("RentAgreementGiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как № .
        /// </summary>
        internal static string RentAgreementNum {
            get {
                return ResourceManager.GetString("RentAgreementNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Керівник: .
        /// </summary>
        internal static string RenterDirector {
            get {
                return ResourceManager.GetString("RenterDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как від.
        /// </summary>
        internal static string RenterLetterDate {
            get {
                return ResourceManager.GetString("RenterLetterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как № .
        /// </summary>
        internal static string RenterLetterNum {
            get {
                return ResourceManager.GetString("RenterLetterNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как тел: .
        /// </summary>
        internal static string RenterPhone {
            get {
                return ResourceManager.GetString("RenterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как {0} за {1}.
        /// </summary>
        internal static string RentObjectsUseColumnFormat {
            get {
                return ResourceManager.GetString("RentObjectsUseColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Порівняння: &apos;{0}&apos; та &apos;{1}&apos;.
        /// </summary>
        internal static string RentObjectsUseCompColumnTitle {
            get {
                return ResourceManager.GetString("RentObjectsUseCompColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Заборгованість зі сплати 30% (50%) до бюджету попередніх періодів (грн.).
        /// </summary>
        internal static string RentObjectsUse_50_DebtPrev {
            get {
                return ResourceManager.GetString("RentObjectsUse_50_DebtPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Заборгованість зі сплати 50% до бюджету за звітний період (грн.).
        /// </summary>
        internal static string RentObjectsUse_50_DebtZvit {
            get {
                return ResourceManager.GetString("RentObjectsUse_50_DebtZvit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Нарахована сума до бюджету 50% (30%) (грн.).
        /// </summary>
        internal static string RentObjectsUse_50_Narah {
            get {
                return ResourceManager.GetString("RentObjectsUse_50_Narah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Перерахована до бюджету 50% (30%), враховуючи перераховану заборгованість за попередні періоди (грн.).
        /// </summary>
        internal static string RentObjectsUse_50_Payed {
            get {
                return ResourceManager.GetString("RentObjectsUse_50_Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Нараховано орендної плати за здачу нежитлової площі (грн.).
        /// </summary>
        internal static string RentObjectsUse_Narahovano {
            get {
                return ResourceManager.GetString("RentObjectsUse_Narahovano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Кількість Договорів Оренди.
        /// </summary>
        internal static string RentObjectsUse_NumAgreements {
            get {
                return ResourceManager.GetString("RentObjectsUse_NumAgreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Кількість Орендарів.
        /// </summary>
        internal static string RentObjectsUse_NumRenters {
            get {
                return ResourceManager.GetString("RentObjectsUse_NumRenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Отримано орендної плати за здачу нежитлової площі (грн.).
        /// </summary>
        internal static string RentObjectsUse_Otrymano {
            get {
                return ResourceManager.GetString("RentObjectsUse_Otrymano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Середній розмір орендної плати за 1 кв.м нежитлової площі (грн.).
        /// </summary>
        internal static string RentObjectsUse_RentAvg {
            get {
                return ResourceManager.GetString("RentObjectsUse_RentAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Заборгованість по орендній платі за здачу нежитлової площі (грн.).
        /// </summary>
        internal static string RentObjectsUse_RentDebt {
            get {
                return ResourceManager.GetString("RentObjectsUse_RentDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Нежитлова площа, всього (кв.м.).
        /// </summary>
        internal static string RentObjectsUse_SqrBalans {
            get {
                return ResourceManager.GetString("RentObjectsUse_SqrBalans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Здається в оренду, всього (кв.м.).
        /// </summary>
        internal static string RentObjectsUse_SqrRentTotal {
            get {
                return ResourceManager.GetString("RentObjectsUse_SqrRentTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Співробітник ДКВ {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Договір надання в оренду: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyDkvArenda {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyDkvArenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Співробітник ДКВ {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Договір надання в оренду: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyDkvArendaPayment {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyDkvArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Співробітник ДКВ {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Об&apos;єкт на балансі: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyDkvBalans {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyDkvBalans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Співробітник ДКВ {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Відчужений об&apos;єкт: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyDkvBalansDel {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyDkvBalansDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Співробітник ДКВ {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Сторінка звіту: Відомості про організацію
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyDkvOrg {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyDkvOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Співробітник ДКВ {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Сторінка звіту: Відомості про організацію (надходження від орендної плати)
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyDkvOrgArendaPayment {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyDkvOrgArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Співробітник ДКВ {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Договір орендування: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyDkvRented {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyDkvRented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Користувач {0} залишив коментар у звіті про використання комунальної власності.
        ///
        ///Організація: {1}
        ///
        ///Договір надання в оренду: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyOrgArenda {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyOrgArenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Користувач {0} залишив коментар у звіті про використання комунальної власності.
        ///
        ///Організація: {1}
        ///
        ///Договір надання в оренду: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyOrgArendaPayment {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyOrgArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Користувач {0} залишив коментар у звіті про використання комунальної власності.
        ///
        ///Організація: {1}
        ///
        ///Об&apos;єкт на балансі: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyOrgBalans {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyOrgBalans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Користувач {0} залишив коментар у звіті про використання комунальної власності.
        ///
        ///Організація: {1}
        ///
        ///Відчужений об&apos;єкт: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyOrgBalansDel {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyOrgBalansDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Користувач {0} залишив коментар у звіті про використання комунальної власності.
        ///
        ///Організація: {1}
        ///
        ///Сторінка звіту: Відомості про організацію
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyOrgOrg {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyOrgOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Користувач {0} залишив коментар у звіті про використання комунальної власності.
        ///
        ///Організація: {1}
        ///
        ///Сторінка звіту: Відомості про організацію (надходження від орендної плати)
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyOrgOrgArendaPayment {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyOrgOrgArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Користувач {0} залишив коментар у звіті про використання комунальної власності.
        ///
        ///Організація: {1}
        ///
        ///Договір орендування: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyOrgRented {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyOrgRented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Співробітник РДА {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Договір надання в оренду: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyRdaArenda {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyRdaArenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Співробітник РДА {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Договір надання в оренду: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyRdaArendaPayment {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyRdaArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Співробітник РДА {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Об&apos;єкт на балансі: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyRdaBalans {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyRdaBalans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Співробітник РДА {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Відчужений об&apos;єкт: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyRdaBalansDel {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyRdaBalansDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Співробітник РДА {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Сторінка звіту: Відомості про організацію
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyRdaOrg {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyRdaOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Співробітник РДА {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Сторінка звіту: Відомості про організацію (надходження від орендної плати)
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyRdaOrgArendaPayment {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyRdaOrgArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Співробітник РДА {0} залишив коментар у Вашому звіті про використання комунальної власності.
        ///
        ///Договір орендування: {2}
        ///
        ///Інформація, що коментується: {3}
        ///
        ///Коментар: {4}
        ///
        ///Перейти до звіту: {5}.
        /// </summary>
        internal static string Report1NFCommentBodyRdaRented {
            get {
                return ResourceManager.GetString("Report1NFCommentBodyRdaRented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника ДКВ щодо договору надання в оренду.
        /// </summary>
        internal static string Report1NFCommentSubjectDkvArenda {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectDkvArenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника ДКВ щодо орендної плати за договором орендування.
        /// </summary>
        internal static string Report1NFCommentSubjectDkvArendaPayment {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectDkvArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника ДКВ щодо об&apos;єкту на балансі.
        /// </summary>
        internal static string Report1NFCommentSubjectDkvBalans {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectDkvBalans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника ДКВ щодо відчуженого об&apos;єкту.
        /// </summary>
        internal static string Report1NFCommentSubjectDkvBalansDel {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectDkvBalansDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника ДКВ щодо відомостей про організацію.
        /// </summary>
        internal static string Report1NFCommentSubjectDkvOrg {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectDkvOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника ДКВ щодо відомостей про надходження від орендної плати.
        /// </summary>
        internal static string Report1NFCommentSubjectDkvOrgArendaPayment {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectDkvOrgArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника ДКВ щодо договору орендування.
        /// </summary>
        internal static string Report1NFCommentSubjectDkvRented {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectDkvRented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від балансоутримувача щодо договору надання в оренду.
        /// </summary>
        internal static string Report1NFCommentSubjectOrgArenda {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectOrgArenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від балансоутримувача щодо орендної плати за договором надання в оренду.
        /// </summary>
        internal static string Report1NFCommentSubjectOrgArendaPayment {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectOrgArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від балансоутримувача щодо об&apos;єкту на балансі.
        /// </summary>
        internal static string Report1NFCommentSubjectOrgBalans {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectOrgBalans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від балансоутримувача щодо відчуженого об&apos;єкту.
        /// </summary>
        internal static string Report1NFCommentSubjectOrgBalansDel {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectOrgBalansDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від балансоутримувача щодо відомостей про організацію.
        /// </summary>
        internal static string Report1NFCommentSubjectOrgOrg {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectOrgOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від балансоутримувача щодо відомостей про надходження від орендної плати.
        /// </summary>
        internal static string Report1NFCommentSubjectOrgOrgArendaPayment {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectOrgOrgArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від балансоутримувача щодо договору орендування.
        /// </summary>
        internal static string Report1NFCommentSubjectOrgRented {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectOrgRented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника РДА щодо договору надання в оренду.
        /// </summary>
        internal static string Report1NFCommentSubjectRdaArenda {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectRdaArenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника РДА щодо орендної плати за договором надання в оренду.
        /// </summary>
        internal static string Report1NFCommentSubjectRdaArendaPayment {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectRdaArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника РДА щодо об&apos;єкту на балансі.
        /// </summary>
        internal static string Report1NFCommentSubjectRdaBalans {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectRdaBalans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника РДА щодо відчуженого об&apos;єкту.
        /// </summary>
        internal static string Report1NFCommentSubjectRdaBalansDel {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectRdaBalansDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника РДА щодо відомостей про організацію.
        /// </summary>
        internal static string Report1NFCommentSubjectRdaOrg {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectRdaOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника РДА щодо відомостей про надходження від орендної плати.
        /// </summary>
        internal static string Report1NFCommentSubjectRdaOrgArendaPayment {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectRdaOrgArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Новий коментар від співробітника РДА щодо договору орендування.
        /// </summary>
        internal static string Report1NFCommentSubjectRdaRented {
            get {
                return ResourceManager.GetString("Report1NFCommentSubjectRdaRented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Вітаємо, {0}.
        ///
        ///Адреса веб-сайту ДКВ, який Ви можете використовувати для звітування з використання комунальної власності: {1}
        ///
        ///Ваш обліковий запис (ім&apos;я користувача) для входу на веб-сайт ДКВ: {2}
        ///Ваш пароль для входу на веб-сайт ДКВ: {3}
        ///.
        /// </summary>
        internal static string Report1NFNewPasswordBody {
            get {
                return ResourceManager.GetString("Report1NFNewPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Реєстрація на веб-сайті ДКВ для подання звітності щодо використання комунальної власності.
        /// </summary>
        internal static string Report1NFNewPasswordTitle {
            get {
                return ResourceManager.GetString("Report1NFNewPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 
        ///Вітаємо, {0}.
        ///
        ///Адреса веб-сайту ДКВ, який Ви можете використовувати для перегляду та контролю звітності балансоутримувачів з використання комунальної власності: {1}
        ///
        ///Ваш обліковий запис (ім&apos;я користувача) для входу на веб-сайт ДКВ: {2}
        ///Ваш пароль для входу на веб-сайт ДКВ: {3}.
        /// </summary>
        internal static string Report1NFRdaNewPasswordBody {
            get {
                return ResourceManager.GetString("Report1NFRdaNewPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Реєстрація на веб-сайті ДКВ для контролю звітності балансоутримувачів щодо використання комунальної власності.
        /// </summary>
        internal static string Report1NFRdaNewPasswordTitle {
            get {
                return ResourceManager.GetString("Report1NFRdaNewPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Дата підготовки звіту: {0:g}.
        /// </summary>
        internal static string ReportDateFormat {
            get {
                return ResourceManager.GetString("ReportDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Звіт згенеровано з наступними показниками: {0}.
        /// </summary>
        internal static string ReportFilterFormat {
            get {
                return ResourceManager.GetString("ReportFilterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как ЗВІТ НЕ НАДІСЛАНО ДО ДКВ.
        /// </summary>
        internal static string ReportNotSubmitted {
            get {
                return ResourceManager.GetString("ReportNotSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как № {0} від {1}.
        /// </summary>
        internal static string Reports1NFRentedFormat {
            get {
                return ResourceManager.GetString("Reports1NFRentedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как № {0} від {1}, орендар: {2}.
        /// </summary>
        internal static string Reports1NFRentFormat {
            get {
                return ResourceManager.GetString("Reports1NFRentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как м. Київ.
        /// </summary>
        internal static string RishenCityName {
            get {
                return ResourceManager.GetString("RishenCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как від .
        /// </summary>
        internal static string RishennyaDate {
            get {
                return ResourceManager.GetString("RishennyaDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как дод. .
        /// </summary>
        internal static string RishennyaDodatok {
            get {
                return ResourceManager.GetString("RishennyaDodatok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Рішення № .
        /// </summary>
        internal static string RishennyaNum {
            get {
                return ResourceManager.GetString("RishennyaNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как п. .
        /// </summary>
        internal static string RishennyaPunkt {
            get {
                return ResourceManager.GetString("RishennyaPunkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Поверх.
        /// </summary>
        internal static string RishenPoverh {
            get {
                return ResourceManager.GetString("RishenPoverh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как вул..
        /// </summary>
        internal static string RishenStreet {
            get {
                return ResourceManager.GetString("RishenStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Додаток {0}.
        /// </summary>
        internal static string RishProjDodatok {
            get {
                return ResourceManager.GetString("RishProjDodatok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как до рішення Київради.
        /// </summary>
        internal static string RishProjDoRishennya {
            get {
                return ResourceManager.GetString("RishProjDoRishennya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как від &quot;{0}&quot; {1} {2}    № {3}.
        /// </summary>
        internal static string RishProjDoRishennyaN {
            get {
                return ResourceManager.GetString("RishProjDoRishennyaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как КИЇВСЬКА МІСЬКА РАДА.
        /// </summary>
        internal static string RishProjRADA {
            get {
                return ResourceManager.GetString("RishProjRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как РІШЕННЯ.
        /// </summary>
        internal static string RishProjRishennya {
            get {
                return ResourceManager.GetString("RishProjRishennya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как  № .
        /// </summary>
        internal static string RishProjRishNum {
            get {
                return ResourceManager.GetString("RishProjRishNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Х СЕСІЯ VІ СКЛИКАННЯ.
        /// </summary>
        internal static string RishProjSessiya {
            get {
                return ResourceManager.GetString("RishProjSessiya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Дані внесено користувачем {0}, дата внесення змін: {1}.
        /// </summary>
        internal static string SignatureObjCard {
            get {
                return ResourceManager.GetString("SignatureObjCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как НЕМА ДАНИХ.
        /// </summary>
        internal static string SignatureUnknownDate {
            get {
                return ResourceManager.GetString("SignatureUnknownDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как НЕВІДОМИЙ.
        /// </summary>
        internal static string SignatureUnknownUser {
            get {
                return ResourceManager.GetString("SignatureUnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как SELECT arenda_id, building_id, balans_id, org_renter_id, org_renter_full_name, org_renter_zkpo, org_giver_id, org_giver_full_name, org_giver_zkpo, object_name, agreement_kind, agreement_date, agreement_num, rent_start_date, rent_finish_date, rent_actual_finish_date, agreement_active, rent_square FROM view_arenda WHERE balans_id = @bid AND agreement_active_int = 1.
        /// </summary>
        internal static string SqlObjCardArendaFromBalans {
            get {
                return ResourceManager.GetString("SqlObjCardArendaFromBalans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как SELECT arenda_id, building_id, balans_id, org_renter_id, org_renter_full_name, org_renter_zkpo, org_giver_id, org_giver_full_name, org_giver_zkpo, object_name, agreement_kind, agreement_date, agreement_num, rent_start_date, rent_finish_date, rent_actual_finish_date, agreement_active, rent_square FROM view_arenda WHERE building_id = @bid AND agreement_active_int = 1.
        /// </summary>
        internal static string SqlObjCardArendaFromBuildings {
            get {
                return ResourceManager.GetString("SqlObjCardArendaFromBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как SELECT arenda_id, building_id, balans_id, org_renter_id, org_renter_full_name, org_renter_zkpo, org_giver_id, org_giver_full_name, org_giver_zkpo, object_name, agreement_kind, agreement_date, agreement_num, rent_start_date, rent_finish_date, rent_actual_finish_date, agreement_active, rent_square FROM view_arenda_privat_docs WHERE balans_id = @bid.
        /// </summary>
        internal static string SqlObjCardPurchaseFromBalans {
            get {
                return ResourceManager.GetString("SqlObjCardPurchaseFromBalans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как SELECT arenda_id, building_id, balans_id, org_renter_id, org_renter_full_name, org_renter_zkpo, org_giver_id, org_giver_full_name, org_giver_zkpo, object_name, agreement_kind, agreement_date, agreement_num, rent_start_date, rent_finish_date, rent_actual_finish_date, agreement_active, rent_square FROM view_arenda_privat_docs WHERE building_id = @bid.
        /// </summary>
        internal static string SqlObjCardPurchaseFromBuildings {
            get {
                return ResourceManager.GetString("SqlObjCardPurchaseFromBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как SELECT district, street_full_name, addr_nomer, floors, form_ownership, object_kind, object_type, condition, purpose_group, purpose, history, cost_balans, sqr_total, sqr_non_habit, num_floors, obj_bti_code, addr_zip_code, construct_year, oatuu_code, facade, note, org_full_name, org_zkpo_code, org_industry, org_occupation, sqr_pidval, sqr_vlas_potreb, sqr_free, sqr_in_rent, sqr_privatizov, sqr_not_for_rent, sqr_gurtoj, cost_expert_1m, cost_expert_total, cost_zalishkova, o26_code, bti_condition, org_maintainer [остаток строки был усечен]&quot;;.
        /// </summary>
        internal static string SqlObjCardSelectFromBalans {
            get {
                return ResourceManager.GetString("SqlObjCardSelectFromBalans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как SELECT district, street_full_name, addr_nomer, NULL as &apos;floors&apos;, NULL as &apos;form_ownership&apos;, object_kind, object_type, condition, NULL as &apos;purpose_group&apos;, NULL as &apos;purpose&apos;, history, cost_balans, sqr_total, sqr_non_habit, num_floors, bti_code as &apos;obj_bti_code&apos;, addr_zip_code, construct_year, oatuu_code, facade, additional_info as &apos;note&apos;, NULL as &apos;org_full_name&apos;, NULL as &apos;org_zkpo_code&apos;, NULL as &apos;org_industry&apos;, NULL as &apos;org_occupation&apos;, sqr_pidval, NULL as &apos;sqr_vlas_potreb&apos;, NULL as &apos;sqr_free&apos;, sqr_rented as &apos; [остаток строки был усечен]&quot;;.
        /// </summary>
        internal static string SqlObjCardSelectFromBuildings {
            get {
                return ResourceManager.GetString("SqlObjCardSelectFromBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как SELECT transfer_id, building_id, district, street_full_name, addr_nomer, condition, object_type, object_kind, purpose_group, purpose, org_from_id, org_from_full_name, org_from_short_name, org_from_zkpo_code, org_from_industry, org_from_occupation, org_from_ownership, org_from_form_gosp, org_to_id, org_to_full_name, org_to_short_name, org_to_zkpo_code, org_to_industry, org_to_occupation, org_to_ownership, org_to_form_gosp, right_name, transfer_date, transfer_year, transfer_quarter, akt_id, akt_num, akt_date, [остаток строки был усечен]&quot;;.
        /// </summary>
        internal static string SqlObjTransfer {
            get {
                return ResourceManager.GetString("SqlObjTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Перерахування коштiв.
        /// </summary>
        internal static string VipiskiWorksheetTitle {
            get {
                return ResourceManager.GetString("VipiskiWorksheetTitle", resourceCulture);
            }
        }
    }
}
