CREATE TABLE [dbo].[__property_info] (
    [full_name]                  VARCHAR (2000) NULL,
    [zkpo_code]                  BIGINT         NULL,
    [cur_state]                  VARCHAR (2000) NULL,
    [max_submit_date]            DATETIME       NULL,
    [stan_recieve_id]            VARCHAR (2000) NULL,
    [stan_recieve_description]   VARCHAR (2000) NULL,
    [prim_balanc]                VARCHAR (2000) NULL,
    [stan_recieve_date]          DATETIME       NULL,
    [inventar_recieve_date]      DATETIME       NULL,
    [dict_rent_occupation_name]  VARCHAR (2000) NULL,
    [addr_district]              VARCHAR (2000) NULL,
    [addr_street_name]           VARCHAR (2000) NULL,
    [addr_nomer]                 VARCHAR (100)  NULL,
    [occupation]                 VARCHAR (2000) NULL,
    [form_gosp]                  VARCHAR (2000) NULL,
    [form_of_ownership]          VARCHAR (2000) NULL,
    [gosp_struct]                VARCHAR (100)  NULL,
    [org_form]                   VARCHAR (2000) NULL,
    [old_organ]                  VARCHAR (2000) NULL,
    [registration_svidot]        VARCHAR (2000) NULL,
    [kved_code]                  VARCHAR (100)  NULL,
    [otdel_gukv]                 VARCHAR (100)  NULL,
    [NumOfObj]                   BIGINT         NULL,
    [ORG_CONTRIB_RATE]           BIGINT         NULL,
    [SQR_TOTAL_BAL]              BIGINT         NULL,
    [SQR_KOR]                    BIGINT         NULL,
    [SQR_VLAS_POTREB]            BIGINT         NULL,
    [SQR_VLAS_POTREB_COUNT]      BIGINT         NULL,
    [SQR_RENTED]                 BIGINT         NULL,
    [SQR_GIVEN]                  BIGINT         NULL,
    [NUM_GIVEN]                  BIGINT         NULL,
    [NUM_RENTER]                 BIGINT         NULL,
    [NUM_RENTED]                 BIGINT         NULL,
    [SQR_FREE]                   BIGINT         NULL,
    [SQR_FREE_COUNT]             BIGINT         NULL,
    [PAY_NARAH_ZVIT]             BIGINT         NULL,
    [PAY_ZNYATO_NADMIRNO_NARAH]  BIGINT         NULL,
    [PAY_PEREPLATA]              BIGINT         NULL,
    [PAY_ZABEZDEPOZ_PRISHLO]     BIGINT         NULL,
    [PAY_RECV_ZVIT_new]          BIGINT         NULL,
    [PAY_RECV_NARAH]             BIGINT         NULL,
    [PAY_LAST_PER]               BIGINT         NULL,
    [PAY_RETURN_OREND_PAYED]     BIGINT         NULL,
    [PAY_PEREPLATA_ALL]          BIGINT         NULL,
    [PAY_RETURN_ALL_OREND_PAYED] BIGINT         NULL,
    [PAY_NARAH_ZVIT_NORMAL]      BIGINT         NULL,
    [PAY_AVANCE_DEBT]            BIGINT         NULL,
    [PAY_RECV_OTHER]             BIGINT         NULL,
    [PAY_DEBT_TOTAL]             BIGINT         NULL,
    [PAY_DEBT_ZVIT]              BIGINT         NULL,
    [PAY_DEBT_V_MEZH]            BIGINT         NULL,
    [PAY_50_NARAH]               BIGINT         NULL,
    [PAY_UNKNOWN_PAYMENTS]       BIGINT         NULL,
    [PAY_50_PAYED]               BIGINT         NULL,
    [PAY_50_DEBT]                BIGINT         NULL,
    [PAY_50_DEBT_CUR]            BIGINT         NULL,
    [PAY_50_DEBT_OLD]            BIGINT         NULL,
    [PAY_SPECIAL]                BIGINT         NULL,
    [planuvania_1]               BIGINT         NULL,
    [planuvania_2]               BIGINT         NULL,
    [planuvania_3]               BIGINT         NULL,
    [planuvania_4]               BIGINT         NULL,
    [planuvania_5]               BIGINT         NULL,
    [ts_]                        DATETIME       NULL
);

