CREATE TABLE [dbo].[adresesUrbio_address] (
    [address_id]                      UNIQUEIDENTIFIER NOT NULL,
    [fullName]                        VARCHAR (1000)   NULL,
    [shortName]                       VARCHAR (1000)   NULL,
    [fullToponym]                     VARCHAR (1000)   NULL,
    [shortToponym]                    VARCHAR (1000)   NULL,
    [isToponymBeforeName]             BIT              NOT NULL,
    [secondLevel_fullName]            VARCHAR (1000)   NULL,
    [secondLevel_shortName]           VARCHAR (1000)   NULL,
    [secondLevel_fullToponym]         VARCHAR (1000)   NULL,
    [secondLevel_shortToponym]        VARCHAR (1000)   NULL,
    [secondLevel_isToponymBeforeName] BIT              NOT NULL,
    [thirdLevel_fullName]             VARCHAR (1000)   NULL,
    [thirdLevel_shortName]            VARCHAR (1000)   NULL,
    [thirdLevel_fullToponym]          VARCHAR (1000)   NULL,
    [thirdLevel_shortToponym]         VARCHAR (1000)   NULL,
    [thirdLevel_isToponymBeforeName]  BIT              NOT NULL,
    [category_fullText]               VARCHAR (1000)   NULL,
    [category_shortText]              VARCHAR (1000)   NULL,
    [zip]                             VARCHAR (1000)   NULL,
    [street_id]                       UNIQUEIDENTIFIER NULL,
    [street_fullName]                 VARCHAR (1000)   NULL,
    [street_shortName]                VARCHAR (1000)   NULL,
    [street_fullToponym]              VARCHAR (1000)   NULL,
    [street_shortToponym]             VARCHAR (1000)   NULL,
    [street_isToponymBeforeName]      BIT              NOT NULL,
    [district_id]                     UNIQUEIDENTIFIER NULL,
    [district_fullName]               VARCHAR (1000)   NULL,
    [district_shortName]              VARCHAR (1000)   NULL,
    [district_fullToponym]            VARCHAR (1000)   NULL,
    [district_shortToponym]           VARCHAR (1000)   NULL,
    [district_isToponymBeforeName]    BIT              NOT NULL,
    [asString]                        VARCHAR (1000)   NULL,
    [locale]                          VARCHAR (1000)   NULL,
    PRIMARY KEY CLUSTERED ([address_id] ASC)
);

