CREATE TABLE [dbo].[arch_balans] (
    [id]                     INT             NOT NULL,
    [year_balans]            INT             NULL,
    [building_id]            INT             NULL,
    [organization_id]        INT             NULL,
    [sqr_total]              NUMERIC (9, 2)  NULL,
    [sqr_pidval]             NUMERIC (9, 2)  NULL,
    [sqr_vlas_potreb]        NUMERIC (9, 2)  NULL,
    [sqr_free]               NUMERIC (9, 2)  NULL,
    [sqr_in_rent]            NUMERIC (9, 2)  NULL,
    [sqr_privatizov]         NUMERIC (9, 2)  NULL,
    [sqr_not_for_rent]       NUMERIC (9, 2)  NULL,
    [sqr_gurtoj]             NUMERIC (9, 2)  NULL,
    [sqr_non_habit]          NUMERIC (9, 2)  NULL,
    [sqr_kor]                NUMERIC (9, 2)  NULL,
    [cost_balans]            NUMERIC (15, 3) NULL,
    [cost_fair]              NUMERIC (15, 3) NULL,
    [cost_expert_1m]         NUMERIC (15, 3) NULL,
    [cost_expert_total]      NUMERIC (15, 3) NULL,
    [cost_rent_narah]        NUMERIC (15, 3) NULL,
    [cost_rent_payed]        NUMERIC (15, 3) NULL,
    [cost_debt]              NUMERIC (15, 3) NULL,
    [cost_zalishkova]        NUMERIC (15, 3) NULL,
    [cost_rinkova]           NUMERIC (15, 3) NULL,
    [cost_fair_1m]           NUMERIC (15, 3) NULL,
    [num_people]             INT             NULL,
    [num_rent_agr]           INT             NULL,
    [num_privat_apt]         INT             NULL,
    [o26_id]                 INT             NULL,
    [bti_id]                 VARCHAR (1000)  NULL,
    [approval_by]            VARCHAR (100)   NULL,
    [approval_num]           VARCHAR (18)    NULL,
    [approval_date]          DATE            NULL,
    [form_ownership_id]      INT             NULL,
    [object_kind_id]         INT             NULL,
    [object_type_id]         INT             NULL,
    [history_id]             INT             NULL,
    [tech_condition_id]      INT             NULL,
    [purpose_group_id]       INT             NULL,
    [purpose_id]             INT             NULL,
    [purpose_str]            VARCHAR (255)   NULL,
    [floors]                 VARCHAR (100)   NULL,
    [priznak_1nf]            INT             NULL,
    [ownership_type_id]      INT             NULL,
    [obj_street_name]        VARCHAR (100)   NULL,
    [obj_street_id]          INT             NULL,
    [obj_street_name2]       VARCHAR (100)   NULL,
    [obj_street_id2]         INT             NULL,
    [obj_nomer1]             VARCHAR (10)    NULL,
    [obj_nomer2]             VARCHAR (18)    NULL,
    [obj_nomer3]             VARCHAR (10)    NULL,
    [obj_nomer]              VARCHAR (40)    NULL,
    [obj_bti_code]           VARCHAR (1000)  NULL,
    [obj_addr_misc]          VARCHAR (100)   NULL,
    [obj_street_misc]        VARCHAR (255)   NULL,
    [modified_by]            VARCHAR (128)   NULL,
    [modify_date]            DATETIME        NULL,
    [form_giver_id]          INT             NULL,
    [org_maintain_id]        INT             NULL,
    [update_src_id]          INT             NULL,
    [is_deleted]             INT             NULL,
    [del_date]               DATE            NULL,
    [znos]                   NUMERIC (15, 3) NULL,
    [znos_date]              DATE            NULL,
    [date_expert]            DATE            NULL,
    [reestr_no]              VARCHAR (100)   NULL,
    [fair_cost_date]         DATE            NULL,
    [otdel_gukv_id]          INT             NULL,
    [date_bti]               DATE            NULL,
    [arch_id]                INT             NULL,
    [arch_flag]              INT             NULL,
    [date_cost_rinkova]      DATE            NULL,
    [memo]                   VARCHAR (MAX)   NULL,
    [note]                   VARCHAR (MAX)   NULL,
    [is_free_sqr]            INT             NULL,
    [free_sqr_useful]        NUMERIC (9, 2)  NULL,
    [free_sqr_condition_id]  VARCHAR (1000)  NULL,
    [free_sqr_location]      VARCHAR (100)   NULL,
    [ownership_doc_type]     INT             NULL,
    [ownership_doc_num]      VARCHAR (24)    NULL,
    [ownership_doc_date]     DATETIME        NULL,
    [balans_doc_type]        INT             NULL,
    [balans_doc_num]         VARCHAR (24)    NULL,
    [balans_doc_date]        DATETIME        NULL,
    [vidch_doc_type]         INT             NULL,
    [vidch_doc_num]          VARCHAR (24)    NULL,
    [vidch_doc_date]         DATETIME        NULL,
    [vidch_type_id]          INT             NULL,
    [vidch_org_id]           INT             NULL,
    [vidch_cost]             NUMERIC (15, 3) NULL,
    [sqr_engineering]        NUMERIC (9, 2)  NULL,
    [obj_status_id]          INT             NULL,
    [archive_id]             INT             IDENTITY (1, 1) NOT NULL,
    [archive_create_date]    DATE            NULL,
    [archive_create_user]    VARCHAR (256)   NULL,
    [archive_link_code]      INT             NOT NULL,
    [archive_link_code_prev] INT             NULL,
    [archive_link_code_next] INT             NULL,
    [rent_period_id]         INT             NULL,
    [report_id]              INT             NULL,
    [geodata_map_opoints]    VARCHAR (8000)  NULL,
    [znizhino_flag]          BIT             DEFAULT ((0)) NOT NULL,
    [znizhino_percent]       NUMERIC (15, 3) NULL,
    [znizhino_stanom]        DATE            NULL,
    [znizhino_shkoda]        BIT             DEFAULT ((0)) NOT NULL,
    [znizhino_zvitakt]       BIT             DEFAULT ((0)) NOT NULL,
    [znizhino_primitka]      VARCHAR (4000)  NULL,
    CONSTRAINT [PK__arch_bal__822B0C7233A42494] PRIMARY KEY CLUSTERED ([archive_id] ASC)
);

