CREATE TABLE [dbo].[arch_arenda_rented] (
    [building_id]             INT             NULL,
    [org_renter_id]           INT             NULL,
    [org_giver_id]            INT             NULL,
    [payment_type_id]         INT             NULL,
    [agreement_date]          DATE            NULL,
    [agreement_num]           VARCHAR (18)    NULL,
    [rent_start_date]         DATE            NULL,
    [rent_finish_date]        DATE            NULL,
    [rent_square]             NUMERIC (9, 2)  NULL,
    [is_subarenda]            INT             NULL,
    [is_cmk]                  INT             NULL,
    [cmk_sqr_rented]          NUMERIC (15, 3) NULL,
    [cmk_payment_narah]       NUMERIC (15, 3) NULL,
    [cmk_payment_to_budget]   NUMERIC (15, 3) NULL,
    [cmk_rent_debt]           NUMERIC (15, 3) NULL,
    [modify_date]             DATETIME        NULL,
    [modified_by]             VARCHAR (128)   NULL,
    [is_deleted]              INT             NULL,
    [del_date]                DATETIME        NULL,
    [id]                      INT             NOT NULL,
    [archive_entry_id]        INT             IDENTITY (1, 1) NOT NULL,
    [archive_entry_timestamp] DATETIME        NULL,
    [rent_period_id]          INT             NULL,
    [report_id]               INT             NULL,
    PRIMARY KEY CLUSTERED ([archive_entry_id] ASC),
    CONSTRAINT [FK_arch_arenda_rented_arenda] FOREIGN KEY ([id]) REFERENCES [dbo].[arenda_rented] ([id]) ON DELETE CASCADE ON UPDATE CASCADE
);

