CREATE TABLE [dbo].[arenda] (
    [id]                      INT             NOT NULL,
    [building_id]             INT             NULL,
    [org_balans_id]           INT             NULL,
    [org_renter_id]           INT             NULL,
    [org_giver_id]            INT             NULL,
    [balans_id]               INT             NULL,
    [rent_year]               INT             NULL,
    [object_kind_id]          INT             NULL,
    [purpose_group_id]        INT             NULL,
    [purpose_id]              INT             NULL,
    [purpose_str]             VARCHAR (252)   NULL,
    [name]                    VARCHAR (252)   NULL,
    [is_privat]               INT             NULL,
    [update_src_id]           INT             NULL,
    [agreement_kind_id]       INT             NULL,
    [agreement_date]          DATE            NULL,
    [agreement_num]           VARCHAR (18)    NULL,
    [agreement_str]           VARCHAR (252)   NULL,
    [floor_number]            VARCHAR (100)   NULL,
    [num_people]              INT             NULL,
    [cost_narah]              NUMERIC (15, 3) NULL,
    [cost_payed]              NUMERIC (15, 3) NULL,
    [cost_debt]               NUMERIC (15, 3) NULL,
    [cost_agreement]          NUMERIC (15, 3) NULL,
    [cost_expert_1m]          NUMERIC (15, 3) NULL,
    [cost_expert_total]       NUMERIC (15, 3) NULL,
    [pidstava]                VARCHAR (252)   NULL,
    [pidstava_date]           DATE            NULL,
    [pidstava_num]            VARCHAR (18)    NULL,
    [pidstava_fact]           VARCHAR (200)   NULL,
    [pidstava2]               VARCHAR (252)   NULL,
    [pidstava_num2]           VARCHAR (18)    NULL,
    [pidstava_date2]          DATE            NULL,
    [pidstava_display]        VARCHAR (MAX)   NULL,
    [rent_start_date]         DATE            NULL,
    [rent_finish_date]        DATE            NULL,
    [rent_actual_finish_date] DATE            NULL,
    [rent_rate]               NUMERIC (15, 3) NULL,
    [rent_rate_uah]           NUMERIC (15, 3) NULL,
    [rent_square]             NUMERIC (9, 2)  NULL,
    [priznak_1nf]             INT             NULL,
    [debt_timespan]           VARCHAR (18)    NULL,
    [order_num]               VARCHAR (18)    NULL,
    [order_date]              DATE            NULL,
    [order_no2]               VARCHAR (18)    NULL,
    [rishennya_id]            INT             NULL,
    [is_inactive]             INT             NULL,
    [inactive_date]           DATE            NULL,
    [is_deleted]              INT             NULL,
    [del_date]                DATE            NULL,
    [date_expert]             DATE            NULL,
    [is_subarenda]            INT             NULL,
    [privat_kind_id]          INT             NULL,
    [num_primirnikiv]         INT             NULL,
    [date_expl_enter]         DATE            NULL,
    [num_akt]                 VARCHAR (18)    NULL,
    [date_akt]                DATE            NULL,
    [num_bti]                 VARCHAR (18)    NULL,
    [date_bti]                DATE            NULL,
    [svidotstvo_serial]       VARCHAR (3)     NULL,
    [svidotstvo_num]          VARCHAR (18)    NULL,
    [svidotstvo_date]         DATE            NULL,
    [payment_type_id]         INT             NULL,
    [arch_id]                 INT             NULL,
    [modified_by]             VARCHAR (128)   NULL,
    [modify_date]             DATETIME        NULL,
    [note]                    VARCHAR (MAX)   NULL,
    [agreement_state]         INT             DEFAULT ((1)) NULL,
    [is_insured]              INT             NULL,
    [insurance_start]         DATE            NULL,
    [insurance_end]           DATE            NULL,
    [insurance_sum]           NUMERIC (15, 2) NULL,
    [is_loan_agreement]       INT             NULL,
    [orandodavec_user_id]     INT             NULL,
    [base_month]              DATE            NULL,
    [method_calc_id]          INT             NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_arenda_agreement_kind] FOREIGN KEY ([agreement_kind_id]) REFERENCES [dbo].[dict_arenda_agreement_kind] ([id]),
    CONSTRAINT [fk_arenda_balans] FOREIGN KEY ([balans_id]) REFERENCES [dbo].[balans] ([id]),
    CONSTRAINT [fk_arenda_object] FOREIGN KEY ([building_id]) REFERENCES [dbo].[buildings] ([id]),
    CONSTRAINT [fk_arenda_object_kind] FOREIGN KEY ([object_kind_id]) REFERENCES [dbo].[dict_object_kind_old] ([id]),
    CONSTRAINT [fk_arenda_org_balans] FOREIGN KEY ([org_balans_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_arenda_org_giver] FOREIGN KEY ([org_giver_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_arenda_org_renter] FOREIGN KEY ([org_renter_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_arenda_payment_type] FOREIGN KEY ([payment_type_id]) REFERENCES [dbo].[dict_arenda_payment_type] ([id]),
    CONSTRAINT [fk_arenda_privat_kind] FOREIGN KEY ([privat_kind_id]) REFERENCES [dbo].[dict_arenda_privat_kind] ([id]),
    CONSTRAINT [fk_arenda_purpose] FOREIGN KEY ([purpose_id]) REFERENCES [dbo].[dict_balans_purpose] ([id]),
    CONSTRAINT [fk_arenda_purpose_group] FOREIGN KEY ([purpose_group_id]) REFERENCES [dbo].[dict_balans_purpose_group] ([id]),
    CONSTRAINT [fk_arenda_update_src] FOREIGN KEY ([update_src_id]) REFERENCES [dbo].[dict_balans_update_src] ([id])
);

