CREATE TABLE [dbo].[arenda_decisions] (
    [id]               INT             NOT NULL,
    [decision_id]      INT             NULL,
    [etr]              VARCHAR (2)     NULL,
    [rent_term]        VARCHAR (252)   NULL,
    [rent_term_note]   VARCHAR (252)   NULL,
    [title]            VARCHAR (252)   NULL,
    [rent_purpose]     VARCHAR (252)   NULL,
    [nov_prot]         VARCHAR (1)     DEFAULT ('') NULL,
    [building_id]      INT             NULL,
    [org_renter_id]    INT             NULL,
    [org_balans_id]    INT             NULL,
    [org_giver_id]     INT             NULL,
    [balans_id]        INT             NULL,
    [apply_date]       DATE            NULL,
    [apply_letter_id]  INT             DEFAULT ((0)) NULL,
    [apply_letter_num] VARCHAR (9)     DEFAULT ((0)) NULL,
    [appendix_prot_id] INT             NULL,
    [appendix_rasp_id] INT             NULL,
    [application_id]   INT             NULL,
    [num_rooms]        INT             DEFAULT ((0)) NULL,
    [sqr_applied]      NUMERIC (15, 2) NULL,
    [sqr_robocha]      NUMERIC (15, 2) NULL,
    [cost_1m]          NUMERIC (15, 2) NULL,
    [cost_rent]        NUMERIC (15, 2) NULL,
    [is_subarenda]     INT             NULL,
    [stadiya_id]       INT             NULL,
    [rishen_punkt]     INT             NULL,
    [modified_by]      VARCHAR (128)   NULL,
    [modify_date]      DATE            DEFAULT (getdate()) NULL,
    [note_rish_etap1]  VARCHAR (MAX)   NULL,
    [note_rish2_etap1] VARCHAR (MAX)   NULL,
    [note_nazva]       VARCHAR (MAX)   NULL,
    [note_rish_etap2]  VARCHAR (MAX)   NULL,
    [note_rish2_etap2] VARCHAR (MAX)   NULL,
    [blob_rish_etap1]  VARBINARY (MAX) NULL,
    [blob_rish2_etap1] VARBINARY (MAX) NULL,
    [blob_nazva]       VARBINARY (MAX) NULL,
    [blob_rish_etap2]  VARBINARY (MAX) NULL,
    [blob_rish2_etap2] VARBINARY (MAX) NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_rent_decisions_balans] FOREIGN KEY ([org_balans_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_rent_decisions_building] FOREIGN KEY ([building_id]) REFERENCES [dbo].[buildings] ([id]),
    CONSTRAINT [fk_rent_decisions_decision] FOREIGN KEY ([decision_id]) REFERENCES [dbo].[dict_rent_decisions] ([id]),
    CONSTRAINT [fk_rent_decisions_giver] FOREIGN KEY ([org_giver_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_rent_decisions_protocol] FOREIGN KEY ([appendix_prot_id]) REFERENCES [dbo].[doc_appendices] ([id]),
    CONSTRAINT [fk_rent_decisions_raspor] FOREIGN KEY ([appendix_rasp_id]) REFERENCES [dbo].[doc_appendices] ([id]),
    CONSTRAINT [fk_rent_decisions_renter] FOREIGN KEY ([org_renter_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_rent_decisions_stadiya] FOREIGN KEY ([stadiya_id]) REFERENCES [dbo].[dict_doc_stadiya] ([id])
);

