CREATE TABLE [dbo].[balans] (
    [id]                    INT             NOT NULL,
    [year_balans]           INT             NULL,
    [building_id]           INT             NULL,
    [organization_id]       INT             NULL,
    [sqr_total]             NUMERIC (9, 2)  NULL,
    [sqr_pidval]            NUMERIC (9, 2)  NULL,
    [sqr_vlas_potreb]       NUMERIC (9, 2)  NULL,
    [sqr_free]              NUMERIC (9, 2)  NULL,
    [sqr_in_rent]           NUMERIC (9, 2)  NULL,
    [sqr_privatizov]        NUMERIC (9, 2)  NULL,
    [sqr_not_for_rent]      NUMERIC (9, 2)  NULL,
    [sqr_gurtoj]            NUMERIC (9, 2)  NULL,
    [sqr_non_habit]         NUMERIC (9, 2)  NULL,
    [sqr_kor]               NUMERIC (9, 2)  NULL,
    [cost_balans]           NUMERIC (15, 3) NULL,
    [cost_fair]             NUMERIC (15, 3) NULL,
    [cost_expert_1m]        NUMERIC (15, 3) NULL,
    [cost_expert_total]     NUMERIC (15, 3) NULL,
    [cost_rent_narah]       NUMERIC (15, 3) NULL,
    [cost_rent_payed]       NUMERIC (15, 3) NULL,
    [cost_debt]             NUMERIC (15, 3) NULL,
    [cost_zalishkova]       NUMERIC (15, 3) NULL,
    [cost_rinkova]          NUMERIC (15, 3) NULL,
    [cost_fair_1m]          NUMERIC (15, 3) NULL,
    [num_people]            INT             NULL,
    [num_rent_agr]          INT             NULL,
    [num_privat_apt]        INT             NULL,
    [o26_id]                INT             NULL,
    [bti_id]                VARCHAR (1000)  NULL,
    [approval_by]           VARCHAR (100)   NULL,
    [approval_num]          VARCHAR (18)    NULL,
    [approval_date]         DATE            NULL,
    [form_ownership_id]     INT             NULL,
    [object_kind_id]        INT             NULL,
    [object_type_id]        INT             NULL,
    [history_id]            INT             NULL,
    [tech_condition_id]     INT             NULL,
    [purpose_group_id]      INT             NULL,
    [purpose_id]            INT             NULL,
    [purpose_str]           VARCHAR (255)   NULL,
    [floors]                VARCHAR (100)   NULL,
    [priznak_1nf]           INT             NULL,
    [ownership_type_id]     INT             NULL,
    [obj_street_name]       VARCHAR (100)   NULL,
    [obj_street_id]         INT             NULL,
    [obj_street_name2]      VARCHAR (100)   NULL,
    [obj_street_id2]        INT             NULL,
    [obj_nomer1]            VARCHAR (10)    NULL,
    [obj_nomer2]            VARCHAR (18)    NULL,
    [obj_nomer3]            VARCHAR (10)    NULL,
    [obj_nomer]             AS              ((((ltrim(rtrim(isnull([obj_nomer1],'')))+' ')+ltrim(rtrim(isnull([obj_nomer2],''))))+' ')+ltrim(rtrim(isnull([obj_nomer3],'')))),
    [obj_bti_code]          VARCHAR (1000)  NULL,
    [obj_addr_misc]         VARCHAR (100)   NULL,
    [obj_street_misc]       VARCHAR (255)   NULL,
    [modified_by]           VARCHAR (128)   NULL,
    [modify_date]           DATETIME        NULL,
    [form_giver_id]         INT             NULL,
    [org_maintain_id]       INT             NULL,
    [update_src_id]         INT             NULL,
    [is_deleted]            INT             NULL,
    [del_date]              DATE            NULL,
    [znos]                  NUMERIC (15, 3) NULL,
    [znos_date]             DATE            NULL,
    [date_expert]           DATE            NULL,
    [reestr_no]             VARCHAR (100)   NULL,
    [fair_cost_date]        DATE            NULL,
    [otdel_gukv_id]         INT             NULL,
    [date_bti]              DATE            NULL,
    [arch_id]               INT             NULL,
    [arch_flag]             INT             CONSTRAINT [DF__balans__arch_fla__5F3B8DD0] DEFAULT ((0)) NULL,
    [date_cost_rinkova]     DATE            NULL,
    [memo]                  VARCHAR (MAX)   NULL,
    [note]                  VARCHAR (MAX)   NULL,
    [is_free_sqr]           INT             NULL,
    [free_sqr_useful]       NUMERIC (9, 2)  NULL,
    [free_sqr_condition_id] VARCHAR (1000)  NULL,
    [free_sqr_location]     VARCHAR (100)   NULL,
    [ownership_doc_type]    INT             NULL,
    [ownership_doc_num]     VARCHAR (24)    NULL,
    [ownership_doc_date]    DATETIME        NULL,
    [balans_doc_type]       INT             NULL,
    [balans_doc_num]        VARCHAR (24)    NULL,
    [balans_doc_date]       DATETIME        NULL,
    [vidch_doc_type]        INT             NULL,
    [vidch_doc_num]         VARCHAR (24)    NULL,
    [vidch_doc_date]        DATETIME        NULL,
    [vidch_type_id]         INT             NULL,
    [vidch_org_id]          INT             NULL,
    [vidch_cost]            NUMERIC (15, 3) NULL,
    [sqr_engineering]       NUMERIC (9, 2)  NULL,
    [obj_status_id]         INT             NULL,
    [geodata_map_opoints]   VARCHAR (8000)  NULL,
    [znizhino_flag]         BIT             DEFAULT ((0)) NOT NULL,
    [znizhino_percent]      NUMERIC (15, 3) NULL,
    [znizhino_stanom]       DATE            NULL,
    [znizhino_shkoda]       BIT             DEFAULT ((0)) NOT NULL,
    [znizhino_zvitakt]      BIT             DEFAULT ((0)) NOT NULL,
    [znizhino_primitka]     VARCHAR (4000)  NULL,
    CONSTRAINT [PK__balans__3213E83F6123D642] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_balans_form_giver] FOREIGN KEY ([form_giver_id]) REFERENCES [dbo].[dict_balans_form_giver] ([id]),
    CONSTRAINT [fk_balans_form_ownership] FOREIGN KEY ([form_ownership_id]) REFERENCES [dbo].[dict_org_ownership] ([id]),
    CONSTRAINT [fk_balans_history] FOREIGN KEY ([history_id]) REFERENCES [dbo].[dict_history] ([id]),
    CONSTRAINT [fk_balans_o26] FOREIGN KEY ([o26_id]) REFERENCES [dbo].[dict_balans_o26] ([id]),
    CONSTRAINT [fk_balans_obj_status] FOREIGN KEY ([obj_status_id]) REFERENCES [dbo].[dict_balans_obj_status] ([id]),
    CONSTRAINT [fk_balans_object] FOREIGN KEY ([building_id]) REFERENCES [dbo].[buildings] ([id]),
    CONSTRAINT [fk_balans_object_kind] FOREIGN KEY ([object_kind_id]) REFERENCES [dbo].[dict_object_kind] ([id]),
    CONSTRAINT [fk_balans_object_type] FOREIGN KEY ([object_type_id]) REFERENCES [dbo].[dict_object_type] ([id]),
    CONSTRAINT [fk_balans_org] FOREIGN KEY ([organization_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_balans_org_maintain_id] FOREIGN KEY ([org_maintain_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_balans_otdel] FOREIGN KEY ([otdel_gukv_id]) REFERENCES [dbo].[dict_otdel_gukv] ([id]),
    CONSTRAINT [fk_balans_ownership_type] FOREIGN KEY ([ownership_type_id]) REFERENCES [dbo].[dict_balans_ownership_type] ([id]),
    CONSTRAINT [fk_balans_purpose] FOREIGN KEY ([purpose_id]) REFERENCES [dbo].[dict_balans_purpose] ([id]),
    CONSTRAINT [fk_balans_purpose_group] FOREIGN KEY ([purpose_group_id]) REFERENCES [dbo].[dict_balans_purpose_group] ([id]),
    CONSTRAINT [fk_balans_tech_condition] FOREIGN KEY ([tech_condition_id]) REFERENCES [dbo].[dict_tech_state] ([id]),
    CONSTRAINT [fk_balans_update_src] FOREIGN KEY ([update_src_id]) REFERENCES [dbo].[dict_balans_update_src] ([id]),
    CONSTRAINT [fk_balans_vidch_org] FOREIGN KEY ([vidch_org_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_balans_vidch_type] FOREIGN KEY ([vidch_type_id]) REFERENCES [dbo].[dict_balans_vidch_type] ([id])
);


GO
CREATE NONCLUSTERED INDEX [indx_balans_building_id]
    ON [dbo].[balans]([building_id] ASC);

