CREATE TABLE [dbo].[building_docs] (
    [id]                  INT             IDENTITY (1, 1) NOT NULL,
    [building_id]         INT             NOT NULL,
    [document_id]         INT             NOT NULL,
    [obj_name]            VARCHAR (255)   NULL,
    [obj_description]     VARCHAR (100)   NULL,
    [obj_build_year]      INT             NULL,
    [obj_expl_enter_year] INT             NULL,
    [obj_length]          NUMERIC (9, 2)  NULL,
    [note]                VARCHAR (MAX)   NULL,
    [cost_balans]         NUMERIC (15, 3) NULL,
    [cost_znos]           NUMERIC (15, 3) NULL,
    [cost_zalishkova]     NUMERIC (15, 3) NULL,
    [cost_expert]         NUMERIC (15, 3) NULL,
    [num_rooms]           INT             NULL,
    [num_floors]          INT             NULL,
    [obj_location]        VARCHAR (60)    NULL,
    [purpose_group_id]    INT             NULL,
    [purpose_id]          INT             NULL,
    [tech_condition_id]   INT             NULL,
    [object_kind_id]      INT             DEFAULT ((0)) NULL,
    [object_type_id]      INT             NULL,
    [sqr_obj]             NUMERIC (9, 2)  NULL,
    [sqr_free]            NUMERIC (9, 2)  NULL,
    [sqr_habit]           NUMERIC (9, 2)  NULL,
    [sqr_non_habit]       NUMERIC (9, 2)  NULL,
    [is_not_in_work]      INT             DEFAULT ((0)) NULL,
    [modified_by]         VARCHAR (128)   NULL,
    [modify_date]         DATE            NULL,
    [doc_dodatok]         VARCHAR (8)     NULL,
    [doc_tab]             VARCHAR (8)     NULL,
    [doc_pos]             VARCHAR (12)    NULL,
    [doc_change_type_id]  INT             NULL,
    [doc_change_num]      VARCHAR (20)    NULL,
    [doc_change_date]     DATE            NULL,
    [doc_change_doc_id]   INT             NULL,
    [form_ownership_id]   INT             NULL,
    [is_on_balans]        INT             NULL,
    [org_id]              INT             NULL,
    [last_org_id]         INT             NULL,
    [date_expert]         DATE            NULL,
    [date_priv]           DATE            NULL,
    [ozn_priv_id]         INT             NULL,
    [pipe_diameter]       VARCHAR (20)    NULL,
    [pipe_material]       VARCHAR (20)    NULL,
    [old_id]              INT             NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_building_docs_building] FOREIGN KEY ([building_id]) REFERENCES [dbo].[buildings] ([id]),
    CONSTRAINT [fk_building_docs_change_type] FOREIGN KEY ([doc_change_type_id]) REFERENCES [dbo].[dict_doc_change_type] ([id]),
    CONSTRAINT [fk_building_docs_changed_doc] FOREIGN KEY ([doc_change_doc_id]) REFERENCES [dbo].[documents] ([id]),
    CONSTRAINT [fk_building_docs_document] FOREIGN KEY ([document_id]) REFERENCES [dbo].[documents] ([id]),
    CONSTRAINT [fk_building_docs_form_ownership] FOREIGN KEY ([form_ownership_id]) REFERENCES [dbo].[dict_org_ownership] ([id]),
    CONSTRAINT [fk_building_docs_last_org] FOREIGN KEY ([last_org_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_building_docs_object_kind] FOREIGN KEY ([object_kind_id]) REFERENCES [dbo].[dict_object_kind_old] ([id]),
    CONSTRAINT [fk_building_docs_object_type] FOREIGN KEY ([object_type_id]) REFERENCES [dbo].[dict_object_type] ([id]),
    CONSTRAINT [fk_building_docs_org] FOREIGN KEY ([org_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_building_docs_purpose] FOREIGN KEY ([purpose_id]) REFERENCES [dbo].[dict_balans_purpose] ([id]),
    CONSTRAINT [fk_building_docs_purpose_group] FOREIGN KEY ([purpose_group_id]) REFERENCES [dbo].[dict_balans_purpose_group] ([id]),
    CONSTRAINT [fk_building_docs_tech_condition] FOREIGN KEY ([tech_condition_id]) REFERENCES [dbo].[dict_tech_state] ([id])
);

