CREATE TABLE [dbo].[buildings] (
    [id]                 INT             NOT NULL,
    [master_building_id] INT             NULL,
    [addr_street_name]   VARCHAR (500)   DEFAULT (' ') NULL,
    [addr_street_id]     INT             NULL,
    [addr_street_name2]  VARCHAR (128)   NULL,
    [addr_street_id2]    INT             NULL,
    [street_full_name]   VARCHAR (128)   NULL,
    [addr_distr_old_id]  INT             NULL,
    [addr_distr_new_id]  INT             NULL,
    [addr_nomer1]        VARCHAR (32)    DEFAULT (' ') NULL,
    [addr_nomer2]        VARCHAR (32)    DEFAULT (' ') NULL,
    [addr_nomer3]        VARCHAR (32)    DEFAULT (' ') NULL,
    [addr_nomer]         AS              ((((ltrim(rtrim(isnull([addr_nomer1],'')))+' ')+ltrim(rtrim(isnull([addr_nomer2],''))))+' ')+ltrim(rtrim(isnull([addr_nomer3],'')))),
    [addr_misc]          VARCHAR (128)   DEFAULT (' ') NULL,
    [addr_korpus_flag]   INT             NULL,
    [addr_korpus]        VARCHAR (255)   NULL,
    [addr_zip_code]      VARCHAR (24)    NULL,
    [addr_address]       AS              ((((((((isnull([street_full_name],'')+' ')+ltrim(rtrim(isnull([addr_nomer1],''))))+' ')+ltrim(rtrim(isnull([addr_nomer2],''))))+' ')+ltrim(rtrim(isnull([addr_nomer3],''))))+' ')+isnull([addr_misc],'')),
    [tech_condition_id]  INT             NULL,
    [date_begin]         DATE            NULL,
    [date_end]           DATE            NULL,
    [num_floors]         VARCHAR (24)    NULL,
    [construct_year]     INT             NULL,
    [condition_year]     INT             NULL,
    [is_condition_valid] INT             NULL,
    [bti_code]           VARCHAR (24)    NULL,
    [history_id]         INT             NULL,
    [object_type_id]     INT             NULL,
    [object_kind_id]     INT             NULL,
    [is_land]            INT             NULL,
    [modify_date]        DATE            NULL,
    [modified_by]        VARCHAR (128)   NULL,
    [kadastr_code]       VARCHAR (32)    NULL,
    [cost_balans]        NUMERIC (15, 3) NULL,
    [sqr_total]          NUMERIC (9, 2)  NULL,
    [sqr_pidval]         NUMERIC (9, 2)  NULL,
    [sqr_mk]             NUMERIC (9, 2)  NULL,
    [sqr_dk]             NUMERIC (9, 2)  NULL,
    [sqr_rk]             NUMERIC (9, 2)  NULL,
    [sqr_other]          NUMERIC (9, 2)  NULL,
    [sqr_rented]         NUMERIC (9, 2)  NULL,
    [sqr_zagal]          NUMERIC (9, 2)  NULL,
    [sqr_for_rent]       NUMERIC (9, 2)  NULL,
    [sqr_habit]          NUMERIC (9, 2)  NULL,
    [sqr_non_habit]      NUMERIC (9, 2)  NULL,
    [additional_info]    VARCHAR (252)   NULL,
    [is_deleted]         INT             NULL,
    [del_date]           DATE            NULL,
    [oatuu_id]           VARCHAR (10)    NULL,
    [updpr]              INT             NULL,
    [arch_id]            INT             NULL,
    [arch_flag]          INT             DEFAULT ((0)) NULL,
    [facade_id]          INT             NULL,
    [nomer_int]          INT             NULL,
    [characteristics]    VARCHAR (MAX)   NULL,
    [expl_enter_year]    INT             NULL,
    [is_basement_exists] INT             NULL,
    [is_loft_exists]     INT             NULL,
    [sqr_loft]           NUMERIC (9, 2)  NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_buildings_dict_street] FOREIGN KEY ([addr_street_id]) REFERENCES [dbo].[dict_streets] ([id]),
    CONSTRAINT [fk_buildings_distr_new] FOREIGN KEY ([addr_distr_new_id]) REFERENCES [dbo].[dict_districts2] ([id]),
    CONSTRAINT [fk_buildings_distr_old] FOREIGN KEY ([addr_distr_old_id]) REFERENCES [dbo].[dict_districts] ([id]),
    CONSTRAINT [fk_buildings_history] FOREIGN KEY ([history_id]) REFERENCES [dbo].[dict_history] ([id]),
    CONSTRAINT [fk_buildings_obj_kind] FOREIGN KEY ([object_kind_id]) REFERENCES [dbo].[dict_object_kind] ([id]),
    CONSTRAINT [fk_buildings_obj_type] FOREIGN KEY ([object_type_id]) REFERENCES [dbo].[dict_object_type] ([id]),
    CONSTRAINT [fk_buildings_tech_stan] FOREIGN KEY ([tech_condition_id]) REFERENCES [dbo].[dict_tech_state] ([id])
);


GO
CREATE NONCLUSTERED INDEX [indx_buildings]
    ON [dbo].[buildings]([addr_street_id] ASC);

