CREATE TABLE [dbo].[documents] (
    [id]               INT             NOT NULL,
    [kind_id]          INT             NULL,
    [general_kind_id]  INT             NULL,
    [doc_date]         DATE            NULL,
    [doc_num]          VARCHAR (20)    NULL,
    [topic]            VARCHAR (255)   NULL,
    [serial_num]       VARCHAR (24)    NULL,
    [note]             VARCHAR (MAX)   NULL,
    [modified_by]      VARCHAR (128)   NULL,
    [modify_date]      DATE            NULL,
    [display_name]     AS              (((N'Документ N '+rtrim([doc_num]))+N' вiд ')+CONVERT([varchar](32),[doc_date],(104))),
    [search_name]      AS              (case when [doc_num] IS NULL then coalesce([topic],'')+N' Б/Н' else ((((N'№ '+rtrim([doc_num]))+N' вiд ')+coalesce(CONVERT([varchar](32),[doc_date],(104)),''))+N': ')+coalesce([topic],'') end),
    [is_not_in_work]   INT             DEFAULT ((0)) NULL,
    [is_archived]      INT             DEFAULT ((0)) NULL,
    [is_reconstruct]   INT             NULL,
    [is_text_exists]   INT             NULL,
    [is_priv_rishen]   INT             NULL,
    [receive_date]     DATE            NULL,
    [commission_id]    INT             NULL,
    [source_id]        INT             NULL,
    [state_id]         INT             NULL,
    [priv_date]        DATE            NULL,
    [summa]            NUMERIC (15, 3) NULL,
    [summa_zalishkova] NUMERIC (15, 3) NULL,
    [extern_doc_id]    INT             NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_documents_doc_kind] FOREIGN KEY ([kind_id]) REFERENCES [dbo].[dict_doc_kind] ([id]),
    CONSTRAINT [fk_documents_source] FOREIGN KEY ([source_id]) REFERENCES [dbo].[dict_doc_source] ([id]),
    CONSTRAINT [fk_documents_state] FOREIGN KEY ([state_id]) REFERENCES [dbo].[dict_doc_state] ([id])
);

