CREATE TABLE [dbo].[expert_note] (
    [id]                 INT             NOT NULL,
    [org_renter_id]      INT             NULL,
    [org_renter_name]    VARCHAR (255)   NULL,
    [org_balans_id]      INT             NULL,
    [org_balans_name]    VARCHAR (255)   NULL,
    [building_id]        INT             NULL,
    [balans_id]          INT             NULL,
    [addr_district_id]   INT             NULL,
    [expert_obj_type_id] INT             NULL,
    [obj_square]         NUMERIC (15, 2) NULL,
    [expert_id]          INT             NULL,
    [expert_name]        VARCHAR (255)   NULL,
    [modified_by]        VARCHAR (128)   NULL,
    [modify_date]        DATETIME        NULL,
    [rezenz_id]          INT             NULL,
    [addr_street_name]   VARCHAR (500)   NULL,
    [cost_1_usd]         NUMERIC (15, 2) NULL,
    [cost_prim]          NUMERIC (15, 2) NULL,
    [valuation_date]     DATE            NULL,
    [final_date]         DATE            NULL,
    [arch_num]           VARCHAR (10)    NULL,
    [arch_date]          DATE            NULL,
    [is_archived]        INT             DEFAULT ((0)) NULL,
    [is_stand_oc]        INT             DEFAULT ((0)) NULL,
    [is_deleted]         INT             DEFAULT ((0)) NULL,
    [del_date]           DATE            NULL,
    [addr_number1]       VARCHAR (9)     NULL,
    [addr_number2]       VARCHAR (64)    NULL,
    [note_text]          VARCHAR (4000)  NULL,
    [addr_street_id]     INT             NULL,
    [addr_nomer]         VARCHAR (256)   NULL,
    [valuation_kind_id]  INT             NULL,
    [stan_id]            INT             NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_expert_note_bal_org] FOREIGN KEY ([org_balans_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_expert_note_balans] FOREIGN KEY ([balans_id]) REFERENCES [dbo].[balans] ([id]),
    CONSTRAINT [fk_expert_note_building] FOREIGN KEY ([building_id]) REFERENCES [dbo].[buildings] ([id]),
    CONSTRAINT [FK_expert_note_dict_street] FOREIGN KEY ([addr_street_id]) REFERENCES [dbo].[dict_streets] ([id]),
    CONSTRAINT [fk_expert_note_district] FOREIGN KEY ([addr_district_id]) REFERENCES [dbo].[dict_districts2] ([id]),
    CONSTRAINT [fk_expert_note_expert] FOREIGN KEY ([expert_id]) REFERENCES [dbo].[dict_expert] ([id]),
    CONSTRAINT [fk_expert_note_obj_type] FOREIGN KEY ([expert_obj_type_id]) REFERENCES [dbo].[dict_expert_obj_type] ([id]),
    CONSTRAINT [fk_expert_note_renter] FOREIGN KEY ([org_renter_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_expert_note_rezenz] FOREIGN KEY ([rezenz_id]) REFERENCES [dbo].[dict_expert_rezenz] ([id]),
    CONSTRAINT [fk_expert_note_stan] FOREIGN KEY ([stan_id]) REFERENCES [dbo].[dict_expert_stan] ([id]),
    CONSTRAINT [FK_expert_note_valuation_kind_id] FOREIGN KEY ([valuation_kind_id]) REFERENCES [dbo].[dict_expert_valuation_kind] ([id])
);

