CREATE TABLE [dbo].[inventarization] (
    [id]                  INT             IDENTITY (1, 1) NOT NULL,
    [org_id]              INT             NULL,
    [zkpo_code]           VARCHAR (8)     NULL,
    [location]            VARCHAR (256)   NULL,
    [name]                VARCHAR (256)   NULL,
    [inv_number]          VARCHAR (30)    NULL,
    [filiya]              VARCHAR (4)     NULL,
    [inv_code]            INT             NULL,
    [prefix]              VARCHAR (3)     NULL,
    [suffix]              VARCHAR (3)     NULL,
    [sqr_total]           DECIMAL (15, 3) NULL,
    [initial_cost]        DECIMAL (18, 2) NULL,
    [dodvart]             DECIMAL (18, 2) NULL,
    [znos]                DECIMAL (18, 2) NULL,
    [remaining_cost]      DECIMAL (18, 2) NULL,
    [on_balance_date]     DATE            NULL,
    [commissioned_date]   DATE            NULL,
    [decommissioned_date] DATE            NULL,
    [yer_on]              SMALLINT        NULL,
    [mesu_on]             VARCHAR (10)    NULL,
    [yer_off]             SMALLINT        NULL,
    [mesu_off]            VARCHAR (10)    NULL,
    [yer_period]          SMALLINT        NULL,
    [addr_name]           VARCHAR (256)   NULL,
    [doc_number_on]       VARCHAR (256)   NULL,
    [doc_date_on]         DATE            NULL,
    [doc_number_off]      VARCHAR (256)   NULL,
    [doc_date_off]        DATE            NULL,
    [comments]            VARCHAR (128)   NULL,
    CONSTRAINT [PK__inventar__3213E83F584371FF] PRIMARY KEY CLUSTERED ([id] ASC)
);

