CREATE TABLE [dbo].[m_report_balans_and_arenda] (
    [balans_id]                 INT             NOT NULL,
    [building_id]               INT             NULL,
    [organization_id]           INT             NULL,
    [org_full_name]             VARCHAR (255)   NULL,
    [org_short_name]            VARCHAR (255)   NULL,
    [org_zkpo_code]             VARCHAR (16)    NULL,
    [org_industry]              VARCHAR (40)    NULL,
    [org_occupation]            VARCHAR (50)    NULL,
    [org_old_industry]          VARCHAR (200)   NULL,
    [org_old_occupation]        VARCHAR (200)   NULL,
    [org_vedomstvo]             VARCHAR (255)   NULL,
    [org_ownership]             VARCHAR (40)    NULL,
    [district]                  VARCHAR (64)    NULL,
    [street_full_name]          VARCHAR (160)   NULL,
    [addr_nomer]                VARCHAR (98)    NULL,
    [balans_sqr_total]          NUMERIC (9, 2)  NULL,
    [balans_sqr_pidval]         NUMERIC (9, 2)  NULL,
    [balans_sqr_vlas_potreb]    NUMERIC (9, 2)  NULL,
    [balans_sqr_free]           NUMERIC (9, 2)  NULL,
    [balans_sqr_in_rent]        NUMERIC (9, 2)  NULL,
    [balans_sqr_privatizov]     NUMERIC (9, 2)  NULL,
    [balans_sqr_not_for_rent]   NUMERIC (9, 2)  NULL,
    [balans_sqr_gurtoj]         NUMERIC (9, 2)  NULL,
    [balans_sqr_non_habit]      NUMERIC (9, 2)  NULL,
    [balans_cost_balans]        NUMERIC (15, 3) NULL,
    [balans_cost_expert_1m]     NUMERIC (15, 3) NULL,
    [balans_cost_expert_total]  NUMERIC (15, 3) NULL,
    [balans_cost_zalishkova]    NUMERIC (15, 3) NULL,
    [num_rent_agr]              INT             NULL,
    [num_privat_apt]            INT             NULL,
    [approval_by]               VARCHAR (100)   NULL,
    [approval_num]              VARCHAR (18)    NULL,
    [approval_date]             DATE            NULL,
    [o26_code]                  VARCHAR (60)    NULL,
    [bti_condition]             VARCHAR (1000)  NULL,
    [num_floors]                VARCHAR (24)    NULL,
    [org_maintain_id]           INT             NULL,
    [org_maintainer_full_name]  VARCHAR (255)   NULL,
    [org_maintainer_short_name] VARCHAR (255)   NULL,
    [org_maintainer_zkpo_code]  VARCHAR (16)    NULL,
    [otdel_gukv]                VARCHAR (60)    NULL,
    [form_ownership]            VARCHAR (40)    NULL,
    [ownership_type]            VARCHAR (50)    NULL,
    [object_kind]               VARCHAR (273)   NULL,
    [object_type]               VARCHAR (64)    NULL,
    [condition]                 VARCHAR (64)    NULL,
    [purpose_group]             VARCHAR (160)   NULL,
    [purpose]                   VARCHAR (160)   NULL,
    [history]                   VARCHAR (64)    NULL,
    [date_expert]               DATE            NULL,
    [floors]                    VARCHAR (100)   NULL,
    [obj_bti_code]              VARCHAR (1000)  NULL,
    [memo]                      VARCHAR (MAX)   NULL,
    [note]                      VARCHAR (MAX)   NULL,
    [znos]                      NUMERIC (15, 3) NULL,
    [znos_date]                 DATE            NULL,
    [input_date]                DATETIME        NULL,
    [addr_zip_code]             VARCHAR (24)    NULL,
    [construct_year]            INT             NULL,
    [oatuu_code]                VARCHAR (10)    NULL,
    [facade]                    VARCHAR (64)    NULL,
    [is_in_privat]              NVARCHAR (3)    NULL,
    [form_ownership_int]        INT             NULL,
    [org_ownership_int]         INT             NULL,
    [balans_obj_name]           VARCHAR (255)   NULL,
    [sqr_free_total]            NUMERIC (15, 3) NULL,
    [sqr_free_korysna]          NUMERIC (15, 3) NULL,
    [sqr_free_mzk]              NUMERIC (15, 3) NULL,
    [free_sqr_floors]           VARCHAR (MAX)   NULL,
    [free_sqr_purpose]          VARCHAR (MAX)   NULL,
    [org_sfera_upr_id]          INT             NULL,
    [org_district_id]           INT             NULL,
    [arenda_id]                 INT             NULL,
    [org_renter_id]             INT             NULL,
    [org_renter_full_name]      VARCHAR (255)   NULL,
    [org_renter_short_name]     VARCHAR (255)   NULL,
    [org_renter_zkpo]           VARCHAR (16)    NULL,
    [org_renter_industry]       VARCHAR (40)    NULL,
    [org_renter_occupation]     VARCHAR (50)    NULL,
    [org_renter_vedomstvo]      VARCHAR (255)   NULL,
    [org_giver_id]              INT             NULL,
    [org_giver_full_name]       VARCHAR (255)   NULL,
    [org_giver_short_name]      VARCHAR (255)   NULL,
    [org_giver_zkpo]            VARCHAR (16)    NULL,
    [org_giver_industry]        VARCHAR (40)    NULL,
    [org_giver_occupation]      VARCHAR (50)    NULL,
    [org_giver_vedomstvo]       VARCHAR (255)   NULL,
    [object_name]               VARCHAR (252)   NULL,
    [object_note]               VARCHAR (MAX)   NULL,
    [is_privat]                 NVARCHAR (3)    NULL,
    [agreement_kind]            VARCHAR (64)    NULL,
    [agreement_date]            DATE            NULL,
    [agreement_date_year]       INT             NULL,
    [agreement_date_quarter]    INT             NULL,
    [agreement_num]             VARCHAR (18)    NULL,
    [floor_number]              VARCHAR (100)   NULL,
    [arenda_cost_narah]         NUMERIC (15, 3) NULL,
    [arenda_cost_payed]         NUMERIC (15, 3) NULL,
    [arenda_cost_debt]          NUMERIC (15, 3) NULL,
    [arenda_cost_agreement]     NUMERIC (15, 3) NULL,
    [arenda_cost_expert_1m]     NUMERIC (15, 3) NULL,
    [arenda_cost_expert_total]  NUMERIC (15, 3) NULL,
    [debt_timespan]             VARCHAR (18)    NULL,
    [pidstava]                  VARCHAR (252)   NULL,
    [pidstava_date]             DATE            NULL,
    [pidstava_num]              VARCHAR (18)    NULL,
    [pidstava_display]          VARCHAR (MAX)   NULL,
    [rent_start_date]           DATE            NULL,
    [rent_start_year]           INT             NULL,
    [rent_start_quarter]        INT             NULL,
    [rent_finish_date]          DATE            NULL,
    [rent_finish_year]          INT             NULL,
    [rent_finish_quarter]       INT             NULL,
    [rent_actual_finish_date]   DATE            NULL,
    [actual_finish_year]        INT             NULL,
    [actual_finish_quarter]     INT             NULL,
    [rent_rate_percent]         NUMERIC (15, 3) NULL,
    [rent_rate_uah]             NUMERIC (15, 3) NULL,
    [rent_square]               NUMERIC (9, 2)  NULL,
    [rishennya_code]            INT             NULL,
    [num_akt]                   VARCHAR (18)    NULL,
    [date_akt]                  DATE            NULL,
    [is_subarenda]              NVARCHAR (3)    NULL,
    [payment_type]              VARCHAR (64)    NULL,
    [agreement_active]          NVARCHAR (3)    NULL,
    [agreement_active_int]      INT             NULL
);

