CREATE TABLE [dbo].[m_view_arenda] (
    [arenda_id]                    INT             NOT NULL,
    [arenda_note_id]               INT             NULL,
    [building_id]                  INT             NULL,
    [balans_id]                    INT             NULL,
    [org_balans_id]                INT             NULL,
    [org_balans_full_name]         VARCHAR (255)   NULL,
    [org_balans_short_name]        VARCHAR (255)   NULL,
    [org_balans_zkpo]              VARCHAR (16)    NULL,
    [org_balans_industry]          VARCHAR (40)    NULL,
    [org_balans_occupation]        VARCHAR (50)    NULL,
    [org_balans_vedomstvo]         VARCHAR (255)   NULL,
    [org_balans_org_form]          VARCHAR (160)   NULL,
    [org_balans_sfera_upr_id]      INT             NULL,
    [org_balans_form_ownership_id] INT             NULL,
    [org_balans_form_ownership]    VARCHAR (40)    NULL,
    [org_balans_district_id]       INT             NULL,
    [org_renter_id]                INT             NULL,
    [org_renter_full_name]         VARCHAR (255)   NULL,
    [org_renter_short_name]        VARCHAR (255)   NULL,
    [org_renter_zkpo]              VARCHAR (16)    NULL,
    [org_renter_industry]          VARCHAR (40)    NULL,
    [org_renter_occupation]        VARCHAR (50)    NULL,
    [org_renter_vedomstvo]         VARCHAR (255)   NULL,
    [org_renter_director_fio]      VARCHAR (70)    NULL,
    [org_renter_director_phone]    VARCHAR (70)    NULL,
    [org_renter_form_of_ownership] VARCHAR (40)    NULL,
    [org_renter_org_form]          VARCHAR (160)   NULL,
    [org_renter_sfera_upr_id]      INT             NULL,
    [org_renter_form_ownership_id] INT             NULL,
    [org_renter_district_id]       INT             NULL,
    [org_giver_id]                 INT             NULL,
    [org_giver_full_name]          VARCHAR (255)   NULL,
    [org_giver_short_name]         VARCHAR (255)   NULL,
    [org_giver_zkpo]               VARCHAR (16)    NULL,
    [org_giver_industry]           VARCHAR (40)    NULL,
    [org_giver_occupation]         VARCHAR (50)    NULL,
    [org_giver_vedomstvo]          VARCHAR (255)   NULL,
    [org_giver_org_form]           VARCHAR (160)   NULL,
    [org_giver_sfera_upr_id]       INT             NULL,
    [org_giver_form_ownership_id]  INT             NULL,
    [org_giver_district_id]        INT             NULL,
    [district]                     VARCHAR (64)    NULL,
    [street_full_name]             VARCHAR (160)   NULL,
    [addr_nomer]                   VARCHAR (98)    NULL,
    [is_in_privat]                 NVARCHAR (3)    NULL,
    [sqr_free_total]               NUMERIC (15, 3) NULL,
    [sqr_free_korysna]             NUMERIC (15, 3) NULL,
    [sqr_free_mzk]                 NUMERIC (15, 3) NULL,
    [free_sqr_floors]              VARCHAR (MAX)   NULL,
    [free_sqr_purpose]             VARCHAR (MAX)   NULL,
    [object_name]                  VARCHAR (252)   NULL,
    [object_note]                  VARCHAR (MAX)   NULL,
    [name]                         VARCHAR (252)   NULL,
    [purpose_group]                VARCHAR (160)   NULL,
    [purpose]                      VARCHAR (160)   NULL,
    [is_privat]                    NVARCHAR (3)    NOT NULL,
    [is_privat_int]                INT             NULL,
    [agreement_kind_id]            INT             NULL,
    [agreement_kind]               VARCHAR (64)    NULL,
    [agreement_date]               DATE            NULL,
    [agreement_date_year]          INT             NULL,
    [agreement_date_quarter]       INT             NULL,
    [agreement_num]                VARCHAR (18)    NULL,
    [agreement_num_int]            BIGINT          NULL,
    [floor_number]                 VARCHAR (100)   NULL,
    [cost_narah]                   NUMERIC (15, 3) NULL,
    [cost_payed]                   NUMERIC (15, 3) NULL,
    [cost_debt]                    NUMERIC (15, 3) NULL,
    [cost_agreement]               NUMERIC (15, 3) NULL,
    [cost_expert_1m]               NUMERIC (15, 3) NULL,
    [cost_expert_total]            NUMERIC (15, 3) NULL,
    [cost_expert_total_agr]        NUMERIC (15, 3) NULL,
    [debt_timespan]                VARCHAR (18)    NULL,
    [pidstava]                     VARCHAR (252)   NULL,
    [pidstava_date]                DATE            NULL,
    [pidstava_num]                 VARCHAR (18)    NULL,
    [pidstava_display]             VARCHAR (MAX)   NULL,
    [rent_start_date]              DATE            NULL,
    [rent_start_year]              INT             NULL,
    [rent_start_quarter]           INT             NULL,
    [rent_finish_date]             DATE            NULL,
    [rent_finish_year]             INT             NULL,
    [rent_finish_quarter]          INT             NULL,
    [rent_actual_finish_date]      DATE            NULL,
    [actual_finish_year]           INT             NULL,
    [actual_finish_quarter]        INT             NULL,
    [rent_rate_percent]            NUMERIC (15, 3) NULL,
    [rent_rate_uah]                NUMERIC (15, 3) NULL,
    [rent_square]                  NUMERIC (9, 2)  NULL,
    [rishennya_code]               INT             NULL,
    [num_akt]                      VARCHAR (18)    NULL,
    [date_akt]                     DATE            NULL,
    [num_bti]                      VARCHAR (18)    NULL,
    [date_bti]                     DATE            NULL,
    [modified_by]                  VARCHAR (128)   NULL,
    [modify_date]                  DATETIME        NULL,
    [is_subarenda_int]             INT             NULL,
    [is_subarenda]                 NVARCHAR (3)    NOT NULL,
    [payment_type]                 VARCHAR (64)    NULL,
    [agreement_active]             NVARCHAR (3)    NOT NULL,
    [agreement_active_int]         INT             NOT NULL,
    [is_deleted]                   INT             NULL,
    [balans_sqr_total]             NUMERIC (9, 2)  NULL,
    [balans_num_rent_agr]          INT             NULL,
    [balans_sqr_in_rent]           NUMERIC (9, 2)  NULL,
    [balans_org_ownership]         VARCHAR (40)    NULL,
    [balans_org_ownership_int]     INT             NULL,
    [balans_form_ownership]        VARCHAR (40)    NULL,
    [balans_form_ownership_int]    INT             NULL,
    [date_expert]                  DATE            NULL,
    [agreement_active_s]           VARCHAR (53)    NOT NULL,
    [payment_type_obj]             VARCHAR (100)   NULL,
    [rental_rate]                  NUMERIC (5, 1)  NULL,
    [invent_no_agr_obj]            VARCHAR (128)   NULL,
    [invent_no_balans]             VARCHAR (18)    NULL,
    [note_status_id]               INT             NULL,
    [id]                           INT             IDENTITY (1, 1) NOT NULL
);

