CREATE TABLE [dbo].[m_view_object_rights] (
    [transfer_id]                INT             NOT NULL,
    [building_id]                INT             NOT NULL,
    [district]                   VARCHAR (64)    NULL,
    [street_full_name]           VARCHAR (160)   NULL,
    [addr_nomer]                 VARCHAR (98)    NULL,
    [condition]                  VARCHAR (64)    NULL,
    [condition_int]              INT             NULL,
    [object_type]                VARCHAR (64)    NULL,
    [object_type_int]            INT             NULL,
    [object_kind]                VARCHAR (256)   NULL,
    [object_kind_int]            INT             NULL,
    [purpose_group]              VARCHAR (160)   NULL,
    [purpose_group_int]          INT             NULL,
    [purpose]                    VARCHAR (160)   NULL,
    [purpose_int]                INT             NULL,
    [org_from_id]                INT             NULL,
    [org_from_full_name]         VARCHAR (255)   NULL,
    [org_from_short_name]        VARCHAR (255)   NULL,
    [org_from_zkpo_code]         VARCHAR (16)    NULL,
    [org_from_industry]          VARCHAR (40)    NULL,
    [org_from_occupation]        VARCHAR (50)    NULL,
    [org_from_ownership]         VARCHAR (40)    NULL,
    [org_from_form_gosp]         VARCHAR (40)    NULL,
    [org_from_vedomstvo]         VARCHAR (255)   NULL,
    [org_from_sfera_upr_id]      INT             NULL,
    [org_from_form_ownership_id] INT             NULL,
    [org_from_district_id]       INT             NULL,
    [org_to_id]                  INT             NULL,
    [org_to_full_name]           VARCHAR (255)   NULL,
    [org_to_short_name]          VARCHAR (255)   NULL,
    [org_to_zkpo_code]           VARCHAR (16)    NULL,
    [org_to_industry]            VARCHAR (40)    NULL,
    [org_to_occupation]          VARCHAR (50)    NULL,
    [org_to_ownership]           VARCHAR (40)    NULL,
    [org_to_form_gosp]           VARCHAR (40)    NULL,
    [org_to_vedomstvo]           VARCHAR (255)   NULL,
    [org_to_sfera_upr_id]        INT             NULL,
    [org_to_form_ownership_id]   INT             NULL,
    [org_to_district_id]         INT             NULL,
    [right_id]                   INT             NULL,
    [right_name]                 VARCHAR (50)    NULL,
    [transfer_date]              DATE            NULL,
    [transfer_year]              INT             NULL,
    [transfer_quarter]           INT             NULL,
    [akt_id]                     INT             NULL,
    [akt_num]                    VARCHAR (20)    NULL,
    [akt_date]                   DATE            NULL,
    [akt_date_year]              INT             NULL,
    [akt_date_quarter]           INT             NULL,
    [akt_topic]                  VARCHAR (255)   NULL,
    [akt_search_name]            NVARCHAR (316)  NULL,
    [akt_text_exists]            INT             NULL,
    [rozp_doc_id]                INT             NULL,
    [rozp_doc_num]               VARCHAR (20)    NULL,
    [rozp_doc_date]              DATE            NULL,
    [rozp_doc_topic]             VARCHAR (255)   NULL,
    [rozp_doc_search_name]       NVARCHAR (316)  NULL,
    [rozp_text_exists]           INT             NULL,
    [modified_by]                VARCHAR (128)   NULL,
    [modify_date]                DATE            NULL,
    [name]                       VARCHAR (255)   NULL,
    [characteristic]             VARCHAR (MAX)   NULL,
    [misc_info]                  VARCHAR (MAX)   NULL,
    [sum_balans]                 NUMERIC (15, 3) NULL,
    [sum_zalishkova]             NUMERIC (15, 3) NULL,
    [sqr_transferred]            NUMERIC (10, 3) NULL,
    [len_transferred]            NUMERIC (9, 2)  NULL
);

