CREATE TABLE [dbo].[m_view_docs_objects_akts] (
    [document_id]      INT             NOT NULL,
    [doc_date]         DATE            NULL,
    [doc_date_year]    INT             NULL,
    [doc_date_quarter] INT             NULL,
    [doc_num]          VARCHAR (20)    NULL,
    [topic]            VARCHAR (255)   NULL,
    [doc_note]         VARCHAR (MAX)   NULL,
    [doc_kind]         VARCHAR (60)    NULL,
    [doc_is_rozp]      NVARCHAR (3)    NOT NULL,
    [general_kind]     VARCHAR (50)    NULL,
    [commission_name]  VARCHAR (40)    NULL,
    [doc_source]       VARCHAR (60)    NULL,
    [doc_state]        VARCHAR (60)    NULL,
    [search_name]      NVARCHAR (316)  NULL,
    [receive_date]     DATE            NULL,
    [summa]            NUMERIC (15, 3) NULL,
    [summa_zalishkova] NUMERIC (15, 3) NULL,
    [doc_text_exists]  INT             NULL,
    [link_id]          INT             NOT NULL,
    [building_id]      INT             NOT NULL,
    [district]         VARCHAR (64)    NULL,
    [street_full_name] VARCHAR (160)   NULL,
    [addr_nomer]       VARCHAR (98)    NULL,
    [obj_name]         VARCHAR (255)   NULL,
    [obj_description]  VARCHAR (100)   NULL,
    [obj_build_year]   INT             NULL,
    [obj_length]       NUMERIC (9, 2)  NULL,
    [object_note]      VARCHAR (MAX)   NULL,
    [cost_balans]      NUMERIC (15, 3) NULL,
    [cost_znos]        NUMERIC (15, 3) NULL,
    [cost_zalishkova]  NUMERIC (15, 3) NULL,
    [cost_expert]      NUMERIC (15, 3) NULL,
    [num_rooms]        INT             NULL,
    [num_floors]       INT             NULL,
    [obj_location]     VARCHAR (60)    NULL,
    [purpose_group]    VARCHAR (160)   NULL,
    [purpose]          VARCHAR (160)   NULL,
    [condition]        VARCHAR (64)    NULL,
    [object_kind]      VARCHAR (256)   NULL,
    [object_type]      VARCHAR (64)    NULL,
    [sqr_obj]          NUMERIC (9, 2)  NULL,
    [sqr_free]         NUMERIC (9, 2)  NULL,
    [sqr_habit]        NUMERIC (9, 2)  NULL,
    [sqr_non_habit]    NUMERIC (9, 2)  NULL,
    [form_ownership]   VARCHAR (40)    NULL,
    [pipe_diameter]    VARCHAR (20)    NULL,
    [pipe_material]    VARCHAR (20)    NULL,
    [akt_exists]       VARCHAR (3)     NOT NULL,
    [akt_id]           INT             NULL,
    [akt_num]          VARCHAR (20)    NULL,
    [akt_date]         DATE            NULL,
    [akt_date_year]    INT             NULL,
    [akt_date_quarter] INT             NULL,
    [akt_topic]        VARCHAR (255)   NULL,
    [akt_search_name]  NVARCHAR (316)  NULL,
    [akt_text_exists]  INT             NULL
);

