CREATE TABLE [dbo].[object_rights] (
    [id]               INT             IDENTITY (1, 1) NOT NULL,
    [building_id]      INT             NOT NULL,
    [org_from_id]      INT             NULL,
    [org_to_id]        INT             NULL,
    [right_id]         INT             NULL,
    [transfer_date]    DATE            NULL,
    [transfer_year]    AS              (datepart(year,[transfer_date])),
    [transfer_quarter] AS              (datepart(quarter,[transfer_date])),
    [akt_id]           INT             NULL,
    [rozp_id]          INT             NULL,
    [modified_by]      VARCHAR (128)   NULL,
    [modify_date]      DATE            NULL,
    [name]             VARCHAR (255)   NULL,
    [characteristic]   VARCHAR (MAX)   NULL,
    [misc_info]        VARCHAR (MAX)   NULL,
    [sum_balans]       NUMERIC (15, 3) NULL,
    [sum_zalishkova]   NUMERIC (15, 3) NULL,
    [sqr_transferred]  NUMERIC (9, 3)  NULL,
    [len_transferred]  NUMERIC (9, 2)  NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_obj_rights_akt_doc] FOREIGN KEY ([akt_id]) REFERENCES [dbo].[documents] ([id]),
    CONSTRAINT [fk_obj_rights_building] FOREIGN KEY ([building_id]) REFERENCES [dbo].[buildings] ([id]),
    CONSTRAINT [fk_obj_rights_org_from] FOREIGN KEY ([org_from_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_obj_rights_org_to] FOREIGN KEY ([org_to_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_obj_rights_right] FOREIGN KEY ([right_id]) REFERENCES [dbo].[dict_obj_rights] ([id]),
    CONSTRAINT [fk_obj_rights_rozp_doc] FOREIGN KEY ([rozp_id]) REFERENCES [dbo].[documents] ([id])
);

