CREATE TABLE [dbo].[OlapReportTotalYear] (
    [yy]      INT             NOT NULL,
    [rnum]    INT             NOT NULL,
    [nam]     NVARCHAR (4000) NULL,
    [zkpo]    NVARCHAR (4000) NULL,
    [sfera]   NVARCHAR (4000) NULL,
    [rayon]   NVARCHAR (4000) NULL,
    [ulic]    NVARCHAR (4000) NULL,
    [dom]     NVARCHAR (4000) NULL,
    [v1]      INT             NULL,
    [v2]      DECIMAL (18, 5) NULL,
    [v3]      DECIMAL (18, 5) NULL,
    [v4]      DECIMAL (18, 5) NULL,
    [v5]      INT             NULL,
    [v6]      DECIMAL (18, 5) NULL,
    [v7]      DECIMAL (18, 5) NULL,
    [v8]      INT             NULL,
    [v9]      INT             NULL,
    [v10]     DECIMAL (18, 5) NULL,
    [v11]     DECIMAL (18, 5) NULL,
    [v12]     DECIMAL (18, 5) NULL,
    [v13]     DECIMAL (18, 5) NULL,
    [v14]     DECIMAL (18, 5) NULL,
    [v15]     DECIMAL (18, 5) NULL,
    [v16]     DECIMAL (18, 5) NULL,
    [v17]     DECIMAL (18, 5) NULL,
    [v18]     DECIMAL (18, 5) NULL,
    [v19]     DECIMAL (18, 5) NULL,
    [v20]     DECIMAL (18, 5) NULL,
    [v21]     DECIMAL (18, 5) NULL,
    [v22]     DECIMAL (18, 5) NULL,
    [v23]     DECIMAL (18, 5) NULL,
    [v24]     DECIMAL (18, 5) NULL,
    [v25]     DECIMAL (18, 5) NULL,
    [vlastyp] VARCHAR (100)   NULL,
    PRIMARY KEY CLUSTERED ([yy] ASC, [rnum] ASC),
    UNIQUE NONCLUSTERED ([yy] ASC, [zkpo] ASC)
);

