CREATE TABLE [dbo].[organizations] (
    [id]                      INT             NOT NULL,
    [master_org_id]           INT             NULL,
    [last_state]              INT             NULL,
    [occupation_id]           INT             NULL,
    [status_id]               INT             NULL,
    [form_gosp_id]            INT             NULL,
    [form_ownership_id]       INT             NULL,
    [gosp_struct_id]          INT             NULL,
    [organ_id]                INT             NULL,
    [industry_id]             INT             NULL,
    [nomer_obj]               INT             NULL,
    [zkpo_code]               VARCHAR (16)    NULL,
    [addr_distr_old_id]       INT             NULL,
    [addr_distr_new_id]       INT             NULL,
    [addr_street_name]        VARCHAR (500)   NULL,
    [addr_street_id]          INT             NULL,
    [addr_nomer]              VARCHAR (30)    NULL,
    [addr_nomer2]             VARCHAR (24)    NULL,
    [addr_korpus]             VARCHAR (20)    NULL,
    [addr_zip_code]           VARCHAR (24)    NULL,
    [addr_misc]               VARCHAR (150)   NULL,
    [director_fio]            VARCHAR (70)    NULL,
    [director_phone]          VARCHAR (70)    NULL,
    [director_fio_kogo]       VARCHAR (70)    NULL,
    [director_title]          VARCHAR (500)   NULL,
    [director_title_kogo]     VARCHAR (70)    NULL,
    [director_doc]            VARCHAR (100)   NULL,
    [director_doc_kogo]       VARCHAR (100)   NULL,
    [director_email]          VARCHAR (100)   NULL,
    [buhgalter_fio]           VARCHAR (70)    NULL,
    [buhgalter_phone]         VARCHAR (24)    NULL,
    [buhgalter_email]         VARCHAR (100)   NULL,
    [num_buildings]           INT             NULL,
    [full_name]               VARCHAR (255)   NULL,
    [short_name]              VARCHAR (255)   NULL,
    [priznak_id]              INT             NULL,
    [title_form_id]           INT             NULL,
    [form_1nf_id]             INT             NULL,
    [vedomstvo_id]            INT             NULL,
    [title_id]                INT             NULL,
    [form_id]                 INT             NULL,
    [gosp_struct_type_id]     INT             NULL,
    [search_name]             VARCHAR (100)   NULL,
    [name_komu]               VARCHAR (150)   NULL,
    [fax]                     VARCHAR (24)    NULL,
    [registration_auth]       VARCHAR (100)   NULL,
    [registration_num]        VARCHAR (24)    NULL,
    [registration_date]       DATE            NULL,
    [registration_svidot]     VARCHAR (10)    NULL,
    [l_year]                  INT             NULL,
    [date_l_year]             DATE            NULL,
    [sqr_on_balance]          NUMERIC (15, 2) NULL,
    [sqr_manufact]            NUMERIC (15, 2) NULL,
    [sqr_non_manufact]        NUMERIC (15, 2) NULL,
    [sqr_free_for_rent]       NUMERIC (15, 2) NULL,
    [sqr_total]               NUMERIC (15, 2) NULL,
    [sqr_rented]              NUMERIC (15, 2) NULL,
    [sqr_privat]              NUMERIC (15, 2) NULL,
    [sqr_given_for_rent]      NUMERIC (15, 2) NULL,
    [sqr_znyata_z_balansu]    NUMERIC (15, 2) NULL,
    [sqr_prodaj]              NUMERIC (15, 2) NULL,
    [sqr_spisani_zneseni]     NUMERIC (15, 2) NULL,
    [sqr_peredana]            NUMERIC (15, 2) NULL,
    [num_objects]             INT             NULL,
    [kved_code]               VARCHAR (8)     NULL,
    [date_stat_spravka]       DATE            NULL,
    [koatuu]                  VARCHAR (16)    NULL,
    [modified_by]             VARCHAR (128)   NULL,
    [modify_date]             DATETIME        NULL,
    [share_type_id]           INT             NULL,
    [share]                   VARCHAR (50)    NULL,
    [bank_name]               VARCHAR (16)    NULL,
    [bank_mfo]                VARCHAR (200)   NULL,
    [is_deleted]              INT             CONSTRAINT [DF__organizat__is_de__767B1AC3] DEFAULT ((0)) NULL,
    [del_date]                DATE            NULL,
    [otdel_gukv_id]           INT             NULL,
    [arch_id]                 INT             NULL,
    [arch_flag]               INT             CONSTRAINT [DF__organizat__arch___776F3EFC] DEFAULT ((0)) NULL,
    [is_liquidated]           INT             CONSTRAINT [DF__organizat__is_li__78636335] DEFAULT ((0)) NULL,
    [liquidation_date]        INT             NULL,
    [pidp_rda]                INT             CONSTRAINT [DF__organizat__pidp___7957876E] DEFAULT ((0)) NULL,
    [is_arend]                INT             NULL,
    [beg_state_date]          DATE            NULL,
    [end_state_date]          DATE            NULL,
    [mayno_id]                INT             NULL,
    [contact_email]           VARCHAR (50)    NULL,
    [contact_posada_id]       INT             NULL,
    [nadhodjennya_id]         INT             NULL,
    [vibuttya_id]             INT             NULL,
    [privat_status_id]        INT             NULL,
    [cur_state_id]            INT             NULL,
    [sfera_upr_id]            INT             NULL,
    [plan_zone_id]            INT             NULL,
    [registr_org_id]          INT             NULL,
    [nadhodjennya_date]       DATE            NULL,
    [vibuttya_date]           DATE            NULL,
    [chastka]                 NUMERIC (15, 4) NULL,
    [registration_rish]       VARCHAR (10)    NULL,
    [registration_dov_date]   DATE            NULL,
    [registration_corp]       VARCHAR (10)    NULL,
    [strok_start_date]        DATE            NULL,
    [strok_end_date]          DATE            NULL,
    [stat_fond]               NUMERIC (15, 2) NULL,
    [size_plus]               VARCHAR (10)    NULL,
    [addr_zip_code_3]         INT             NULL,
    [old_industry_id]         INT             NULL,
    [old_occupation_id]       INT             NULL,
    [old_organ_id]            INT             NULL,
    [form_vlasn_vibuttya_id]  INT             NULL,
    [addr_city]               VARCHAR (100)   NULL,
    [addr_flat_num]           INT             NULL,
    [povnovajennia]           VARCHAR (100)   NULL,
    [povnov_osoba_fio]        VARCHAR (50)    NULL,
    [povnov_passp_seria]      VARCHAR (15)    NULL,
    [povnov_passp_num]        VARCHAR (15)    NULL,
    [povnov_passp_auth]       VARCHAR (160)   NULL,
    [povnov_passp_date]       DATE            NULL,
    [director_passp_seria]    VARCHAR (15)    NULL,
    [director_passp_num]      VARCHAR (15)    NULL,
    [director_passp_auth]     VARCHAR (160)   NULL,
    [director_passp_date]     DATE            NULL,
    [registration_svid_date]  DATE            NULL,
    [origin_db]               INT             CONSTRAINT [DF__organizat__origi__7A4BABA7] DEFAULT ((1)) NULL,
    [budg_payments_rate]      NUMERIC (5, 2)  NULL,
    [is_under_closing]        INT             NULL,
    [phys_addr_street_id]     INT             NULL,
    [phys_addr_district_id]   INT             NULL,
    [phys_addr_nomer]         VARCHAR (60)    NULL,
    [phys_addr_zip_code]      VARCHAR (24)    NULL,
    [phys_addr_misc]          VARCHAR (150)   NULL,
    [contribution_rate]       INT             NULL,
    [budget_narah_50_uah]     NUMERIC (15, 3) NULL,
    [budget_zvit_50_uah]      NUMERIC (15, 3) NULL,
    [budget_prev_50_uah]      NUMERIC (15, 3) NULL,
    [budget_debt_30_50_uah]   NUMERIC (15, 3) NULL,
    [is_special_organization] INT             NULL,
    [payment_budget_special]  NUMERIC (15, 3) NULL,
    [konkurs_payments]        NUMERIC (15, 3) NULL,
    [unknown_payments]        NUMERIC (15, 3) NULL,
    [unknown_payment_note]    VARCHAR (510)   NULL,
    [temp_org_kind_id]        INT             NULL,
    [isactive]                SMALLINT        DEFAULT ((0)) NOT NULL,
    [bank_rahunok]            VARCHAR (255)   NULL,
    [ouprav_id]               INT             NULL,
    [pravform_id]             INT             NULL,
    [planuvania_1]            NUMERIC (15, 3) NULL,
    [planuvania_2]            NUMERIC (15, 3) NULL,
    [planuvania_3]            NUMERIC (15, 3) NULL,
    [planuvania_4]            NUMERIC (15, 3) NULL,
    [planuvania_5]            NUMERIC (15, 3) NULL,
    [prozoro_title]           VARCHAR (500)   NULL,
    CONSTRAINT [PK__organiza__3213E83F7C33F419] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_organizations_cur_state] FOREIGN KEY ([cur_state_id]) REFERENCES [dbo].[dict_org_cur_state] ([id]),
    CONSTRAINT [fk_organizations_distr_new] FOREIGN KEY ([addr_distr_new_id]) REFERENCES [dbo].[dict_districts2] ([id]),
    CONSTRAINT [fk_organizations_distr_old] FOREIGN KEY ([addr_distr_old_id]) REFERENCES [dbo].[dict_districts] ([id]),
    CONSTRAINT [fk_organizations_form] FOREIGN KEY ([form_id]) REFERENCES [dbo].[dict_org_form] ([id]),
    CONSTRAINT [fk_organizations_form_1nf] FOREIGN KEY ([form_1nf_id]) REFERENCES [dbo].[dict_org_form_1nf] ([id]),
    CONSTRAINT [fk_organizations_form_gosp] FOREIGN KEY ([form_gosp_id]) REFERENCES [dbo].[dict_org_form_gosp] ([id]),
    CONSTRAINT [fk_organizations_form_vlasn_vibuttya] FOREIGN KEY ([form_vlasn_vibuttya_id]) REFERENCES [dbo].[dict_form_vlasn_vibuttya] ([id]),
    CONSTRAINT [fk_organizations_gosp_struct] FOREIGN KEY ([gosp_struct_id]) REFERENCES [dbo].[dict_org_gosp_struct] ([id]),
    CONSTRAINT [fk_organizations_gosp_struct_type] FOREIGN KEY ([gosp_struct_type_id]) REFERENCES [dbo].[dict_org_gosp_struct_type] ([id]),
    CONSTRAINT [fk_organizations_industry] FOREIGN KEY ([industry_id]) REFERENCES [dbo].[dict_org_industry] ([id]),
    CONSTRAINT [fk_organizations_mayno] FOREIGN KEY ([mayno_id]) REFERENCES [dbo].[dict_org_mayno] ([id]),
    CONSTRAINT [fk_organizations_nadhodzhennya] FOREIGN KEY ([nadhodjennya_id]) REFERENCES [dbo].[dict_org_nadhodjennya] ([id]),
    CONSTRAINT [fk_organizations_occupation] FOREIGN KEY ([occupation_id]) REFERENCES [dbo].[dict_org_occupation] ([id]),
    CONSTRAINT [fk_organizations_old_industry] FOREIGN KEY ([old_industry_id]) REFERENCES [dbo].[dict_org_old_industry] ([id]),
    CONSTRAINT [fk_organizations_old_organ] FOREIGN KEY ([old_organ_id]) REFERENCES [dbo].[dict_org_old_organ] ([id]),
    CONSTRAINT [fk_organizations_organ] FOREIGN KEY ([organ_id]) REFERENCES [dbo].[dict_org_organ] ([id]),
    CONSTRAINT [fk_organizations_otdel] FOREIGN KEY ([otdel_gukv_id]) REFERENCES [dbo].[dict_otdel_gukv] ([id]),
    CONSTRAINT [fk_organizations_ouprav] FOREIGN KEY ([ouprav_id]) REFERENCES [dbo].[dict_1nf_org_ouprav] ([id]),
    CONSTRAINT [fk_organizations_ownership] FOREIGN KEY ([form_ownership_id]) REFERENCES [dbo].[dict_org_ownership] ([id]),
    CONSTRAINT [fk_organizations_plan_zone] FOREIGN KEY ([plan_zone_id]) REFERENCES [dbo].[dict_org_plan_zone] ([id]),
    CONSTRAINT [fk_organizations_posada] FOREIGN KEY ([contact_posada_id]) REFERENCES [dbo].[dict_org_contact_posada] ([id]),
    CONSTRAINT [fk_organizations_pravform] FOREIGN KEY ([pravform_id]) REFERENCES [dbo].[dict_1nf_org_pravform] ([id]),
    CONSTRAINT [fk_organizations_privat_status] FOREIGN KEY ([privat_status_id]) REFERENCES [dbo].[dict_org_privat_status] ([id]),
    CONSTRAINT [fk_organizations_priznak] FOREIGN KEY ([priznak_id]) REFERENCES [dbo].[dict_org_priznak] ([id]),
    CONSTRAINT [fk_organizations_registr_org] FOREIGN KEY ([registr_org_id]) REFERENCES [dbo].[dict_org_registr_org] ([id]),
    CONSTRAINT [fk_organizations_sfera_upr] FOREIGN KEY ([sfera_upr_id]) REFERENCES [dbo].[dict_org_sfera_upr] ([id]),
    CONSTRAINT [fk_organizations_share_type] FOREIGN KEY ([share_type_id]) REFERENCES [dbo].[dict_org_share_type] ([id]),
    CONSTRAINT [fk_organizations_status] FOREIGN KEY ([status_id]) REFERENCES [dbo].[dict_org_status] ([id]),
    CONSTRAINT [fk_organizations_title] FOREIGN KEY ([title_id]) REFERENCES [dbo].[dict_org_title] ([id]),
    CONSTRAINT [fk_organizations_title_form] FOREIGN KEY ([title_form_id]) REFERENCES [dbo].[dict_org_title_form] ([id]),
    CONSTRAINT [fk_organizations_vedomstvo] FOREIGN KEY ([vedomstvo_id]) REFERENCES [dbo].[dict_org_vedomstvo] ([id]),
    CONSTRAINT [fk_organizations_vibuttya] FOREIGN KEY ([vibuttya_id]) REFERENCES [dbo].[dict_org_vibuttya] ([id])
);


GO
CREATE NONCLUSTERED INDEX [indx_organizations_zkpo]
    ON [dbo].[organizations]([zkpo_code] ASC);

