CREATE TABLE [dbo].[privatization] (
    [id]               INT             NOT NULL,
    [building_id]      INT             NOT NULL,
    [organization_id]  INT             NULL,
    [balans_id]        INT             NULL,
    [obj_group_id]     INT             NULL,
    [privat_kind_id]   INT             NULL,
    [privat_state_id]  INT             NULL,
    [sqr_total]        NUMERIC (9, 2)  NULL,
    [obj_name]         VARCHAR (100)   NULL,
    [complex_id]       INT             NULL,
    [object_kind_id]   INT             NULL,
    [object_type_id]   INT             NULL,
    [purpose_group_id] INT             NULL,
    [history_id]       INT             NULL,
    [obj_floor]        INT             NULL,
    [note]             VARCHAR (100)   NULL,
    [cost]             NUMERIC (15, 2) NULL,
    [cost_expert]      NUMERIC (15, 2) NULL,
    [expert_date]      DATE            NULL,
    [subordination_id] INT             NULL,
    [rishen_doc_id]    INT             NULL,
    [modified_by]      VARCHAR (128)   NULL,
    [modify_date]      DATE            NULL,
    [addr_street_name] VARCHAR (500)   NULL,
    [addr_number]      VARCHAR (18)    NULL,
    [addr_misc]        VARCHAR (30)    NULL,
    [addr_district_id] INT             NULL,
    [addr_zip_code]    VARCHAR (15)    NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_privatization_building] FOREIGN KEY ([building_id]) REFERENCES [dbo].[buildings] ([id]),
    CONSTRAINT [fk_privatization_complex] FOREIGN KEY ([complex_id]) REFERENCES [dbo].[dict_privat_complex] ([id]),
    CONSTRAINT [fk_privatization_district] FOREIGN KEY ([addr_district_id]) REFERENCES [dbo].[dict_districts2] ([id]),
    CONSTRAINT [fk_privatization_history] FOREIGN KEY ([history_id]) REFERENCES [dbo].[dict_history] ([id]),
    CONSTRAINT [fk_privatization_obj_group] FOREIGN KEY ([obj_group_id]) REFERENCES [dbo].[dict_privat_obj_group] ([id]),
    CONSTRAINT [fk_privatization_obj_kind] FOREIGN KEY ([object_kind_id]) REFERENCES [dbo].[dict_object_kind_old] ([id]),
    CONSTRAINT [fk_privatization_obj_type] FOREIGN KEY ([object_type_id]) REFERENCES [dbo].[dict_object_type] ([id]),
    CONSTRAINT [fk_privatization_org] FOREIGN KEY ([organization_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_privatization_privat_kind] FOREIGN KEY ([privat_kind_id]) REFERENCES [dbo].[dict_privat_kind] ([id]),
    CONSTRAINT [fk_privatization_privat_state] FOREIGN KEY ([privat_state_id]) REFERENCES [dbo].[dict_privat_state] ([id]),
    CONSTRAINT [fk_privatization_purpose_group] FOREIGN KEY ([purpose_group_id]) REFERENCES [dbo].[dict_balans_purpose_group] ([id]),
    CONSTRAINT [fk_privatization_subordination] FOREIGN KEY ([subordination_id]) REFERENCES [dbo].[dict_privat_subordination] ([id])
);

