CREATE TABLE [dbo].[rent_payment_debt] (
    [id]                    INT             IDENTITY (1, 1) NOT NULL,
    [rent_payment_id]       INT             NULL,
    [rent_renter_org_id]    INT             NULL,
    [rent_period_id]        INT             NULL,
    [giver_organization_id] INT             NULL,
    [debt_total]            NUMERIC (15, 3) NULL,
    [debt_3_month]          NUMERIC (15, 3) NULL,
    [debt_12_month]         NUMERIC (15, 3) NULL,
    [debt_3_years]          NUMERIC (15, 3) NULL,
    [debt_over_3_years]     NUMERIC (15, 3) NULL,
    [debt_spysano]          NUMERIC (15, 3) NULL,
    [num_zahodiv_total]     INT             DEFAULT ((0)) NULL,
    [num_zahodiv_zvit]      INT             NULL,
    [num_pozov_total]       INT             DEFAULT ((0)) NULL,
    [num_pozov_zvit]        INT             NULL,
    [num_pozov_zadov_total] INT             DEFAULT ((0)) NULL,
    [num_pozov_zadov_zvit]  INT             NULL,
    [num_pozov_vikon_total] INT             NULL,
    [num_pozov_vikon_zvit]  INT             NULL,
    [debt_pogasheno_total]  NUMERIC (15, 3) NULL,
    [debt_pogasheno_zvit]   NUMERIC (15, 3) NULL,
    [agreement_flag]        INT             DEFAULT ((0)) NULL,
    [debt_v_mezhah_vitrat]  NUMERIC (15, 3) NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_payment_debt_org_giver] FOREIGN KEY ([giver_organization_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_payment_debt_payment] FOREIGN KEY ([rent_payment_id]) REFERENCES [dbo].[rent_payment] ([id]),
    CONSTRAINT [fk_payment_debt_period] FOREIGN KEY ([rent_period_id]) REFERENCES [dbo].[dict_rent_period] ([id]),
    CONSTRAINT [fk_payment_debt_renter] FOREIGN KEY ([rent_renter_org_id]) REFERENCES [dbo].[rent_renter_org] ([id])
);

