CREATE TABLE [dbo].[rent_payment] (
    [id]                      INT             NOT NULL,
    [org_balans_id]           INT             NULL,
    [rent_period_id]          INT             NULL,
    [sqr_balans]              NUMERIC (15, 3) NULL,
    [payment_zvit_uah]        NUMERIC (15, 3) NULL,
    [received_zvit_uah]       NUMERIC (15, 3) NULL,
    [received_nar_zvit_uah]   NUMERIC (15, 3) NULL,
    [debt_total_uah]          NUMERIC (15, 3) NULL,
    [debt_zvit_uah]           NUMERIC (15, 3) NULL,
    [budget_narah_50_uah]     NUMERIC (15, 3) NULL,
    [budget_zvit_50_uah]      NUMERIC (15, 3) NULL,
    [budget_prev_50_uah]      NUMERIC (15, 3) NULL,
    [budget_debt_50_uah]      NUMERIC (15, 3) NULL,
    [budget_debt_30_50_uah]   NUMERIC (15, 3) NULL,
    [sqr_cmk]                 NUMERIC (15, 3) NULL,
    [budget_narah_50_cmk_uah] NUMERIC (15, 3) NULL,
    [budget_zvit_50_cmk_uah]  NUMERIC (15, 3) NULL,
    [budget_debt_50_cmk_uah]  NUMERIC (15, 3) NULL,
    [budget_zvit_50_in_uah]   NUMERIC (15, 3) NULL,
    [zkpo_code]               VARCHAR (255)   NULL,
    [modify_date]             DATE            NULL,
    [modified_by]             VARCHAR (255)   NULL,
    [email]                   VARCHAR (255)   NULL,
    [phone]                   VARCHAR (25)    NULL,
    [responsible_fio]         VARCHAR (255)   NULL,
    [director_fio]            VARCHAR (255)   NULL,
    [buhgalter_fio]           VARCHAR (255)   NULL,
    [num_agreements]          INT             NULL,
    [num_renters]             INT             NULL,
    [debt_v_mezhah_vitrat]    NUMERIC (15, 3) NULL,
    [budget_zvit_50_old]      NUMERIC (15, 3) DEFAULT ((0)) NULL,
    [post_address]            VARCHAR (512)   NULL,
    [pererahunok_50_b]        NUMERIC (15, 3) NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_rent_payment_org_balans] FOREIGN KEY ([org_balans_id]) REFERENCES [dbo].[organizations] ([id]),
    CONSTRAINT [fk_rent_payment_period] FOREIGN KEY ([rent_period_id]) REFERENCES [dbo].[dict_rent_period] ([id])
);

