CREATE TABLE [dbo].[rent_object] (
    [id]               INT             IDENTITY (1, 1) NOT NULL,
    [building_id]      INT             NULL,
    [rent_payment_id]  INT             NULL,
    [rent_period_id]   INT             NULL,
    [addr_street]      VARCHAR (255)   NULL,
    [addr_street_type] VARCHAR (64)    NULL,
    [addr_num]         VARCHAR (255)   NULL,
    [sqr_total]        NUMERIC (15, 3) NULL,
    [sqr_rented]       NUMERIC (15, 3) NULL,
    [sqr_free]         NUMERIC (15, 3) NULL,
    [sqr_korysna]      NUMERIC (15, 3) NULL,
    [sqr_mzk]          NUMERIC (15, 3) NULL,
    [floors]           VARCHAR (255)   NULL,
    [tech_state_id]    INT             NULL,
    [is_energo]        INT             NULL,
    [is_vodo]          INT             NULL,
    [is_teplo]         INT             NULL,
    [district_id]      INT             NULL,
    [purpose]          VARCHAR (255)   NULL,
    [rent_note_id]     INT             NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [fk_rent_object_building] FOREIGN KEY ([building_id]) REFERENCES [dbo].[buildings] ([id]),
    CONSTRAINT [fk_rent_object_district] FOREIGN KEY ([district_id]) REFERENCES [dbo].[dict_districts2] ([id]),
    CONSTRAINT [fk_rent_object_note] FOREIGN KEY ([rent_note_id]) REFERENCES [dbo].[dict_rent_note] ([id]),
    CONSTRAINT [fk_rent_object_payment] FOREIGN KEY ([rent_payment_id]) REFERENCES [dbo].[rent_payment] ([id]),
    CONSTRAINT [fk_rent_object_period] FOREIGN KEY ([rent_period_id]) REFERENCES [dbo].[dict_rent_period] ([id])
);

