CREATE TABLE [dbo].[reports1nf_arenda_notes] (
    [id]                  INT             IDENTITY (1, 1) NOT NULL,
    [arenda_id]           INT             NULL,
    [purpose_group_id]    INT             NULL,
    [purpose_id]          INT             NULL,
    [purpose_str]         VARCHAR (252)   NULL,
    [rent_square]         NUMERIC (9, 2)  NULL,
    [modify_date]         DATE            NULL,
    [modified_by]         VARCHAR (128)   NULL,
    [note]                VARCHAR (252)   NULL,
    [rent_rate]           NUMERIC (15, 3) NULL,
    [rent_rate_uah]       NUMERIC (15, 3) NULL,
    [cost_narah]          NUMERIC (15, 3) NULL,
    [cost_agreement]      NUMERIC (15, 3) NULL,
    [is_deleted]          INT             NULL,
    [del_date]            DATE            NULL,
    [cost_expert_total]   NUMERIC (15, 3) NULL,
    [date_expert]         DATE            NULL,
    [payment_type_id]     INT             NULL,
    [invent_no]           VARCHAR (128)   NULL,
    [note_status_id]      INT             NULL,
    [report_id]           INT             NOT NULL,
    [zapezh_deposit]      NUMERIC (15, 3) NULL,
    [ref_balans_id]       INT             NULL,
    [factich_vikorist_id] INT             NULL,
    PRIMARY KEY CLUSTERED ([report_id] ASC, [id] ASC),
    CONSTRAINT [FK_reports1nf_arenda_notes_reports1nf] FOREIGN KEY ([report_id]) REFERENCES [dbo].[reports1nf] ([id]) ON DELETE CASCADE ON UPDATE CASCADE
);

