CREATE TABLE [dbo].[reports1nf_arenda_dogcontinue] (
    [id]                        INT             IDENTITY (1, 1) NOT NULL,
    [arenda_id]                 INT             NOT NULL,
    [total_free_sqr]            NUMERIC (9, 2)  CONSTRAINT [DF_reports1nf_arenda_dogcontinue_total_free_sqrr] DEFAULT ((0)) NOT NULL,
    [free_sqr_condition_id]     INT             NOT NULL,
    [floor]                     VARCHAR (128)   CONSTRAINT [DF_reports1nf_arenda_dogcontinue_floor] DEFAULT ((0)) NULL,
    [possible_using]            VARCHAR (1000)  NULL,
    [water]                     BIT             CONSTRAINT [DF_reports1nf_arenda_dogcontinue_water] DEFAULT ((0)) NOT NULL,
    [heating]                   BIT             CONSTRAINT [DF_reports1nf_arenda_dogcontinue_heating] DEFAULT ((0)) NOT NULL,
    [power]                     BIT             CONSTRAINT [DF_reports1nf_arenda_dogcontinue_power] DEFAULT ((0)) NOT NULL,
    [gas]                       BIT             NOT NULL,
    [modify_date]               DATETIME        NOT NULL,
    [modified_by]               VARCHAR (128)   NOT NULL,
    [report_id]                 INT             NOT NULL,
    [free_sqr_korysna]          NUMERIC (9, 2)  NULL,
    [note]                      VARCHAR (MAX)   NULL,
    [is_solution]               BIT             NULL,
    [initiator]                 VARCHAR (1000)  NULL,
    [zgoda_control_id]          INT             NULL,
    [zgoda_renter_id]           INT             NULL,
    [komis_protocol]            VARCHAR (255)   NULL,
    [geodata_map_url]           VARCHAR (8000)  NULL,
    [geodata_map_points]        VARCHAR (8000)  NULL,
    [current_stage_id]          INT             NULL,
    [current_stage_docdate]     DATETIME        NULL,
    [current_stage_docnum]      VARCHAR (1000)  NULL,
    [period_used_id]            INT             NULL,
    [using_possible_id]         INT             NULL,
    [invest_solution_id]        INT             NULL,
    [modify_date2]              DATETIME        NULL,
    [modified_by2]              VARCHAR (128)   NULL,
    [freecycle_step_dict_id]    INT             NULL,
    [is_included]               BIT             DEFAULT ((1)) NOT NULL,
    [include_in_perelik]        VARCHAR (1000)  NULL,
    [zal_balans_vartist]        NUMERIC (15, 3) NULL,
    [perv_balans_vartist]       NUMERIC (15, 3) NULL,
    [punkt_metod_rozrahunok]    VARCHAR (1000)  NULL,
    [prop_srok_orands]          INT             NULL,
    [nomer_derzh_reestr_neruh]  VARCHAR (1000)  NULL,
    [reenum_derzh_reestr_neruh] VARCHAR (1000)  NULL,
    [info_priznach_nouse]       VARCHAR (1000)  NULL,
    [info_rahunok_postach]      VARCHAR (1000)  NULL,
    [power_text]                VARCHAR (1000)  NULL,
    [priznach_before]           VARCHAR (1000)  NULL,
    [period_nouse]              VARCHAR (1000)  NULL,
    [osoba_use_before]          VARCHAR (1000)  NULL,
    [power_info_id]             INT             NULL,
    [free_object_type_id]       INT             NULL,
    [prozoro_number]            VARCHAR (1000)  NULL,
    [has_perevazh_pravo]        BIT             NULL,
    [polipshanya_vartist]       NUMERIC (15, 2) NULL,
    [polipshanya_finish_date]   DATETIME        NULL,
    [orend_plat_last_month]     NUMERIC (15, 3) NULL,
    [orend_plat_borg]           NUMERIC (15, 3) NULL,
    [stanom_na]                 DATETIME        NULL,
    [primitki]                  VARCHAR (1000)  NULL,
    [zalbalansvartist_date]     DATETIME        NULL,
    [osoba_oznakoml]            VARCHAR (1000)  NULL,
    [rozmir_vidshkoduv]         NUMERIC (15, 3) NULL,
    [may_pravo_prodov]          INT             NULL,
    [building_type]             VARCHAR (4000)  NULL,
    [category]                  VARCHAR (4000)  NULL,
    [rental_rate_percent]       VARCHAR (200)   NULL,
    [rental_type]               VARCHAR (4000)  NULL,
    [rental_term]               VARCHAR (4000)  NULL,
    [commission_note]           VARCHAR (4000)  NULL,
    [additional_info]           VARCHAR (4000)  NULL,
    [speaker_name]              VARCHAR (4000)  NULL,
    [incoming_doc_num]          VARCHAR (4000)  NULL,
    [incoming_doc_date]         DATETIME        NULL,
    [commission_result]         VARCHAR (100)   NULL,
    [protocol_question_num]     INT             NULL,
    [outgoing_doc_num]          VARCHAR (100)   NULL,
    [outgoing_doc_date]         DATETIME        NULL,
    [slukhali_text]             VARCHAR (MAX)   NULL,
    [virishyly_text]            VARCHAR (MAX)   NULL,
    [golosovanie]               VARCHAR (MAX)   NULL,
    [commission_id]             INT             NULL,
    [orend_plat_dogovor]        NUMERIC (15, 3) NULL,
    CONSTRAINT [PK_Treports1nf_arenda_dogcontinue] PRIMARY KEY CLUSTERED ([id] ASC),
    FOREIGN KEY ([current_stage_id]) REFERENCES [dbo].[dict_free_square_stage] ([id]),
    FOREIGN KEY ([free_object_type_id]) REFERENCES [dbo].[dict_free_object_type] ([id]),
    FOREIGN KEY ([invest_solution_id]) REFERENCES [dbo].[dict_1nf_invest_solution] ([id]),
    FOREIGN KEY ([may_pravo_prodov]) REFERENCES [dbo].[dict_may_pravo_prodov] ([id]),
    FOREIGN KEY ([period_used_id]) REFERENCES [dbo].[dict_1nf_period_used] ([id]),
    FOREIGN KEY ([power_info_id]) REFERENCES [dbo].[dict_1nf_power_info] ([id]),
    CONSTRAINT [FK__reports1n__using__62829FFE] FOREIGN KEY ([using_possible_id]) REFERENCES [dbo].[dict_rental_rate] ([id]),
    CONSTRAINT [FK__reports1nf_arend__5BD5A26F] FOREIGN KEY ([report_id], [arenda_id]) REFERENCES [dbo].[reports1nf_arenda] ([report_id], [id]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [fk__reports1nf_arenda_dogcontinue__freecycle_step_dict_id] FOREIGN KEY ([freecycle_step_dict_id]) REFERENCES [dbo].[dogcontinue_proc_step_dict] ([step_id]),
    CONSTRAINT [FK_reports1nf_arenda_dogcontinue_dogcontinue_commission] FOREIGN KEY ([commission_id]) REFERENCES [dbo].[dogcontinue_commission] ([id])
);

