CREATE TABLE [dbo].[reptab_RentAgreements] (
    [arenda_id]                    INT             NOT NULL,
    [building_id]                  INT             NULL,
    [balans_id]                    INT             NULL,
    [org_balans_id]                INT             NULL,
    [org_balans_full_name]         VARCHAR (4000)  NULL,
    [org_balans_short_name]        VARCHAR (4000)  NULL,
    [org_balans_zkpo]              VARCHAR (4000)  NULL,
    [org_balans_industry]          VARCHAR (4000)  NULL,
    [org_balans_occupation]        VARCHAR (4000)  NULL,
    [org_balans_vedomstvo]         VARCHAR (4000)  NULL,
    [org_balans_org_form]          VARCHAR (4000)  NULL,
    [org_balans_sfera_upr_id]      INT             NULL,
    [org_balans_form_ownership_id] INT             NULL,
    [org_balans_form_ownership]    VARCHAR (4000)  NULL,
    [org_balans_district_id]       INT             NULL,
    [org_renter_id]                INT             NULL,
    [org_renter_full_name]         VARCHAR (4000)  NULL,
    [org_renter_short_name]        VARCHAR (4000)  NULL,
    [org_renter_zkpo]              VARCHAR (4000)  NULL,
    [org_renter_industry]          VARCHAR (4000)  NULL,
    [org_renter_occupation]        VARCHAR (4000)  NULL,
    [org_renter_vedomstvo]         VARCHAR (4000)  NULL,
    [org_renter_director_fio]      VARCHAR (4000)  NULL,
    [org_renter_director_phone]    VARCHAR (4000)  NULL,
    [org_renter_form_of_ownership] VARCHAR (4000)  NULL,
    [org_renter_org_form]          VARCHAR (4000)  NULL,
    [org_renter_sfera_upr_id]      INT             NULL,
    [org_renter_form_ownership_id] INT             NULL,
    [org_renter_district_id]       INT             NULL,
    [org_giver_id]                 INT             NULL,
    [org_giver_full_name]          VARCHAR (4000)  NULL,
    [org_giver_short_name]         VARCHAR (4000)  NULL,
    [org_giver_zkpo]               VARCHAR (4000)  NULL,
    [org_giver_industry]           VARCHAR (4000)  NULL,
    [org_giver_occupation]         VARCHAR (4000)  NULL,
    [org_giver_vedomstvo]          VARCHAR (4000)  NULL,
    [org_giver_org_form]           VARCHAR (4000)  NULL,
    [org_giver_sfera_upr_id]       INT             NULL,
    [org_giver_form_ownership_id]  INT             NULL,
    [org_giver_district_id]        INT             NULL,
    [district]                     VARCHAR (4000)  NULL,
    [street_full_name]             VARCHAR (4000)  NULL,
    [addr_nomer]                   VARCHAR (4000)  NULL,
    [is_in_privat]                 NVARCHAR (3)    NULL,
    [sqr_free_total]               NUMERIC (15, 3) NULL,
    [sqr_free_korysna]             NUMERIC (15, 3) NULL,
    [sqr_free_mzk]                 NUMERIC (15, 3) NULL,
    [free_sqr_floors]              VARCHAR (MAX)   NULL,
    [free_sqr_purpose]             VARCHAR (MAX)   NULL,
    [object_name]                  VARCHAR (4000)  NULL,
    [object_note]                  VARCHAR (MAX)   NULL,
    [name]                         VARCHAR (4000)  NULL,
    [purpose_group]                VARCHAR (4000)  NULL,
    [purpose]                      VARCHAR (4000)  NULL,
    [is_privat]                    NVARCHAR (3)    NOT NULL,
    [is_privat_int]                INT             NULL,
    [agreement_kind_id]            INT             NULL,
    [agreement_kind]               VARCHAR (4000)  NULL,
    [agreement_date]               DATE            NULL,
    [agreement_date_year]          INT             NULL,
    [agreement_date_quarter]       INT             NULL,
    [agreement_num]                VARCHAR (4000)  NULL,
    [agreement_num_int]            BIGINT          NULL,
    [agreement_state]              INT             NULL,
    [floor_number]                 VARCHAR (4000)  NULL,
    [cost_narah]                   NUMERIC (15, 3) NULL,
    [cost_payed]                   NUMERIC (15, 3) NULL,
    [cost_debt]                    NUMERIC (15, 3) NULL,
    [cost_agreement]               NUMERIC (15, 3) NULL,
    [cost_expert_1m]               NUMERIC (15, 3) NULL,
    [cost_expert_total]            NUMERIC (15, 3) NULL,
    [debt_timespan]                VARCHAR (4000)  NULL,
    [pidstava]                     VARCHAR (4000)  NULL,
    [pidstava_date]                DATE            NULL,
    [pidstava_num]                 VARCHAR (4000)  NULL,
    [pidstava_display]             VARCHAR (MAX)   NULL,
    [rent_start_date]              DATE            NULL,
    [rent_start_year]              INT             NULL,
    [rent_start_quarter]           INT             NULL,
    [rent_finish_date]             DATE            NULL,
    [rent_finish_year]             INT             NULL,
    [rent_finish_quarter]          INT             NULL,
    [rent_actual_finish_date]      DATE            NULL,
    [actual_finish_year]           INT             NULL,
    [actual_finish_quarter]        INT             NULL,
    [rent_rate_percent]            NUMERIC (15, 3) NULL,
    [rent_rate_uah]                NUMERIC (15, 3) NULL,
    [rent_square]                  NUMERIC (9, 2)  NULL,
    [rishennya_code]               INT             NULL,
    [num_akt]                      VARCHAR (4000)  NULL,
    [date_akt]                     DATE            NULL,
    [num_bti]                      VARCHAR (4000)  NULL,
    [date_bti]                     DATE            NULL,
    [modified_by]                  VARCHAR (4000)  NULL,
    [modify_date]                  DATETIME        NULL,
    [is_subarenda_int]             INT             NULL,
    [is_subarenda]                 NVARCHAR (3)    NOT NULL,
    [payment_type]                 VARCHAR (4000)  NULL,
    [agreement_active]             NVARCHAR (3)    NOT NULL,
    [agreement_active_int]         INT             NOT NULL,
    [is_deleted]                   INT             NULL,
    [balans_sqr_total]             NUMERIC (38, 2) NULL,
    [balans_num_rent_agr]          INT             NULL,
    [balans_sqr_in_rent]           NUMERIC (38, 2) NULL,
    [balans_org_ownership]         VARCHAR (4000)  NULL,
    [balans_org_ownership_int]     INT             NULL,
    [balans_form_ownership]        VARCHAR (4000)  NULL,
    [balans_form_ownership_int]    INT             NULL,
    [date_expert]                  DATE            NULL,
    [form_gosp]                    VARCHAR (4000)  NULL,
    [agreement_active_s]           VARCHAR (4000)  NOT NULL,
    [n_cost_narah]                 DECIMAL (10, 2) NULL,
    [n_rent_rate]                  NUMERIC (38, 3) NULL,
    [n_rent_rate_uah]              NUMERIC (38, 3) NULL,
    [n_cost_expert_total]          NUMERIC (38, 3) NULL,
    [n_cost_agreement]             NUMERIC (38, 3) NULL,
    [n_rent_square]                NUMERIC (38, 2) NULL,
    [cost_agreement_max]           NUMERIC (15, 3) NULL,
    [cost_narah_max]               NUMERIC (15, 3) NULL,
    [contribution_rate]            INT             NULL,
    [payment_narah]                NUMERIC (15, 3) NULL,
    [last_year_saldo]              NUMERIC (15, 3) NULL,
    [payment_received]             NUMERIC (15, 3) NULL,
    [payment_nar_zvit]             NUMERIC (15, 3) NULL,
    [old_debts_payed]              NUMERIC (15, 3) NULL,
    [return_orend_payed]           NUMERIC (15, 3) NULL,
    [return_all_orend_payed]       NUMERIC (15, 3) NULL,
    [use_calc_debt]                INT             NULL,
    [debt_total]                   NUMERIC (15, 3) NULL,
    [debt_zvit]                    NUMERIC (15, 3) NULL,
    [debt_3_month]                 NUMERIC (15, 3) NULL,
    [debt_12_month]                NUMERIC (15, 3) NULL,
    [debt_3_years]                 NUMERIC (15, 3) NULL,
    [debt_over_3_years]            NUMERIC (15, 3) NULL,
    [debt_v_mezhah_vitrat]         NUMERIC (15, 3) NULL,
    [debt_spysano]                 NUMERIC (15, 3) NULL,
    [num_zahodiv_total]            INT             NULL,
    [num_zahodiv_zvit]             INT             NULL,
    [avance_plat]                  NUMERIC (15, 3) NULL,
    [is_discount]                  INT             NULL,
    [zvilneno_percent]             NUMERIC (15, 3) NULL,
    [zvilneno_date1]               DATETIME        NULL,
    [zvilneno_date2]               DATETIME        NULL,
    [povidoleno1_date]             DATETIME        NULL,
    [povidoleno1_num]              VARCHAR (4000)  NULL,
    [povidoleno2_date]             DATETIME        NULL,
    [povidoleno2_num]              VARCHAR (4000)  NULL,
    [povidoleno3_date]             DATETIME        NULL,
    [povidoleno3_num]              VARCHAR (4000)  NULL,
    [povidoleno4_date]             DATETIME        NULL,
    [povidoleno4_num]              VARCHAR (4000)  NULL,
    [zvilbykmp_percent]            NUMERIC (15, 3) NULL,
    [zvilbykmp_date1]              DATETIME        NULL,
    [zvilbykmp_date2]              DATETIME        NULL,
    [stanjuro]                     VARCHAR (4000)  NULL,
    [insurance_sum]                NUMERIC (15, 2) NULL,
    [insurance_start]              DATE            NULL,
    [insurance_end]                DATE            NULL,
    [org_renter_director_email]    VARCHAR (4000)  NULL,
    [sphera_dialnosti]             VARCHAR (4000)  NOT NULL,
    [priznachennya]                VARCHAR (4000)  NULL,
    [ex_reports1nf_arenda]         INT             NOT NULL,
    [arenda_report_id]             INT             NULL,
    [is_dpz_object]                INT             NOT NULL,
    [count_dogovor_objects]        INT             NULL,
    [has_reports1nf_photos]        INT             NOT NULL,
    [old_organ]                    VARCHAR (1000)  NULL,
    [num_pozov_total]              INT             NULL,
    [num_pozov_zadov_total]        INT             NULL,
    [num_pozov_vikon_total]        INT             NULL,
    [list_dogovor_objects]         VARCHAR (4000)  NULL,
    [prozoro_number]               VARCHAR (4000)  NULL,
    [method_calc_name]             VARCHAR (4000)  NULL,
    [base_month]                   DATE            NULL,
    PRIMARY KEY CLUSTERED ([arenda_id] ASC)
);

