CREATE TABLE [dbo].[zzz20210518_backup_reports1nf_balans_free_square] (
    [id]                        INT             IDENTITY (1, 1) NOT NULL,
    [balans_id]                 INT             NOT NULL,
    [total_free_sqr]            NUMERIC (9, 2)  NOT NULL,
    [free_sqr_condition_id]     INT             NOT NULL,
    [floor]                     VARCHAR (128)   NULL,
    [possible_using]            VARCHAR (1000)  NULL,
    [water]                     BIT             NOT NULL,
    [heating]                   BIT             NOT NULL,
    [power]                     BIT             NOT NULL,
    [gas]                       BIT             NOT NULL,
    [modify_date]               DATETIME        NOT NULL,
    [modified_by]               VARCHAR (128)   NOT NULL,
    [report_id]                 INT             NOT NULL,
    [free_sqr_korysna]          NUMERIC (9, 2)  NULL,
    [note]                      VARCHAR (MAX)   NULL,
    [is_solution]               BIT             NULL,
    [initiator]                 VARCHAR (1000)  NULL,
    [zgoda_control_id]          INT             NULL,
    [zgoda_renter_id]           INT             NULL,
    [komis_protocol]            VARCHAR (255)   NULL,
    [geodata_map_url]           VARCHAR (8000)  NULL,
    [geodata_map_points]        VARCHAR (8000)  NULL,
    [current_stage_id]          INT             NULL,
    [current_stage_docdate]     DATETIME        NULL,
    [current_stage_docnum]      VARCHAR (1000)  NULL,
    [period_used_id]            INT             NULL,
    [using_possible_id]         INT             NULL,
    [invest_solution_id]        INT             NULL,
    [modify_date2]              DATETIME        NULL,
    [modified_by2]              VARCHAR (128)   NULL,
    [freecycle_step_dict_id]    INT             NULL,
    [is_included]               BIT             NOT NULL,
    [include_in_perelik]        VARCHAR (1000)  NULL,
    [zal_balans_vartist]        NUMERIC (15, 3) NULL,
    [perv_balans_vartist]       NUMERIC (15, 3) NULL,
    [punkt_metod_rozrahunok]    VARCHAR (1000)  NULL,
    [prop_srok_orands]          INT             NULL,
    [nomer_derzh_reestr_neruh]  VARCHAR (1000)  NULL,
    [reenum_derzh_reestr_neruh] VARCHAR (1000)  NULL,
    [info_priznach_nouse]       VARCHAR (1000)  NULL,
    [info_rahunok_postach]      VARCHAR (1000)  NULL,
    [power_text]                VARCHAR (1000)  NULL,
    [priznach_before]           VARCHAR (1000)  NULL,
    [period_nouse]              VARCHAR (1000)  NULL,
    [osoba_use_before]          VARCHAR (1000)  NULL,
    [power_info_id]             INT             NULL,
    [free_object_type_id]       INT             NULL,
    [prozoro_number]            VARCHAR (1000)  NULL,
    [primitki]                  VARCHAR (1000)  NULL,
    [zalbalansvartist_date]     DATETIME        NULL,
    [osoba_oznakoml]            VARCHAR (1000)  NULL
);

