CREATE TABLE [dbo].[zzzz20220109_backup__object_rights_building_docs] (
    [id]                  INT             IDENTITY (1, 1) NOT NULL,
    [building_id]         INT             NOT NULL,
    [document_id]         INT             NOT NULL,
    [obj_name]            VARCHAR (255)   NULL,
    [obj_description]     VARCHAR (100)   NULL,
    [obj_build_year]      INT             NULL,
    [obj_expl_enter_year] INT             NULL,
    [obj_length]          NUMERIC (9, 2)  NULL,
    [note]                VARCHAR (MAX)   NULL,
    [cost_balans]         NUMERIC (15, 3) NULL,
    [cost_znos]           NUMERIC (15, 3) NULL,
    [cost_zalishkova]     NUMERIC (15, 3) NULL,
    [num_rooms]           INT             NULL,
    [num_floors]          INT             NULL,
    [obj_location]        VARCHAR (60)    NULL,
    [purpose_group_id]    INT             NULL,
    [purpose_id]          INT             NULL,
    [tech_condition_id]   INT             NULL,
    [object_kind_id]      INT             NULL,
    [object_type_id]      INT             NULL,
    [sqr_obj]             NUMERIC (9, 2)  NULL,
    [sqr_free]            NUMERIC (9, 2)  NULL,
    [sqr_habit]           NUMERIC (9, 2)  NULL,
    [sqr_non_habit]       NUMERIC (9, 2)  NULL,
    [modified_by]         VARCHAR (128)   NULL,
    [modify_date]         DATE            NULL,
    [doc_pos]             VARCHAR (12)    NULL,
    [pipe_diameter]       VARCHAR (20)    NULL,
    [pipe_material]       VARCHAR (20)    NULL
);

