CREATE TABLE [dbo].[zzzz20220109_backup__expert_note] (
    [id]                 INT             NOT NULL,
    [org_renter_id]      INT             NULL,
    [org_renter_name]    VARCHAR (255)   NULL,
    [org_balans_id]      INT             NULL,
    [org_balans_name]    VARCHAR (255)   NULL,
    [building_id]        INT             NULL,
    [balans_id]          INT             NULL,
    [addr_district_id]   INT             NULL,
    [expert_obj_type_id] INT             NULL,
    [obj_square]         NUMERIC (15, 2) NULL,
    [expert_id]          INT             NULL,
    [expert_name]        VARCHAR (255)   NULL,
    [modified_by]        VARCHAR (128)   NULL,
    [modify_date]        DATE            NULL,
    [rezenz_id]          INT             NULL,
    [addr_street_name]   VARCHAR (100)   NULL,
    [cost_1_usd]         NUMERIC (15, 2) NULL,
    [cost_prim]          NUMERIC (15, 2) NULL,
    [valuation_date]     DATE            NULL,
    [final_date]         DATE            NULL,
    [arch_num]           VARCHAR (10)    NULL,
    [arch_date]          DATE            NULL,
    [is_archived]        INT             NULL,
    [is_stand_oc]        INT             NULL,
    [is_deleted]         INT             NULL,
    [del_date]           DATE            NULL,
    [addr_number1]       VARCHAR (9)     NULL,
    [addr_number2]       VARCHAR (64)    NULL,
    [note_text]          VARCHAR (255)   NULL,
    [addr_street_id]     INT             NULL,
    [addr_nomer]         VARCHAR (256)   NULL,
    [valuation_kind_id]  INT             NULL,
    [stan_id]            INT             NULL
);

