CREATE TABLE [dbo].[zzzzzzzzzz20250102_reports1nf_buildings] (
    [id]                 INT             NOT NULL,
    [master_building_id] INT             NULL,
    [addr_street_name]   VARCHAR (128)   NULL,
    [addr_street_id]     INT             NULL,
    [addr_street_name2]  VARCHAR (128)   NULL,
    [addr_street_id2]    INT             NULL,
    [street_full_name]   VARCHAR (128)   NULL,
    [addr_distr_old_id]  INT             NULL,
    [addr_distr_new_id]  INT             NULL,
    [addr_nomer1]        VARCHAR (32)    NULL,
    [addr_nomer2]        VARCHAR (32)    NULL,
    [addr_nomer3]        VARCHAR (32)    NULL,
    [addr_nomer]         VARCHAR (98)    NULL,
    [addr_misc]          VARCHAR (128)   NULL,
    [addr_korpus_flag]   INT             NULL,
    [addr_korpus]        VARCHAR (255)   NULL,
    [addr_zip_code]      VARCHAR (24)    NULL,
    [addr_address]       VARCHAR (356)   NULL,
    [tech_condition_id]  INT             NULL,
    [date_begin]         DATE            NULL,
    [date_end]           DATE            NULL,
    [num_floors]         VARCHAR (24)    NULL,
    [construct_year]     INT             NULL,
    [condition_year]     INT             NULL,
    [is_condition_valid] INT             NULL,
    [bti_code]           VARCHAR (24)    NULL,
    [history_id]         INT             NULL,
    [object_type_id]     INT             NULL,
    [object_kind_id]     INT             NULL,
    [is_land]            INT             NULL,
    [modify_date]        DATE            NULL,
    [modified_by]        VARCHAR (128)   NULL,
    [kadastr_code]       VARCHAR (32)    NULL,
    [cost_balans]        NUMERIC (15, 3) NULL,
    [sqr_total]          NUMERIC (9, 2)  NULL,
    [sqr_pidval]         NUMERIC (9, 2)  NULL,
    [sqr_mk]             NUMERIC (9, 2)  NULL,
    [sqr_dk]             NUMERIC (9, 2)  NULL,
    [sqr_rk]             NUMERIC (9, 2)  NULL,
    [sqr_other]          NUMERIC (9, 2)  NULL,
    [sqr_rented]         NUMERIC (9, 2)  NULL,
    [sqr_zagal]          NUMERIC (9, 2)  NULL,
    [sqr_for_rent]       NUMERIC (9, 2)  NULL,
    [sqr_habit]          NUMERIC (9, 2)  NULL,
    [sqr_non_habit]      NUMERIC (9, 2)  NULL,
    [additional_info]    VARCHAR (252)   NULL,
    [is_deleted]         INT             NULL,
    [del_date]           DATE            NULL,
    [oatuu_id]           VARCHAR (10)    NULL,
    [updpr]              INT             NULL,
    [arch_id]            INT             NULL,
    [arch_flag]          INT             NULL,
    [facade_id]          INT             NULL,
    [nomer_int]          INT             NULL,
    [characteristics]    VARCHAR (MAX)   NULL,
    [expl_enter_year]    INT             NULL,
    [is_basement_exists] INT             NULL,
    [is_loft_exists]     INT             NULL,
    [sqr_loft]           NUMERIC (9, 2)  NULL,
    [unique_id]          INT             IDENTITY (1, 1) NOT NULL,
    [report_id]          INT             NOT NULL
);

