CREATE TABLE [dbo].[zzzz20220109_backup__arenda_decisions] (
    [id]               INT             NOT NULL,
    [decision_id]      INT             NULL,
    [etr]              VARCHAR (2)     NULL,
    [rent_term]        VARCHAR (252)   NULL,
    [rent_term_note]   VARCHAR (252)   NULL,
    [title]            VARCHAR (252)   NULL,
    [rent_purpose]     VARCHAR (252)   NULL,
    [nov_prot]         VARCHAR (1)     NULL,
    [building_id]      INT             NULL,
    [org_renter_id]    INT             NULL,
    [org_balans_id]    INT             NULL,
    [org_giver_id]     INT             NULL,
    [balans_id]        INT             NULL,
    [apply_date]       DATE            NULL,
    [apply_letter_id]  INT             NULL,
    [apply_letter_num] VARCHAR (9)     NULL,
    [appendix_prot_id] INT             NULL,
    [appendix_rasp_id] INT             NULL,
    [application_id]   INT             NULL,
    [num_rooms]        INT             NULL,
    [sqr_applied]      NUMERIC (15, 2) NULL,
    [sqr_robocha]      NUMERIC (15, 2) NULL,
    [cost_1m]          NUMERIC (15, 2) NULL,
    [cost_rent]        NUMERIC (15, 2) NULL,
    [is_subarenda]     INT             NULL,
    [stadiya_id]       INT             NULL,
    [rishen_punkt]     INT             NULL,
    [modified_by]      VARCHAR (128)   NULL,
    [modify_date]      DATE            NULL,
    [note_rish_etap1]  VARCHAR (MAX)   NULL,
    [note_rish2_etap1] VARCHAR (MAX)   NULL,
    [note_nazva]       VARCHAR (MAX)   NULL,
    [note_rish_etap2]  VARCHAR (MAX)   NULL,
    [note_rish2_etap2] VARCHAR (MAX)   NULL,
    [blob_rish_etap1]  VARBINARY (MAX) NULL,
    [blob_rish2_etap1] VARBINARY (MAX) NULL,
    [blob_nazva]       VARBINARY (MAX) NULL,
    [blob_rish_etap2]  VARBINARY (MAX) NULL,
    [blob_rish2_etap2] VARBINARY (MAX) NULL
);

