CREATE TABLE [dbo].[zzzz20250119_del_reports1nf_arenda] (
    [id]                      INT             NOT NULL,
    [building_id]             INT             NULL,
    [org_balans_id]           INT             NULL,
    [org_renter_id]           INT             NULL,
    [org_giver_id]            INT             NULL,
    [balans_id]               INT             NULL,
    [rent_year]               INT             NULL,
    [object_kind_id]          INT             NULL,
    [purpose_group_id]        INT             NULL,
    [purpose_id]              INT             NULL,
    [purpose_str]             VARCHAR (252)   NULL,
    [name]                    VARCHAR (252)   NULL,
    [is_privat]               INT             NULL,
    [update_src_id]           INT             NULL,
    [agreement_kind_id]       INT             NULL,
    [agreement_date]          DATE            NULL,
    [agreement_num]           VARCHAR (18)    NULL,
    [agreement_str]           VARCHAR (252)   NULL,
    [floor_number]            VARCHAR (100)   NULL,
    [num_people]              INT             NULL,
    [cost_narah]              NUMERIC (15, 3) NULL,
    [cost_payed]              NUMERIC (15, 3) NULL,
    [cost_debt]               NUMERIC (15, 3) NULL,
    [cost_agreement]          NUMERIC (15, 3) NULL,
    [cost_expert_1m]          NUMERIC (15, 3) NULL,
    [cost_expert_total]       NUMERIC (15, 3) NULL,
    [pidstava]                VARCHAR (252)   NULL,
    [pidstava_date]           DATE            NULL,
    [pidstava_num]            VARCHAR (18)    NULL,
    [pidstava_fact]           VARCHAR (200)   NULL,
    [pidstava2]               VARCHAR (252)   NULL,
    [pidstava_num2]           VARCHAR (18)    NULL,
    [pidstava_date2]          DATE            NULL,
    [pidstava_display]        VARCHAR (MAX)   NULL,
    [rent_start_date]         DATE            NULL,
    [rent_finish_date]        DATE            NULL,
    [rent_actual_finish_date] DATE            NULL,
    [rent_rate]               NUMERIC (15, 3) NULL,
    [rent_rate_uah]           NUMERIC (15, 3) NULL,
    [rent_square]             NUMERIC (9, 2)  NULL,
    [priznak_1nf]             INT             NULL,
    [debt_timespan]           VARCHAR (18)    NULL,
    [order_num]               VARCHAR (18)    NULL,
    [order_date]              DATE            NULL,
    [order_no2]               VARCHAR (18)    NULL,
    [rishennya_id]            INT             NULL,
    [is_inactive]             INT             NULL,
    [inactive_date]           DATE            NULL,
    [is_deleted]              INT             NULL,
    [del_date]                DATE            NULL,
    [date_expert]             DATE            NULL,
    [is_subarenda]            INT             NULL,
    [privat_kind_id]          INT             NULL,
    [num_primirnikiv]         INT             NULL,
    [date_expl_enter]         DATE            NULL,
    [num_akt]                 VARCHAR (18)    NULL,
    [date_akt]                DATE            NULL,
    [num_bti]                 VARCHAR (18)    NULL,
    [date_bti]                DATE            NULL,
    [svidotstvo_serial]       VARCHAR (3)     NULL,
    [svidotstvo_num]          VARCHAR (18)    NULL,
    [svidotstvo_date]         DATE            NULL,
    [payment_type_id]         INT             NULL,
    [arch_id]                 INT             NULL,
    [modified_by]             VARCHAR (128)   NULL,
    [modify_date]             DATETIME        NULL,
    [note]                    VARCHAR (MAX)   NULL,
    [agreement_state]         INT             NULL,
    [is_insured]              INT             NULL,
    [insurance_start]         DATE            NULL,
    [insurance_end]           DATE            NULL,
    [insurance_sum]           NUMERIC (15, 2) NULL,
    [report_id]               INT             NOT NULL,
    [building_1nf_unique_id]  INT             NULL,
    [submit_date]             DATETIME        NULL,
    [is_loan_agreement]       INT             NULL,
    [is_valid]                INT             NULL,
    [validation_errors]       TEXT            NULL,
    [base_month]              DATE            NULL,
    [method_calc_id]          INT             NULL
);

