CREATE TABLE [dbo].[zzzzz20260106_fordel] (
    [cnt]                     INT             NULL,
    [arenda_id]               INT             NULL,
    [rent_period_id]          INT             NULL,
    [sqr_total_rent]          NUMERIC (15, 3) NULL,
    [sqr_payed_by_percent]    NUMERIC (15, 3) NULL,
    [sqr_payed_by_1uah]       NUMERIC (15, 3) NULL,
    [sqr_payed_hourly]        NUMERIC (15, 3) NULL,
    [payment_narah]           NUMERIC (15, 3) NULL,
    [last_year_saldo]         NUMERIC (15, 3) NULL,
    [payment_received]        NUMERIC (15, 3) NULL,
    [payment_nar_zvit]        NUMERIC (15, 3) NULL,
    [payment_budget_special]  NUMERIC (15, 3) NULL,
    [debt_total]              NUMERIC (15, 3) NULL,
    [debt_zvit]               NUMERIC (15, 3) NULL,
    [debt_3_month]            NUMERIC (15, 3) NULL,
    [debt_12_month]           NUMERIC (15, 3) NULL,
    [debt_3_years]            NUMERIC (15, 3) NULL,
    [debt_over_3_years]       NUMERIC (15, 3) NULL,
    [debt_v_mezhah_vitrat]    NUMERIC (15, 3) NULL,
    [debt_spysano]            NUMERIC (15, 3) NULL,
    [num_zahodiv_total]       INT             NULL,
    [num_zahodiv_zvit]        INT             NULL,
    [num_pozov_total]         INT             NULL,
    [num_pozov_zvit]          INT             NULL,
    [num_pozov_zadov_total]   INT             NULL,
    [num_pozov_zadov_zvit]    INT             NULL,
    [num_pozov_vikon_total]   INT             NULL,
    [num_pozov_vikon_zvit]    INT             NULL,
    [debt_pogasheno_total]    NUMERIC (15, 3) NULL,
    [debt_pogasheno_zvit]     NUMERIC (15, 3) NULL,
    [budget_narah_50_uah]     NUMERIC (15, 3) NULL,
    [budget_zvit_50_uah]      NUMERIC (15, 3) NULL,
    [budget_prev_50_uah]      NUMERIC (15, 3) NULL,
    [budget_debt_50_uah]      NUMERIC (15, 3) NULL,
    [budget_debt_30_50_uah]   NUMERIC (15, 3) NULL,
    [is_renter_out]           INT             NULL,
    [is_debt_exists]          INT             NULL,
    [modify_date]             DATETIME        NULL,
    [modified_by]             VARCHAR (128)   NULL,
    [is_special_organization] INT             NULL,
    [id]                      INT             IDENTITY (1, 1) NOT NULL,
    [report_id]               INT             NOT NULL,
    [old_debts_payed]         NUMERIC (15, 3) NULL,
    [zvilneno_date1]          DATETIME        NULL,
    [zvilneno_date2]          DATETIME        NULL,
    [zvilneno_percent]        NUMERIC (15, 3) NULL,
    [is_discount]             INT             NULL,
    [povidoleno1_date]        DATETIME        NULL,
    [povidoleno1_num]         VARCHAR (128)   NULL,
    [povidoleno2_date]        DATETIME        NULL,
    [povidoleno2_num]         VARCHAR (128)   NULL,
    [povidoleno3_date]        DATETIME        NULL,
    [povidoleno3_num]         VARCHAR (128)   NULL,
    [povidoleno4_date]        DATETIME        NULL,
    [povidoleno4_num]         VARCHAR (128)   NULL,
    [return_orend_payed]      NUMERIC (15, 3) NULL,
    [zvilbykmp_date1]         DATETIME        NULL,
    [zvilbykmp_date2]         DATETIME        NULL,
    [zvilbykmp_percent]       NUMERIC (15, 3) NULL,
    [return_all_orend_payed]  NUMERIC (15, 3) NULL,
    [use_calc_debt]           INT             NULL,
    [debtkvart_0]             NUMERIC (15, 3) NULL,
    [debtkvart_1]             NUMERIC (15, 3) NULL,
    [debtkvart_2]             NUMERIC (15, 3) NULL,
    [debtkvart_3]             NUMERIC (15, 3) NULL,
    [debtkvart_4]             NUMERIC (15, 3) NULL,
    [debtkvart_5]             NUMERIC (15, 3) NULL,
    [debtkvart_6]             NUMERIC (15, 3) NULL,
    [debtkvart_7]             NUMERIC (15, 3) NULL,
    [debtkvart_8]             NUMERIC (15, 3) NULL,
    [debtkvart_9]             NUMERIC (15, 3) NULL,
    [debtkvart_10]            NUMERIC (15, 3) NULL,
    [debtkvart_11]            NUMERIC (15, 3) NULL,
    [debtkvart_12]            NUMERIC (15, 3) NULL,
    [debtkvart_13]            NUMERIC (15, 3) NULL,
    [debtkvart_14]            NUMERIC (15, 3) NULL,
    [debtkvart_15]            NUMERIC (15, 3) NULL,
    [debtkvart_16]            NUMERIC (15, 3) NULL,
    [debtkvart_17]            NUMERIC (15, 3) NULL,
    [debtkvart_18]            NUMERIC (15, 3) NULL,
    [debtkvart_19]            NUMERIC (15, 3) NULL,
    [debtkvart_20]            NUMERIC (15, 3) NULL,
    [avance_plat]             NUMERIC (15, 3) NULL,
    [znyato_nadmirno_narah]   NUMERIC (15, 3) NULL,
    [avance_paymentnar]       NUMERIC (15, 3) NULL,
    [avance_saldo]            NUMERIC (15, 3) NULL,
    [avance_debt]             NUMERIC (15, 3) NULL,
    [znyato_from_avance]      NUMERIC (15, 3) NULL,
    [zabezdepoz_narah]        NUMERIC (15, 3) NULL,
    [zabezdepoz_saldo]        NUMERIC (15, 3) NULL,
    [zabezdepoz_nadhod]       NUMERIC (15, 3) NULL,
    [use_zabezdepoz]          INT             NULL,
    [zabezdepoz_debt]         NUMERIC (15, 3) NULL,
    [total_pereplata]         NUMERIC (15, 3) NULL,
    [zabezd_usesum]           NUMERIC (15, 3) NULL,
    [avance_usesum]           NUMERIC (15, 3) NULL,
    [zabezdepoz_prishlo]      NUMERIC (15, 3) NULL,
    [zvilbykmp2_date1]        DATETIME        NULL,
    [zvilbykmp2_date2]        DATETIME        NULL,
    [zvilbykmp2_percent]      NUMERIC (15, 3) NULL,
    [zvilbykmp3_date1]        DATETIME        NULL,
    [zvilbykmp3_date2]        DATETIME        NULL,
    [zvilbykmp3_percent]      NUMERIC (15, 3) NULL,
    [total_year_saldo]        NUMERIC (15, 3) NULL,
    [zvilbykmp6_date1]        DATETIME        NULL,
    [zvilbykmp6_date2]        DATETIME        NULL,
    [zvilbykmp6_percent]      NUMERIC (15, 3) NULL,
    [zvilbykmp7_date1]        DATETIME        NULL,
    [zvilbykmp7_date2]        DATETIME        NULL,
    [zvilbykmp7_percent]      NUMERIC (15, 3) NULL,
    [znizhka1_name]           VARCHAR (1000)  NULL,
    [znizhka1_percent]        NUMERIC (15, 3) NULL,
    [znizhka1_date1]          DATETIME        NULL,
    [znizhka1_date2]          DATETIME        NULL,
    [znizhka2_name]           VARCHAR (1000)  NULL,
    [znizhka2_percent]        NUMERIC (15, 3) NULL,
    [znizhka2_date1]          DATETIME        NULL,
    [znizhka2_date2]          DATETIME        NULL,
    [znizhka3_name]           VARCHAR (1000)  NULL,
    [znizhka3_percent]        NUMERIC (15, 3) NULL,
    [znizhka3_date1]          DATETIME        NULL,
    [znizhka3_date2]          DATETIME        NULL,
    [znizhka4_name]           VARCHAR (1000)  NULL,
    [znizhka4_percent]        NUMERIC (15, 3) NULL,
    [znizhka4_date1]          DATETIME        NULL,
    [znizhka4_date2]          DATETIME        NULL,
    [znizhka5_name]           VARCHAR (1000)  NULL,
    [znizhka5_percent]        NUMERIC (15, 3) NULL,
    [znizhka5_date1]          DATETIME        NULL,
    [znizhka5_date2]          DATETIME        NULL,
    [znizhka6_name]           VARCHAR (1000)  NULL,
    [znizhka6_percent]        NUMERIC (15, 3) NULL,
    [znizhka6_date1]          DATETIME        NULL,
    [znizhka6_date2]          DATETIME        NULL,
    [znizhka1_invnums]        VARCHAR (1000)  NULL,
    [znizhka2_invnums]        VARCHAR (1000)  NULL,
    [znizhka3_invnums]        VARCHAR (1000)  NULL,
    [znizhka4_invnums]        VARCHAR (1000)  NULL,
    [znizhka5_invnums]        VARCHAR (1000)  NULL,
    [znizhka6_invnums]        VARCHAR (1000)  NULL,
    [znizhka7_name]           VARCHAR (1000)  NULL,
    [znizhka7_percent]        NUMERIC (15, 3) NULL,
    [znizhka7_date1]          DATETIME        NULL,
    [znizhka7_date2]          DATETIME        NULL,
    [znizhka7_invnums]        VARCHAR (1000)  NULL,
    [znizhka8_name]           VARCHAR (1000)  NULL,
    [znizhka8_percent]        NUMERIC (15, 3) NULL,
    [znizhka8_date1]          DATETIME        NULL,
    [znizhka8_date2]          DATETIME        NULL,
    [znizhka8_invnums]        VARCHAR (1000)  NULL,
    [znizhka9_name]           VARCHAR (1000)  NULL,
    [znizhka9_percent]        NUMERIC (15, 3) NULL,
    [znizhka9_date1]          DATETIME        NULL,
    [znizhka9_date2]          DATETIME        NULL,
    [znizhka9_invnums]        VARCHAR (1000)  NULL,
    [znizhka10_name]          VARCHAR (1000)  NULL,
    [znizhka10_percent]       NUMERIC (15, 3) NULL,
    [znizhka10_date1]         DATETIME        NULL,
    [znizhka10_date2]         DATETIME        NULL,
    [znizhka10_invnums]       VARCHAR (1000)  NULL,
    [is_cmk]                  INT             NULL,
    [cmk_sqr_rented]          NUMERIC (15, 3) NULL,
    [cmk_payment_narah]       NUMERIC (15, 3) NULL,
    [cmk_payment_to_budget]   NUMERIC (15, 3) NULL,
    [cmk_rent_debt]           NUMERIC (15, 3) NULL
);

