CREATE TABLE [dbo].[zzzz20220109_backup__privatization] (
    [id]               INT             NOT NULL,
    [building_id]      INT             NOT NULL,
    [organization_id]  INT             NULL,
    [balans_id]        INT             NULL,
    [obj_group_id]     INT             NULL,
    [privat_kind_id]   INT             NULL,
    [privat_state_id]  INT             NULL,
    [sqr_total]        NUMERIC (9, 2)  NULL,
    [obj_name]         VARCHAR (100)   NULL,
    [complex_id]       INT             NULL,
    [object_kind_id]   INT             NULL,
    [object_type_id]   INT             NULL,
    [purpose_group_id] INT             NULL,
    [history_id]       INT             NULL,
    [obj_floor]        INT             NULL,
    [note]             VARCHAR (100)   NULL,
    [cost]             NUMERIC (15, 2) NULL,
    [cost_expert]      NUMERIC (15, 2) NULL,
    [expert_date]      DATE            NULL,
    [subordination_id] INT             NULL,
    [rishen_doc_id]    INT             NULL,
    [modified_by]      VARCHAR (128)   NULL,
    [modify_date]      DATE            NULL,
    [addr_street_name] VARCHAR (100)   NULL,
    [addr_number]      VARCHAR (18)    NULL,
    [addr_misc]        VARCHAR (30)    NULL,
    [addr_district_id] INT             NULL,
    [addr_zip_code]    VARCHAR (15)    NULL
);

