//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUKV.DataMigration.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUKV.DataMigration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на літ. 17.
        /// </summary>
        internal static string AddrBehterevskyyLit17 {
            get {
                return ResourceManager.GetString("AddrBehterevskyyLit17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на літ. 2.
        /// </summary>
        internal static string AddrBehterevskyyLit2 {
            get {
                return ResourceManager.GetString("AddrBehterevskyyLit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 23 КМ, К.1.
        /// </summary>
        internal static string AddrBoryspilske23KMK1 {
            get {
                return ResourceManager.GetString("AddrBoryspilske23KMK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ,К.10 (ЛІТ.Б).
        /// </summary>
        internal static string AddrDniprodz130K10B_correct {
            get {
                return ResourceManager.GetString("AddrDniprodz130K10B_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ,К.10 (ЛІТ.Б) ПОБУ.
        /// </summary>
        internal static string AddrDniprodz130K10B_wrong {
            get {
                return ResourceManager.GetString("AddrDniprodz130K10B_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А ЛІТ.А.
        /// </summary>
        internal static string AddrFranka24A_correct {
            get {
                return ResourceManager.GetString("AddrFranka24A_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -а літ..
        /// </summary>
        internal static string AddrFranka24A_wrong {
            get {
                return ResourceManager.GetString("AddrFranka24A_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Б.
        /// </summary>
        internal static string AddrGorkogoLitB {
            get {
                return ResourceManager.GetString("AddrGorkogoLitB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /7 ЛІТ.А 3К..
        /// </summary>
        internal static string AddrIllinska37A3k {
            get {
                return ResourceManager.GetString("AddrIllinska37A3k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КМ.
        /// </summary>
        internal static string AddrKM {
            get {
                return ResourceManager.GetString("AddrKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /7  К.2.
        /// </summary>
        internal static string AddrKopylivska1_7_k2_correct {
            get {
                return ResourceManager.GetString("AddrKopylivska1_7_k2_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /7  К2.
        /// </summary>
        internal static string AddrKopylivska1_7_k2_wrong {
            get {
                return ResourceManager.GetString("AddrKopylivska1_7_k2_wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НЕМ.
        /// </summary>
        internal static string AddrNoInfo1 {
            get {
                return ResourceManager.GetString("AddrNoInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВІДС.
        /// </summary>
        internal static string AddrNoInfo2 {
            get {
                return ResourceManager.GetString("AddrNoInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ШУТОВА.
        /// </summary>
        internal static string AddrShutova {
            get {
                return ResourceManager.GetString("AddrShutova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СМОЛИЧА.
        /// </summary>
        internal static string AddrSmolicha {
            get {
                return ResourceManager.GetString("AddrSmolicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Б/Н.
        /// </summary>
        internal static string BuildingAddressNoNumber {
            get {
                return ResourceManager.GetString("BuildingAddressNoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БН.
        /// </summary>
        internal static string BuildingAddressNoNumberCorrect {
            get {
                return ResourceManager.GetString("BuildingAddressNoNumberCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОК-.
        /// </summary>
        internal static string BuildingDockPrefix1 {
            get {
                return ResourceManager.GetString("BuildingDockPrefix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К.К..
        /// </summary>
        internal static string BuildingKorpusDuplicate {
            get {
                return ResourceManager.GetString("BuildingKorpusDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КОРП..
        /// </summary>
        internal static string BuildingKorpusPrefix1 {
            get {
                return ResourceManager.GetString("BuildingKorpusPrefix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на корп..
        /// </summary>
        internal static string BuildingKorpusPrefix2 {
            get {
                return ResourceManager.GetString("BuildingKorpusPrefix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К-.
        /// </summary>
        internal static string BuildingKorpusPrefix3 {
            get {
                return ResourceManager.GetString("BuildingKorpusPrefix3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К.
        /// </summary>
        internal static string BuildingKorpusPrefix4 {
            get {
                return ResourceManager.GetString("BuildingKorpusPrefix4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К..
        /// </summary>
        internal static string BuildingKorpusPrefixCorrect {
            get {
                return ResourceManager.GetString("BuildingKorpusPrefixCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А.
        /// </summary>
        internal static string BuildingLetterA {
            get {
                return ResourceManager.GetString("BuildingLetterA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛІТ..
        /// </summary>
        internal static string BuildingLitPrefix {
            get {
                return ResourceManager.GetString("BuildingLitPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛІТЕР..
        /// </summary>
        internal static string BuildingLitPrefix2 {
            get {
                return ResourceManager.GetString("BuildingLitPrefix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛІТЕРА.
        /// </summary>
        internal static string BuildingLitPrefix3 {
            get {
                return ResourceManager.GetString("BuildingLitPrefix3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛІТЕР.
        /// </summary>
        internal static string BuildingLitPrefix4 {
            get {
                return ResourceManager.GetString("BuildingLitPrefix4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛІТЕР ..
        /// </summary>
        internal static string BuildingLitPrefix5 {
            get {
                return ResourceManager.GetString("BuildingLitPrefix5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛІТЕР  ..
        /// </summary>
        internal static string BuildingLitPrefix6 {
            get {
                return ResourceManager.GetString("BuildingLitPrefix6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛІТЕРА -.
        /// </summary>
        internal static string BuildingLitPrefix7 {
            get {
                return ResourceManager.GetString("BuildingLitPrefix7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛІТ.
        /// </summary>
        internal static string BuildingLitPrefix8 {
            get {
                return ResourceManager.GetString("BuildingLitPrefix8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ч..
        /// </summary>
        internal static string BuildingPartPrefix1 {
            get {
                return ResourceManager.GetString("BuildingPartPrefix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №.
        /// </summary>
        internal static string BuildingPrefixNumber {
            get {
                return ResourceManager.GetString("BuildingPrefixNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єкт {0} кв.м. на балансі у організації &apos;{1}&apos; за адресою {2}.
        /// </summary>
        internal static string CorrectionBalansInfoNoDate {
            get {
                return ResourceManager.GetString("CorrectionBalansInfoNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єкт {0} кв.м. на балансі у організації &apos;{1}&apos; за адресою {2}, дата актуальності {3}.
        /// </summary>
        internal static string CorrectionBalansInfoWithDate {
            get {
                return ResourceManager.GetString("CorrectionBalansInfoWithDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створено новий об&apos;єкт на балансі по інформації з БД &apos;Приватизація&apos;.
        /// </summary>
        internal static string CorrectionMsgBalansObjCreatedFromPrivat {
            get {
                return ResourceManager.GetString("CorrectionMsgBalansObjCreatedFromPrivat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створено новий об&apos;єкт на балансі по інформації з БД &apos;Розпорядження&apos;.
        /// </summary>
        internal static string CorrectionMsgBalansObjCreatedFromTransfer {
            get {
                return ResourceManager.GetString("CorrectionMsgBalansObjCreatedFromTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Встановлено новий балансоутримувач &apos;{1}&apos;.
        /// </summary>
        internal static string CorrectionMsgBalansObjNewHolder {
            get {
                return ResourceManager.GetString("CorrectionMsgBalansObjNewHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Встановлено новий балансоутримувач &apos;{1}&apos;, та форма власності &apos;{2}&apos;.
        /// </summary>
        internal static string CorrectionMsgBalansObjNewHolderAndOwnership {
            get {
                return ResourceManager.GetString("CorrectionMsgBalansObjNewHolderAndOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Змінено площу об&apos;єкту, нова площа становить {1}.
        /// </summary>
        internal static string CorrectionMsgBalansSqrCorrected {
            get {
                return ResourceManager.GetString("CorrectionMsgBalansSqrCorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Дані по цьому об&apos;єкту є більш актуальними, ніж договір купівлі-продажу з БД &apos;Приватизація&apos;, і не можуть бути змінені. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionMsgBalansUpToDate {
            get {
                return ResourceManager.GetString("CorrectionMsgBalansUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За інформацією з БД &apos;Приватизація&apos;.
        /// </summary>
        internal static string CorrectionMsgFromPrivatization {
            get {
                return ResourceManager.GetString("CorrectionMsgFromPrivatization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Площа цього об&apos;єкту в 1НФ не співпадає з площею об&apos;єкту з БД &apos;Приватизація&apos;. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionMsgIncorrectPrivatSquare {
            get {
                return ResourceManager.GetString("CorrectionMsgIncorrectPrivatSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В 1НФ нема об&apos;єктів на балансі за адресою {0}.
        /// </summary>
        internal static string CorrectionMsgNoDataByAddress {
            get {
                return ResourceManager.GetString("CorrectionMsgNoDataByAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продаж даного об&apos;єкту в БД &apos;Приватизація&apos; не підтверджено Актом. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionMsgNoPrivatAkt {
            get {
                return ResourceManager.GetString("CorrectionMsgNoPrivatAkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неможливо однозначно співставити об&apos;єкт з базою 1НФ, оскільки в 1НФ за цією адресою нема договорів оренди у організації &apos;{0}&apos;. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionMsgNoRentAgreements {
            get {
                return ResourceManager.GetString("CorrectionMsgNoRentAgreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Змінено форму власності об&apos;єкту на &apos;{0}&apos;.
        /// </summary>
        internal static string CorrectionMsgOwnershipChanged {
            get {
                return ResourceManager.GetString("CorrectionMsgOwnershipChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неможливо однозначно співставити об&apos;єкт з базою 1НФ, оскільки в 1НФ за цією адресою є кілька об&apos;єктів на балансі у організації &apos;{0}&apos;. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionMsgTooManyObjOnBalans {
            get {
                return ResourceManager.GetString("CorrectionMsgTooManyObjOnBalans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неможливо однозначно співставити об&apos;єкт з базою 1НФ, оскільки в 1НФ за цією адресою є кілька договорів оренди у організації &apos;{0}&apos;. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionMsgTooManyRentAgreements {
            get {
                return ResourceManager.GetString("CorrectionMsgTooManyRentAgreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Даний об&apos;єкт в 1НФ закріплено за іншим балансоутримувачем. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionMsgWrongBalansHolder {
            get {
                return ResourceManager.GetString("CorrectionMsgWrongBalansHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неможливо однозначно співставити об&apos;єкт з базою 1НФ, оскільки є невідповідність між догором оренди організації &apos;{0}&apos; в 1НФ та даними з БД &apos;Приватизація&apos;. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionMsgWrongRentAgreement {
            get {
                return ResourceManager.GetString("CorrectionMsgWrongRentAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Об&apos;єкт з БД &apos;Приватизація&apos; {0} за адресою {1}, площа {2} кв.м., приватизовано організацією &apos;{3}&apos;.
        /// </summary>
        internal static string CorrectionPrivatInfo {
            get {
                return ResourceManager.GetString("CorrectionPrivatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наявність інформації про передачу об&apos;єкту в БД &apos;Розпорядження&apos;.
        /// </summary>
        internal static string CorrectionReasonTransfer {
            get {
                return ResourceManager.GetString("CorrectionReasonTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Договір {0} на оренду {1} кв.м. між балансоутримувачем &apos;{2}&apos; та орендарем &apos;{3}&apos; за адресою {4}.
        /// </summary>
        internal static string CorrectionRentInfo {
            get {
                return ResourceManager.GetString("CorrectionRentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Інформація в БД &apos;1НФ&apos; за цією адресою не відповідає інформації з БД &apos;Розпорядження&apos;. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionTransferAmbiguity {
            get {
                return ResourceManager.GetString("CorrectionTransferAmbiguity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Дані по цьому об&apos;єкту є більш актуальними, ніж інформація про передачу прав з БД &apos;Розпорядження&apos;, і не можуть бути змінені. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionTransferBalansUpToDate {
            get {
                return ResourceManager.GetString("CorrectionTransferBalansUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Передано {0} {1} кв.м. за адресою {2} від організації &apos;{3}&apos; до організації &apos;{4}&apos;, право {5}.
        /// </summary>
        internal static string CorrectionTransferInfo {
            get {
                return ResourceManager.GetString("CorrectionTransferInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Організація, від якої передано об&apos;єкт, не має схожого об&apos;єкту на балансі за цією адресою в БД &apos;1НФ&apos;. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionTransferNoSuitableObjForGiver {
            get {
                return ResourceManager.GetString("CorrectionTransferNoSuitableObjForGiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В БД &apos;1НФ&apos; існує схожий об&apos;єкт, але він знаходиться на балансі іншої організації. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionTransferOwnerMismatch {
            get {
                return ResourceManager.GetString("CorrectionTransferOwnerMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не співпадає площа об&apos;єкту в БД &apos;1НФ&apos; та в БД &apos;Розпорядження&apos;. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionTransferSqrMismatch {
            get {
                return ResourceManager.GetString("CorrectionTransferSqrMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неможливо однозначно визначити об&apos;єкт в БД 1НФ, оскільки організація, від якої передано об&apos;єкт, має кілька об&apos;єктів на балансі за цією адресою. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionTransferTooManyObjForGiver {
            get {
                return ResourceManager.GetString("CorrectionTransferTooManyObjForGiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неможливо однозначно визначити об&apos;єкт в БД 1НФ, оскільки організація, якій передано об&apos;єкт, має кілька об&apos;єктів на балансі за цією адресою. Необхідна перевірка..
        /// </summary>
        internal static string CorrectionTransferTooManyObjForReceiver {
            get {
                return ResourceManager.GetString("CorrectionTransferTooManyObjForReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РІГ.
        /// </summary>
        internal static string CrossRoadPrefix {
            get {
                return ResourceManager.GetString("CrossRoadPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повне ім&apos;я організації.
        /// </summary>
        internal static string CvsLogBalansOrgFullName {
            get {
                return ResourceManager.GetString("CvsLogBalansOrgFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код ЗКПО.
        /// </summary>
        internal static string CvsLogBalansOrgOKPO {
            get {
                return ResourceManager.GetString("CvsLogBalansOrgOKPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коротке ім&apos;я організації.
        /// </summary>
        internal static string CvsLogBalansOrgShortName {
            get {
                return ResourceManager.GetString("CvsLogBalansOrgShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корпус.
        /// </summary>
        internal static string CvsLogPrivatObjKorpus {
            get {
                return ResourceManager.GetString("CvsLogPrivatObjKorpus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва.
        /// </summary>
        internal static string CvsLogPrivatObjName {
            get {
                return ResourceManager.GetString("CvsLogPrivatObjName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер будинку.
        /// </summary>
        internal static string CvsLogPrivatObjNumber {
            get {
                return ResourceManager.GetString("CvsLogPrivatObjNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вулиця.
        /// </summary>
        internal static string CvsLogPrivatObjStreet {
            get {
                return ResourceManager.GetString("CvsLogPrivatObjStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поштовий індекс.
        /// </summary>
        internal static string CvsLogPrivatObjZIP {
            get {
                return ResourceManager.GetString("CvsLogPrivatObjZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A.
        /// </summary>
        internal static string DocArchiveFlagEng {
            get {
                return ResourceManager.GetString("DocArchiveFlagEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А.
        /// </summary>
        internal static string DocArchiveFlagRus {
            get {
                return ResourceManager.GetString("DocArchiveFlagRus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на від.
        /// </summary>
        internal static string DocDate {
            get {
                return ResourceManager.GetString("DocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОКУМЕНТИ 1НФ.
        /// </summary>
        internal static string DocKind1NFDocuments {
            get {
                return ResourceManager.GetString("DocKind1NFDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОКУМЕНТИ З АРЕНДИ.
        /// </summary>
        internal static string DocKindArendaDocuments {
            get {
                return ResourceManager.GetString("DocKindArendaDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НАКАЗ МІНІСТЕРСТВА ПАЛИВА ТА ЕНЕРГЕТИКИ.
        /// </summary>
        internal static string DocKindNakazMinEnergetiki {
            get {
                return ResourceManager.GetString("DocKindNakazMinEnergetiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОКУМЕНТИ З ПРИВАТИЗАЦІЇ.
        /// </summary>
        internal static string DocKindPrivatDocuments {
            get {
                return ResourceManager.GetString("DocKindPrivatDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РОЗПОРЯДЖЕННЯ КИЇВРАДИ.
        /// </summary>
        internal static string DocKindRozpKyivRadi {
            get {
                return ResourceManager.GetString("DocKindRozpKyivRadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РОЗПОРЯДЖЕННЯ МОСКОВСЬКОЇ РАЙДЕРЖАДМІНІСТРАЦІЇ.
        /// </summary>
        internal static string DocKindRozpMoskAdmin {
            get {
                return ResourceManager.GetString("DocKindRozpMoskAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РОЗПОРЯДЖЕННЯ РАДЯНСЬКОЇ РАЙДЕРЖАДМІНІСТРАЦІЇ.
        /// </summary>
        internal static string DocKindRozpRadyanskAdmin {
            get {
                return ResourceManager.GetString("DocKindRozpRadyanskAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РОЗПОРЯДЖЕННЯ ЗАЛІЗНИЧНОЇ РАЙДЕРЖАДМІНІСТРАЦІЇ.
        /// </summary>
        internal static string DocKindRozpZaliznAdmin {
            get {
                return ResourceManager.GetString("DocKindRozpZaliznAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №.
        /// </summary>
        internal static string DocNum {
            get {
                return ResourceManager.GetString("DocNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КОНТРАКТ.
        /// </summary>
        internal static string DocTypeContract {
            get {
                return ResourceManager.GetString("DocTypeContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РІШЕННЯ.
        /// </summary>
        internal static string DocTypeDecision {
            get {
                return ResourceManager.GetString("DocTypeDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РОЗПОРЯДЖЕННЯ.
        /// </summary>
        internal static string DocTypeOrder {
            get {
                return ResourceManager.GetString("DocTypeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РОЗПОРЯДЖЕННЯ КМДА.
        /// </summary>
        internal static string DocTypeOrderKMDA {
            get {
                return ResourceManager.GetString("DocTypeOrderKMDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОЛОЖЕННЯ.
        /// </summary>
        internal static string DocTypePolojennya {
            get {
                return ResourceManager.GetString("DocTypePolojennya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОСТАНОВА.
        /// </summary>
        internal static string DocTypePostanova {
            get {
                return ResourceManager.GetString("DocTypePostanova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОВІДОМЛЕННЯ ПРО ПРИПИНЕННЯ ЮР.ОСОБИ.
        /// </summary>
        internal static string DocTypePovidomlennya {
            get {
                return ResourceManager.GetString("DocTypePovidomlennya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОТОКОЛ.
        /// </summary>
        internal static string DocTypeProtocol {
            get {
                return ResourceManager.GetString("DocTypeProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СТАТУТ.
        /// </summary>
        internal static string DocTypeStatut {
            get {
                return ResourceManager.GetString("DocTypeStatut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЄДРПОУ.
        /// </summary>
        internal static string FinCoefDocFileZKPOPattern {
            get {
                return ResourceManager.GetString("FinCoefDocFileZKPOPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Норматив відрахувань місто.dot.
        /// </summary>
        internal static string FinCoefWordFileName1 {
            get {
                return ResourceManager.GetString("FinCoefWordFileName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Норматив відрахувань райони.dot.
        /// </summary>
        internal static string FinCoefWordFileName2 {
            get {
                return ResourceManager.GetString("FinCoefWordFileName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %ФІНАНСОВИЙ ПЛАН%.
        /// </summary>
        internal static string FinPlan {
            get {
                return ResourceManager.GetString("FinPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %КВА%.
        /// </summary>
        internal static string FinPlanQuarterCol {
            get {
                return ResourceManager.GetString("FinPlanQuarterCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %ВІДРАХУВАННЯ%.
        /// </summary>
        internal static string FinPlanVidrahuvannia1 {
            get {
                return ResourceManager.GetString("FinPlanVidrahuvannia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %ПРИБУТКУ%.
        /// </summary>
        internal static string FinPlanVidrahuvannia2 {
            get {
                return ResourceManager.GetString("FinPlanVidrahuvannia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %БЮДЖЕТУ%.
        /// </summary>
        internal static string FinPlanVidrahuvannia3 {
            get {
                return ResourceManager.GetString("FinPlanVidrahuvannia3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %ФІНАНСОВІ%.
        /// </summary>
        internal static string FinResults1 {
            get {
                return ResourceManager.GetString("FinResults1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %РЕЗУЛЬТАТИ%.
        /// </summary>
        internal static string FinResults2 {
            get {
                return ResourceManager.GetString("FinResults2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string FinResultsForm1 {
            get {
                return ResourceManager.GetString("FinResultsForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2-М.
        /// </summary>
        internal static string FinResultsForm2 {
            get {
                return ResourceManager.GetString("FinResultsForm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %ЧИСТИЙ%.
        /// </summary>
        internal static string FinResultsPureIncome1 {
            get {
                return ResourceManager.GetString("FinResultsPureIncome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %ПРИБУТОК%.
        /// </summary>
        internal static string FinResultsPureIncome2 {
            get {
                return ResourceManager.GetString("FinResultsPureIncome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %ЗБИТОК%.
        /// </summary>
        internal static string FinResultsPureIncome3 {
            get {
                return ResourceManager.GetString("FinResultsPureIncome3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Середня чисельність працюючих за .
        /// </summary>
        internal static string FormulaAvgNumWorkers {
            get {
                return ResourceManager.GetString("FormulaAvgNumWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Середня заробітна плата за .
        /// </summary>
        internal static string FormulaAvgSalary {
            get {
                return ResourceManager.GetString("FormulaAvgSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зобов&apos;язання з відрахувань частки прибутку до бюджету на {0}.
        /// </summary>
        internal static string FormulaBudgPayments {
            get {
                return ResourceManager.GetString("FormulaBudgPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума відрахувань частки прибутку до бюджету за 2010 р..
        /// </summary>
        internal static string FormulaBudgPayments2010 {
            get {
                return ResourceManager.GetString("FormulaBudgPayments2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума відрахувань частки прибутку до бюджету за I кв. 2010 р..
        /// </summary>
        internal static string FormulaBudgPayments2010Q1 {
            get {
                return ResourceManager.GetString("FormulaBudgPayments2010Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума відрахувань частки прибутку до бюджету за II кв. 2010 р..
        /// </summary>
        internal static string FormulaBudgPayments2010Q2 {
            get {
                return ResourceManager.GetString("FormulaBudgPayments2010Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума відрахувань частки прибутку до бюджету за III кв. 2010 р..
        /// </summary>
        internal static string FormulaBudgPayments2010Q3 {
            get {
                return ResourceManager.GetString("FormulaBudgPayments2010Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума відрахувань частки прибутку до бюджету за 2011 р..
        /// </summary>
        internal static string FormulaBudgPayments2011 {
            get {
                return ResourceManager.GetString("FormulaBudgPayments2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума відрахувань частки прибутку до бюджету за I кв. 2011 р..
        /// </summary>
        internal static string FormulaBudgPayments2011Q1 {
            get {
                return ResourceManager.GetString("FormulaBudgPayments2011Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума відрахувань частки прибутку до бюджету за II кв. 2011 р..
        /// </summary>
        internal static string FormulaBudgPayments2011Q2 {
            get {
                return ResourceManager.GetString("FormulaBudgPayments2011Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума відрахувань частки прибутку до бюджету за III кв. 2011 р..
        /// </summary>
        internal static string FormulaBudgPayments2011Q3 {
            get {
                return ResourceManager.GetString("FormulaBudgPayments2011Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума відрахувань частки прибутку до бюджету за 2012 р..
        /// </summary>
        internal static string FormulaBudgPayments2012 {
            get {
                return ResourceManager.GetString("FormulaBudgPayments2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума відрахувань частки прибутку до бюджету за I кв. 2012 р..
        /// </summary>
        internal static string FormulaBudgPayments2012Q1 {
            get {
                return ResourceManager.GetString("FormulaBudgPayments2012Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума відрахувань частки прибутку до бюджету за II кв. 2012 р..
        /// </summary>
        internal static string FormulaBudgPayments2012Q2 {
            get {
                return ResourceManager.GetString("FormulaBudgPayments2012Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума відрахувань частки прибутку до бюджету за III кв. 2012 р..
        /// </summary>
        internal static string FormulaBudgPayments2012Q3 {
            get {
                return ResourceManager.GetString("FormulaBudgPayments2012Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Норматив відрахувань частки прибутку до бюджету на {0}.
        /// </summary>
        internal static string FormulaBudgPaymentsRate {
            get {
                return ResourceManager.GetString("FormulaBudgPaymentsRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чистий прибуток/збиток за .
        /// </summary>
        internal static string FormulaClearIncome {
            get {
                return ResourceManager.GetString("FormulaClearIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість активів на 01.01.2011.
        /// </summary>
        internal static string FormulaCostActives2010 {
            get {
                return ResourceManager.GetString("FormulaCostActives2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість активів на 01.04.2010.
        /// </summary>
        internal static string FormulaCostActives2010Q1 {
            get {
                return ResourceManager.GetString("FormulaCostActives2010Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість активів на 01.07.2010.
        /// </summary>
        internal static string FormulaCostActives2010Q2 {
            get {
                return ResourceManager.GetString("FormulaCostActives2010Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість активів на 01.10.2010.
        /// </summary>
        internal static string FormulaCostActives2010Q3 {
            get {
                return ResourceManager.GetString("FormulaCostActives2010Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість активів на 01.01.2012.
        /// </summary>
        internal static string FormulaCostActives2011 {
            get {
                return ResourceManager.GetString("FormulaCostActives2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість активів на 01.04.2011.
        /// </summary>
        internal static string FormulaCostActives2011Q1 {
            get {
                return ResourceManager.GetString("FormulaCostActives2011Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість активів на 01.07.2011.
        /// </summary>
        internal static string FormulaCostActives2011Q2 {
            get {
                return ResourceManager.GetString("FormulaCostActives2011Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість активів на 01.10.2011.
        /// </summary>
        internal static string FormulaCostActives2011Q3 {
            get {
                return ResourceManager.GetString("FormulaCostActives2011Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість активів на 01.01.2013.
        /// </summary>
        internal static string FormulaCostActives2012 {
            get {
                return ResourceManager.GetString("FormulaCostActives2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість активів на 01.04.2012.
        /// </summary>
        internal static string FormulaCostActives2012Q1 {
            get {
                return ResourceManager.GetString("FormulaCostActives2012Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість активів на 01.07.2012.
        /// </summary>
        internal static string FormulaCostActives2012Q2 {
            get {
                return ResourceManager.GetString("FormulaCostActives2012Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вартість активів на 01.10.2012.
        /// </summary>
        internal static string FormulaCostActives2012Q3 {
            get {
                return ResourceManager.GetString("FormulaCostActives2012Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кредиторська заборгованість станом на .
        /// </summary>
        internal static string FormulaCreditDebt {
            get {
                return ResourceManager.GetString("FormulaCreditDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дебіторська заборгованість на .
        /// </summary>
        internal static string FormulaDebitDebt {
            get {
                return ResourceManager.GetString("FormulaDebitDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Довгострокові кредити банків станом на .
        /// </summary>
        internal static string FormulaDovgBankCredit {
            get {
                return ResourceManager.GetString("FormulaDovgBankCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Довгострокові зобов&apos;язання станом на .
        /// </summary>
        internal static string FormulaDovgZobov {
            get {
                return ResourceManager.GetString("FormulaDovgZobov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Довгострокова дебіторська заборгованість на .
        /// </summary>
        internal static string FormulaLongDebitDebt {
            get {
                return ResourceManager.GetString("FormulaLongDebitDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на перший квартал {0} р..
        /// </summary>
        internal static string FormulaNameQ1 {
            get {
                return ResourceManager.GetString("FormulaNameQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на другий квартал {0} р..
        /// </summary>
        internal static string FormulaNameQ2 {
            get {
                return ResourceManager.GetString("FormulaNameQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на третій квартал {0} р..
        /// </summary>
        internal static string FormulaNameQ3 {
            get {
                return ResourceManager.GetString("FormulaNameQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} рік.
        /// </summary>
        internal static string FormulaNameYear {
            get {
                return ResourceManager.GetString("FormulaNameYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поточні зобов&apos;язання станом на .
        /// </summary>
        internal static string FormulaPotochZobov {
            get {
                return ResourceManager.GetString("FormulaPotochZobov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибуток-збиток факт. за .
        /// </summary>
        internal static string FormulaPributokZbitokFact {
            get {
                return ResourceManager.GetString("FormulaPributokZbitokFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Короткострокові кредити банків станом на .
        /// </summary>
        internal static string FormulaShortBankCredit {
            get {
                return ResourceManager.GetString("FormulaShortBankCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загальний обсяг доходів за .
        /// </summary>
        internal static string FormulaTotalDohod {
            get {
                return ResourceManager.GetString("FormulaTotalDohod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сукупні доходи (без ПДВ) за 2012 р..
        /// </summary>
        internal static string FormulaTotalIncome2012 {
            get {
                return ResourceManager.GetString("FormulaTotalIncome2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://185.151.105.59/gukv.
        /// </summary>
        internal static string GlobalWebSiteURL {
            get {
                return ResourceManager.GetString("GlobalWebSiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛЕСІ УКРАЇНКИ БУЛЬВ..
        /// </summary>
        internal static string LesiUkrainkiCorrect {
            get {
                return ResourceManager.GetString("LesiUkrainkiCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛЕСІ УКРАЇНКИ.
        /// </summary>
        internal static string LesiUkrainkiShort {
            get {
                return ResourceManager.GetString("LesiUkrainkiShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А.
        /// </summary>
        internal static string LiteraA {
            get {
                return ResourceManager.GetString("LiteraA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МАЙНОВИЙ КОМПЛЕКС.
        /// </summary>
        internal static string NJFPurposeGroupComplex {
            get {
                return ResourceManager.GetString("NJFPurposeGroupComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НЕЗАВЕРШЕНЕ БУДІВНИЦТВО.
        /// </summary>
        internal static string NJFPurposeGroupNezavershene {
            get {
                return ResourceManager.GetString("NJFPurposeGroupNezavershene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НЕЖИЛІ БУДІВЛІ.
        /// </summary>
        internal static string NJFPurposeGroupNezhili {
            get {
                return ResourceManager.GetString("NJFPurposeGroupNezhili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НЕЖИТЛОВІ.
        /// </summary>
        internal static string NJFPurposeGroupNezhitlovi {
            get {
                return ResourceManager.GetString("NJFPurposeGroupNezhitlovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПІДПРИЄМСТВО.
        /// </summary>
        internal static string NJFPurposeGroupPidpr {
            get {
                return ResourceManager.GetString("NJFPurposeGroupPidpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доп. Адреса.
        /// </summary>
        internal static string NJFUnmatchedObjAddrMisc {
            get {
                return ResourceManager.GetString("NJFUnmatchedObjAddrMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        internal static string NJFUnmatchedObjID {
            get {
                return ResourceManager.GetString("NJFUnmatchedObjID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер.
        /// </summary>
        internal static string NJFUnmatchedObjNomer1 {
            get {
                return ResourceManager.GetString("NJFUnmatchedObjNomer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер 2.
        /// </summary>
        internal static string NJFUnmatchedObjNomer2 {
            get {
                return ResourceManager.GetString("NJFUnmatchedObjNomer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер 3.
        /// </summary>
        internal static string NJFUnmatchedObjNomer3 {
            get {
                return ResourceManager.GetString("NJFUnmatchedObjNomer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вулиця.
        /// </summary>
        internal static string NJFUnmatchedObjStreet {
            get {
                return ResourceManager.GetString("NJFUnmatchedObjStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А БЛОК А.
        /// </summary>
        internal static string NumberAblockA {
            get {
                return ResourceManager.GetString("NumberAblockA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А/А.
        /// </summary>
        internal static string NumberAslashA {
            get {
                return ResourceManager.GetString("NumberAslashA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВНУТРІШНЬОКВАРТАЛЬНЕ.
        /// </summary>
        internal static string ObjectTypeInBlock {
            get {
                return ResourceManager.GetString("ObjectTypeInBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВБУДОВАНЕ ПРИМІЩ..
        /// </summary>
        internal static string ObjectTypeInBuilt {
            get {
                return ResourceManager.GetString("ObjectTypeInBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ІНШІ.
        /// </summary>
        internal static string ObjectTypeOther {
            get {
                return ResourceManager.GetString("ObjectTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розпорядження КМДА.
        /// </summary>
        internal static string OrderTopicKMDADefault {
            get {
                return ResourceManager.GetString("OrderTopicKMDADefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДЕПУТАТ.
        /// </summary>
        internal static string OrgKindDeputy {
            get {
                return ResourceManager.GetString("OrgKindDeputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МАЛЕ ПІДПРИЄМСТВО.
        /// </summary>
        internal static string OrgKindSmallBusiness {
            get {
                return ResourceManager.GetString("OrgKindSmallBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адреса об&apos;єкту в БД &quot;1НФ&quot;.
        /// </summary>
        internal static string PrivatCSVLogAddr1NF {
            get {
                return ResourceManager.GetString("PrivatCSVLogAddr1NF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адреса об&apos;єкту в БД &quot;Приватизація&quot;.
        /// </summary>
        internal static string PrivatCSVLogAddrPrivat {
            get {
                return ResourceManager.GetString("PrivatCSVLogAddrPrivat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А.
        /// </summary>
        internal static string PrivatGroupCodeA {
            get {
                return ResourceManager.GetString("PrivatGroupCodeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Е.
        /// </summary>
        internal static string PrivatGroupCodeE {
            get {
                return ResourceManager.GetString("PrivatGroupCodeE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол засідання комісії.
        /// </summary>
        internal static string ProtocolTopicDefault {
            get {
                return ResourceManager.GetString("ProtocolTopicDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол засідання міської комісії.
        /// </summary>
        internal static string ProtocolTopicForCity {
            get {
                return ResourceManager.GetString("ProtocolTopicForCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Протокол засідання постійної комісії.
        /// </summary>
        internal static string ProtocolTopicForConstCommitty {
            get {
                return ResourceManager.GetString("ProtocolTopicForConstCommitty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОСП..
        /// </summary>
        internal static string RentPaymentStreetTypeAvenue {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeAvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОС.
        /// </summary>
        internal static string RentPaymentStreetTypeAvenue1 {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeAvenue1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРСП.
        /// </summary>
        internal static string RentPaymentStreetTypeAvenue2 {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeAvenue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПР..
        /// </summary>
        internal static string RentPaymentStreetTypeAvenue3 {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeAvenue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПР-Т.
        /// </summary>
        internal static string RentPaymentStreetTypeAvenue4 {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeAvenue4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРТ.
        /// </summary>
        internal static string RentPaymentStreetTypeAvenue5 {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeAvenue5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БУЛЬВ..
        /// </summary>
        internal static string RentPaymentStreetTypeBoulevard {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeBoulevard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БУЛ.
        /// </summary>
        internal static string RentPaymentStreetTypeBoulevard1 {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeBoulevard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОВ..
        /// </summary>
        internal static string RentPaymentStreetTypeLane {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОВ.
        /// </summary>
        internal static string RentPaymentStreetTypeLane1 {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeLane1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЛ..
        /// </summary>
        internal static string RentPaymentStreetTypeSquare {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЛ.
        /// </summary>
        internal static string RentPaymentStreetTypeSquare1 {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeSquare1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УЗВІЗ.
        /// </summary>
        internal static string RentPaymentStreetTypeUzviz {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeUzviz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УЗВ.
        /// </summary>
        internal static string RentPaymentStreetTypeUzviz1 {
            get {
                return ResourceManager.GetString("RentPaymentStreetTypeUzviz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///Шановний користистувач веб-сайту ДКВ!
        ///
        ///Повідомляємо Вам, що згідно документу: {0} № {1} від {2} на баланс організації {3} передано {4} кв.м. за адресою: {5}
        ///
        ///Адреса веб-сайту ДКВ, який Ви можете використовувати для заповненния звітності з використання комунальної власності: {6}.
        /// </summary>
        internal static string Report1NFObjectAddedBody {
            get {
                return ResourceManager.GetString("Report1NFObjectAddedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повідомлення про прийняття на баланс нового об&apos;єкту нерухомого майна.
        /// </summary>
        internal static string Report1NFObjectAddedTitle {
            get {
                return ResourceManager.GetString("Report1NFObjectAddedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///Шановний користистувач веб-сайту ДКВ!
        ///
        ///Повідомляємо Вам, що згідно документу: {0} № {1} від {2} з балансу організації {3} знято {4} кв.м. за адресою: {5}
        ///
        ///Адреса веб-сайту ДКВ, який Ви можете використовувати для заповненния звітності з використання комунальної власності: {6}.
        /// </summary>
        internal static string Report1NFObjectRemovedBody {
            get {
                return ResourceManager.GetString("Report1NFObjectRemovedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повідомлення про зняття об&apos;єкту нерухомого майна з балансу.
        /// </summary>
        internal static string Report1NFObjectRemovedTitle {
            get {
                return ResourceManager.GetString("Report1NFObjectRemovedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на кв.м..
        /// </summary>
        internal static string SquareMeters {
            get {
                return ResourceManager.GetString("SquareMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СОРОКАРІЧЧЯ ЖОВТНЯ.
        /// </summary>
        internal static string Street40LetOkt {
            get {
                return ResourceManager.GetString("Street40LetOkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АНТОНОВА АВІАКОНСТРУКТОРА.
        /// </summary>
        internal static string StreetAntonovaAvia {
            get {
                return ResourceManager.GetString("StreetAntonovaAvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АНТОНОВА-ОВСІЄНКА.
        /// </summary>
        internal static string StreetAntonovaOvs {
            get {
                return ResourceManager.GetString("StreetAntonovaOvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АНТОНОВА.
        /// </summary>
        internal static string StreetAntonovaShort {
            get {
                return ResourceManager.GetString("StreetAntonovaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БЕХТЕРЕВСЬКИЙ.
        /// </summary>
        internal static string StreetBehterevskyy {
            get {
                return ResourceManager.GetString("StreetBehterevskyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БОРИСП.
        /// </summary>
        internal static string StreetBoryspil {
            get {
                return ResourceManager.GetString("StreetBoryspil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДЕГТЯРІВСЬКА.
        /// </summary>
        internal static string StreetDegtarivska {
            get {
                return ResourceManager.GetString("StreetDegtarivska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДНІПРОДЗЕРЖИНСЬКА.
        /// </summary>
        internal static string StreetDniprodz {
            get {
                return ResourceManager.GetString("StreetDniprodz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФРАНКА.
        /// </summary>
        internal static string StreetFranka {
            get {
                return ResourceManager.GetString("StreetFranka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГЛУШКОВА.
        /// </summary>
        internal static string StreetGlushkova {
            get {
                return ResourceManager.GetString("StreetGlushkova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГОРЬКОГО.
        /// </summary>
        internal static string StreetGorkogo {
            get {
                return ResourceManager.GetString("StreetGorkogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ХАРКІВСЬКЕ.
        /// </summary>
        internal static string StreetHarkivske {
            get {
                return ResourceManager.GetString("StreetHarkivske", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ІЛЛІНСЬКА.
        /// </summary>
        internal static string StreetIllinska {
            get {
                return ResourceManager.GetString("StreetIllinska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОСП..
        /// </summary>
        internal static string StreetKindAvenueCorrect {
            get {
                return ResourceManager.GetString("StreetKindAvenueCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БУЛЬВ..
        /// </summary>
        internal static string StreetKindBoulevardCorrect {
            get {
                return ResourceManager.GetString("StreetKindBoulevardCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОВ..
        /// </summary>
        internal static string StreetKindLaneCorrect {
            get {
                return ResourceManager.GetString("StreetKindLaneCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЛ..
        /// </summary>
        internal static string StreetKindSquareCorrect {
            get {
                return ResourceManager.GetString("StreetKindSquareCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КОМАРОВА.
        /// </summary>
        internal static string StreetKomarova {
            get {
                return ResourceManager.GetString("StreetKomarova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КОПИЛІВСЬКА.
        /// </summary>
        internal static string StreetKopylivska {
            get {
                return ResourceManager.GetString("StreetKopylivska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КОТЕЛЬНИКОВА.
        /// </summary>
        internal static string StreetKotelnikova {
            get {
                return ResourceManager.GetString("StreetKotelnikova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КУРЕНІВСЬКА.
        /// </summary>
        internal static string StreetKurenivska {
            get {
                return ResourceManager.GetString("StreetKurenivska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НАБЕРЕЖНО-ПЕЧЕРСЬКА ДОРОГА.
        /// </summary>
        internal static string StreetNaberezhnoPechDoroga {
            get {
                return ResourceManager.GetString("StreetNaberezhnoPechDoroga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОВСІЄНКА.
        /// </summary>
        internal static string StreetOvsienkaShort {
            get {
                return ResourceManager.GetString("StreetOvsienkaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПАРК ІМ. ПУШКІНА О.С..
        /// </summary>
        internal static string StreetParkPushkina {
            get {
                return ResourceManager.GetString("StreetParkPushkina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РУСТАВЕЛІ.
        /// </summary>
        internal static string StreetRustaveli {
            get {
                return ResourceManager.GetString("StreetRustaveli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВУЛ..
        /// </summary>
        internal static string StreetSuffix1 {
            get {
                return ResourceManager.GetString("StreetSuffix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВУЛ.
        /// </summary>
        internal static string StreetSuffix2 {
            get {
                return ResourceManager.GetString("StreetSuffix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БУЛЬВ..
        /// </summary>
        internal static string StreetSuffixBulv {
            get {
                return ResourceManager.GetString("StreetSuffixBulv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОСП..
        /// </summary>
        internal static string StreetSuffixProsp {
            get {
                return ResourceManager.GetString("StreetSuffixProsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОВ..
        /// </summary>
        internal static string StreetSuffixProv {
            get {
                return ResourceManager.GetString("StreetSuffixProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОВІТРОФЛОТСЬКИЙ ПРОСП..
        /// </summary>
        internal static string StreetVozduhoflotskyyProsp {
            get {
                return ResourceManager.GetString("StreetVozduhoflotskyyProsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОВІТРОФЛОТСЬКИЙ ПРОВ..
        /// </summary>
        internal static string StreetVozduhoflotskyyProv {
            get {
                return ResourceManager.GetString("StreetVozduhoflotskyyProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЖУКОВА.
        /// </summary>
        internal static string StreetZhukova {
            get {
                return ResourceManager.GetString("StreetZhukova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повне і&apos;мя.
        /// </summary>
        internal static string UncategorizedOrgFullName {
            get {
                return ResourceManager.GetString("UncategorizedOrgFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        internal static string UncategorizedOrgID {
            get {
                return ResourceManager.GetString("UncategorizedOrgID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категорія відома.
        /// </summary>
        internal static string UncategorizedOrgIsCategorized {
            get {
                return ResourceManager.GetString("UncategorizedOrgIsCategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коротке і&apos;мя.
        /// </summary>
        internal static string UncategorizedOrgShortName {
            get {
                return ResourceManager.GetString("UncategorizedOrgShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗКПО.
        /// </summary>
        internal static string UncategorizedOrgZKPO {
            get {
                return ResourceManager.GetString("UncategorizedOrgZKPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на район.
        /// </summary>
        internal static string ValidationAddrDistrict {
            get {
                return ResourceManager.GetString("ValidationAddrDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на номер будинку.
        /// </summary>
        internal static string ValidationAddrNumber {
            get {
                return ResourceManager.GetString("ValidationAddrNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на загальна площа, житлова площа, нежитлова площа.
        /// </summary>
        internal static string ValidationAddrSquare {
            get {
                return ResourceManager.GetString("ValidationAddrSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на назва вулиці.
        /// </summary>
        internal static string ValidationAddrStreet {
            get {
                return ResourceManager.GetString("ValidationAddrStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на балансоутримувач.
        /// </summary>
        internal static string ValidationArendaBalansHolder {
            get {
                return ResourceManager.GetString("ValidationArendaBalansHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на орендодавець.
        /// </summary>
        internal static string ValidationArendaGiver {
            get {
                return ResourceManager.GetString("ValidationArendaGiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на адреса.
        /// </summary>
        internal static string ValidationArendaObject {
            get {
                return ResourceManager.GetString("ValidationArendaObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на орендна плата.
        /// </summary>
        internal static string ValidationArendaPayment {
            get {
                return ResourceManager.GetString("ValidationArendaPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на орендар.
        /// </summary>
        internal static string ValidationArendaRenter {
            get {
                return ResourceManager.GetString("ValidationArendaRenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на орендована площа.
        /// </summary>
        internal static string ValidationArendaSquare {
            get {
                return ResourceManager.GetString("ValidationArendaSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дата початку оренди.
        /// </summary>
        internal static string ValidationArendaStart {
            get {
                return ResourceManager.GetString("ValidationArendaStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на нежитлова площа.
        /// </summary>
        internal static string ValidationBalansNonHabitSqr {
            get {
                return ResourceManager.GetString("ValidationBalansNonHabitSqr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на адреса.
        /// </summary>
        internal static string ValidationBalansObject {
            get {
                return ResourceManager.GetString("ValidationBalansObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на балансоутримувач.
        /// </summary>
        internal static string ValidationBalansOrg {
            get {
                return ResourceManager.GetString("ValidationBalansOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на призначення.
        /// </summary>
        internal static string ValidationBalansPurpose {
            get {
                return ResourceManager.GetString("ValidationBalansPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на група призначення.
        /// </summary>
        internal static string ValidationBalansPurposeGroup {
            get {
                return ResourceManager.GetString("ValidationBalansPurposeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на загальна площа.
        /// </summary>
        internal static string ValidationBalansTotalSqr {
            get {
                return ResourceManager.GetString("ValidationBalansTotalSqr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необхідно заповнити показники для договору оренди: {0}.
        /// </summary>
        internal static string ValidationMsgArendaIncomplete {
            get {
                return ResourceManager.GetString("ValidationMsgArendaIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необхідно заповнити показники для об&apos;єкту на балансі: {0}.
        /// </summary>
        internal static string ValidationMsgBalansIncomplete {
            get {
                return ResourceManager.GetString("ValidationMsgBalansIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надто велике відхилення нежитлової площі об&apos;єкту: було {0}, стало {1}.
        /// </summary>
        internal static string ValidationMsgBalansNonHabitSquareMismatch {
            get {
                return ResourceManager.GetString("ValidationMsgBalansNonHabitSquareMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надто велике відхилення загальної площі об&apos;єкту: було {0}, стало {1}.
        /// </summary>
        internal static string ValidationMsgBalansTotalSquareMismatch {
            get {
                return ResourceManager.GetString("ValidationMsgBalansTotalSquareMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Надто велике відхилення площі будинку: було {0}, стало {1}.
        /// </summary>
        internal static string ValidationMsgObjDiffSqr {
            get {
                return ResourceManager.GetString("ValidationMsgObjDiffSqr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необхідно заповнити показники для будинку: {0}.
        /// </summary>
        internal static string ValidationMsgObjIncomplete {
            get {
                return ResourceManager.GetString("ValidationMsgObjIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необхідно заповнити показники для організації: {0}.
        /// </summary>
        internal static string ValidationMsgOrgIncomplete {
            get {
                return ResourceManager.GetString("ValidationMsgOrgIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В організації з кодом ЄДРПОУ {0} не співпадає: {1}.
        /// </summary>
        internal static string ValidationMsgOrgMismatch {
            get {
                return ResourceManager.GetString("ValidationMsgOrgMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необхідно заповнити додаткові показники для організації: {0}.
        /// </summary>
        internal static string ValidationMsgOrgNoAdditionalInfo {
            get {
                return ResourceManager.GetString("ValidationMsgOrgNoAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відомості про об&apos;єкт не заповнені.
        /// </summary>
        internal static string ValidationNoObjectInfo {
            get {
                return ResourceManager.GetString("ValidationNoObjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відомості про організацію не заповнені.
        /// </summary>
        internal static string ValidationNoOrgInfo {
            get {
                return ResourceManager.GetString("ValidationNoOrgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на вид діяльності.
        /// </summary>
        internal static string ValidationOrgActivity {
            get {
                return ResourceManager.GetString("ValidationOrgActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код ЄДРПОУ {0} дублюється в базі 1НФ. Неможливо виконати однозначне співставлення організації.
        /// </summary>
        internal static string ValidationOrgDuplicateZKPO {
            get {
                return ResourceManager.GetString("ValidationOrgDuplicateZKPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на галузь.
        /// </summary>
        internal static string ValidationOrgIndustry {
            get {
                return ResourceManager.GetString("ValidationOrgIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на повна назва.
        /// </summary>
        internal static string ValidationOrgName {
            get {
                return ResourceManager.GetString("ValidationOrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на форма власності.
        /// </summary>
        internal static string ValidationOrgOwnership {
            get {
                return ResourceManager.GetString("ValidationOrgOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на код ЄДРПОУ.
        /// </summary>
        internal static string ValidationOrgZKPO {
            get {
                return ResourceManager.GetString("ValidationOrgZKPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Договір оренди № {0} від {1}.
        /// </summary>
        internal static string ValidationRentAgreementDescr {
            get {
                return ResourceManager.GetString("ValidationRentAgreementDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Орендар:.
        /// </summary>
        internal static string ValidationRentAgreementRenter {
            get {
                return ResourceManager.GetString("ValidationRentAgreementRenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невідомий код вулиці.
        /// </summary>
        internal static string ValidationUnknownStreetCode {
            get {
                return ResourceManager.GetString("ValidationUnknownStreetCode", resourceCulture);
            }
        }
    }
}
