//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUKV.DataMigration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ</string>
  <string>АТ З ОБМЕЖ.ВІДПОВ.</string>
  <string>АТ З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ</string>
  <string>СПІЛЬНЕ ПІДПРИЄМСТВО ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ</string>
  <string>СП УКР.-АМЕР.ПІДПРИЄМСТВО У ФОРМІ ТОВ</string>
  <string>УКРАЇНСЬКО-ЛИТОВСЬКЕ СП У ФОРМІ ТОВ</string>
  <string>СПІЛЬНЕ ПІДПРИЄМСТВО У ФОРМІ ТОВАРИСТВА З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ</string>
  <string>СПІЛЬНЕ УКРАЇНСЬКО-АМЕРИКАНСЬКЕ ПІДПРИЄМСТВО ТОВ</string>
  <string>УКРАЇНСЬКО-РОСІЙСЬКЕ СЕРВІСНО-ВИРОБНИЧЕ І ТОРГІВЕЛЬНЕ ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ</string>
  <string>УКРАЇНСЬКО-ШВЕДСЬКО-РОСІЙСЬКЕ МЕДИЧНЕ СПІЛЬНЕ ПІДПРИЄМСТВО У ФОРМІ ТОВАРИСТВА З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ</string>
  <string>СПІЛЬНЕ УКРАЇНСЬКО-СІРІЙСЬКЕ ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ</string>
  <string>УКРАЇНСЬКО-НІМЕЦЬКЕ СПІЛЬНЕ ПІДПРИЄМСТВО У ФОРМІ ТОВАРИСТВА З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ</string>
  <string>УКРАЇНСЬКО-ІТАЛІЙСЬКЕ ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ</string>
  <string>УКР.-ІТАЛІЙСЬКЕ ТОВ.</string>
  <string>УКР.-НІДЕРЛАНДСЬКЕ ТОВ</string>
  <string>УКРАЇНСЬКО-НІДЕРЛАНДСЬКЕ ТОВ</string>
  <string>СП ТОВ</string>
  <string>ТОВ </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameTOV {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameTOV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ЧЛЕН КОНСХУ</string>
  <string>ЧЛЕН НАЦІОНАЛЬНОЇ СПІЛКИ ХУДОЖНИКІВ УКРАЇНИ ХУДОЖНИК</string>
  <string>ХУДОЖНИК-ДИЗАЙНЕР</string>
  <string>ХУДОЖНИК-АРХІТЕКТОР</string>
  <string>ХУДОЖНИК-ГРАФІК</string>
  <string>ХУДОЖНИК-ЕМАЛЬЄР</string>
  <string>ХУДОЖНИК-КЕРАМІСТ</string>
  <string>ХУДОЖНИК-МОНУМЕНТАЛІСТ</string>
  <string>ХУДОЖНИК-ОФОРМЛЮВАЧ</string>
  <string>ХУДОЖНИК-ОФОРМЛ.</string>
  <string>ХУДОЖНИК-ПРОЕКТАНТ</string>
  <string>ХУДОЖНИК-РЕСТАВРАТОР</string>
  <string>ХУДОЖНИК-СКУЛЬПТОР</string>
  <string>ЧЛЕН СПІЛКИ ХУДОЖНИКІВ УКРАЇНИ</string>
  <string>ЧЛЕН СПІЛКИ КИЇВСЬКОГО МІСЬКОГО ОБ'ЄДНАННЯ ХУДОЖНИКІВ-АМАТОРІВ ""ТВОРЧІСТЬ""</string>
  <string>ЧЛЕН СПІЛКИ КОНСХУ</string>
  <string>ЧЛЕН ТВОРЧОГО СОЮЗУ ХУДОЖНИКІВ ХУДОЖНИК</string>
  <string>ЧЛЕН КИЇВСЬКОЇ ОРГАНІЗАЦІЇ НАЦІОНАЛЬНОЇ СПІЛКИ ХУДОЖНИКІВ</string>
  <string>ЧЛЕН ХУДОЖНИК</string>
  <string>ЧЛЕН НАЦІОНАЛЬНОЇ СПІЛКИ ХУДОЖНИКІВ УКРАЇНИ</string>
  <string>ХУДОЖНИК</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNamePainters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNamePainters"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>УКРАЇНСЬКО-АВСТРІЙСЬКЕ СПІЛЬНЕ ПІДПРИЄМСТВО</string>\r\n  <string>УКРАЇНСЬКО" +
            "-АВСТРІЙСЬКЕ СП</string>\r\n  <string>СПІЛЬНЕ УКРАЇНСЬКО-КАНАДСЬКЕ ПІДПРИЄМСТВО</s" +
            "tring>\r\n  <string>УКРАЇНСЬКО-ІНДІЙСЬКЕ СП</string>\r\n  <string>УКРАЇНСЬКО-АМЕРИКА" +
            "НСЬКЕ СП</string>\r\n  <string>УКРАЇНСЬКО-АМЕРИКАНСЬКЕ СПІЛЬНЕ ПІДПРИЄМСТВО</strin" +
            "g>\r\n  <string>УКРАЇНСЬКО-БІЛОРУСЬКЕ СПІЛЬНЕ ПІДПРИЄМСТВО</string>\r\n  <string>УКР" +
            "АЇНСЬКО-БІЛОРУСЬКЕ ПІДПРИЄМСТВО</string>\r\n  <string>УКРАЇНСЬКО-БІЛОРУС. СП</stri" +
            "ng>\r\n  <string>УКРАЇНСЬКО-БІЛОРУС.П-ВО</string>\r\n  <string>УКРАЇНСЬКО-ЛИТОВСЬКЕ " +
            "ПІДПРИЄМСТВО</string>\r\n  <string>УКРАЇНСЬКО-ТУРЕЦЬКА ФІРМА</string>\r\n  <string>У" +
            "КРАЇНСЬКО-СЛОВАЦЬКЕ СП</string>\r\n  <string>УКРАЇНСЬКО-УГОРСЬКЕ СП</string>\r\n  <s" +
            "tring>УКРАЇНСЬКО-ЧЕШСЬКЕ СП</string>\r\n  <string>СПІЛЬНЕ РАДЯНСЬКО-АМЕРИКАНСЬКЕ П" +
            "ІДПРИЄМСТВО</string>\r\n  <string>СПІЛЬНЕ УКРАЇНСЬКО-РОСІЙСЬКО-УГОРСЬКО- НІМЕЦЬКЕ " +
            "ПІДПРИЄМСТВО</string>\r\n  <string>СПІЛЬНЕ УКРАЇНСЬКО-РОСІЙСЬКЕ ПІДПРИЄМСТВО</stri" +
            "ng>\r\n  <string>СПІЛЬНЕ ПІДПРИЄМСТВО УКРАЇНСЬКО-ТУРЕЦЬКЕ</string>\r\n  <string>СПІЛ" +
            "ЬНЕ УКРАЇНСЬКО-АМЕРИКАНСЬКЕ ПІДПРИЄМСТВО</string>\r\n  <string>СПІЛЬНЕ УКРАЇНСЬКО-" +
            "НІМЕЦЬКЕ ПІДПРИЄМСТВО</string>\r\n  <string>УКРАЇНСЬКО-ПОЛЬСЬКЕ СП</string>\r\n  <st" +
            "ring>СПІЛЬНЕ ПІДПРИЄМСТВО ФІРМА</string>\r\n  <string>СПІЛЬНЕ УКРАЇНСЬКО-НІМЕЦЬКО-" +
            "АМЕРИКАНСЬКЕ ПІДПРИЄМСТВО</string>\r\n  <string>СПІЛЬНЕ УКРАЇНСЬКО-АМЕРИКАНСЬКЕ ГО" +
            "ТЕЛЬНО-ОФІСНЕ ПІДПРИЄМСТВО</string>\r\n  <string>СПІЛЬНЕ УКРАЇНСЬКО-ШВЕЙЦАРСЬКЕ ПІ" +
            "ДПРИЄМСТВО</string>\r\n  <string>СПІЛЬНЕ УКРАЇНСЬКО-МОЛДАВСЬКЕ ПІДПРИЄМСТВО</strin" +
            "g>\r\n  <string>СПІЛЬНЕ УКРАЇНСЬКО-ІЗРАЇЛЬСЬКЕ ПІДПРИЄМСТВО</string>\r\n  <string>СП" +
            "ІЛЬНЕ УКРАЇНО-ІСПАНСЬКЕ ПІДПРИЄМСТВО</string>\r\n  <string>СПІЛЬНЕ УКРАЇНСЬКО-БРИТ" +
            "АНСЬКЕ ПІДПРИЄМСТВО</string>\r\n  <string>СПІЛЬНЕ УКРАЇНСЬКО-ПОЛЬСЬКЕ ПІДПРИЄМСТВО" +
            "</string>\r\n  <string>УКРАЇНСЬКО-ГЕРМАНСЬКА ФІРМА</string>\r\n  <string>УКРАЇНСЬКО-" +
            "АМЕРИКАНСЬКЕ ПІДПРИЄМСТВО</string>\r\n  <string>УКРАЇНСЬКО-ЮГОСЛАВСЬКЕ СП</string>" +
            "\r\n  <string>УКРАЇНСЬКО-БРИТАНСЬКЕ СП</string>\r\n  <string>УКРАЇНСЬКО-ВЕНГЕРСЬКЕ П" +
            "ІДПРИЄМСТВО</string>\r\n  <string>УКРАЇНСЬКО-ІТАЛІЙСЬКЕ СПІЛЬНЕ ПІДПРИЄМСТВО</stri" +
            "ng>\r\n  <string>СПІЛЬНЕ УКРАЇНСЬКО-БЕЛЬГІЙСЬКЕ ПІДПРИЄМСТВО</string>\r\n  <string>С" +
            "УСПІЛЬНЕ ПІДПРИЄМСТВО</string>\r\n  <string>СПІЛЬНЕ ПІДПРИЄМСТВО</string>\r\n  <stri" +
            "ng>СПІЛЬНЕ ВИРОБНИЧЕ ПІДПРИЄМСТВО</string>\r\n  <string>СПІЛЬНЕ НАУКОВО-ВИРОБНИЧЕ " +
            "ПІДПРИЄМСТВО</string>\r\n  <string>УКРАЇНСЬКО-НІМЕЦЬКЕ СПІЛЬНЕ ПІДПРИЄМСТВО</strin" +
            "g>\r\n  <string>УКРАЇНСЬКО-НІМЕЦЬКЕ КОМЕРЦІЙНЕ ПІДПРИЄМСТВО</string>\r\n  <string>УК" +
            "Р.-НІМЕЦЬКЕ КОМЕРЦІЙНЕ П-ВО</string>\r\n  <string>УКРАЇНСЬКО-НІМЕЦЬКЕ ПІДПРИЄМСТВО" +
            "</string>\r\n  <string>УКР.-НІМ. СПІЛ. ПІДПР.ТОВ</string>\r\n  <string>УКР.-НІМЕЦ. П" +
            "ІДПР.</string>\r\n  <string>УКР.-НІМ.СП</string>\r\n  <string>СП </string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameSP {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameSP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ПРИВАТНО-ВИРОБНИЧЕ ПІДПРИЄМСТВО</string>
  <string>ПРИВАТНЕ ВИРОБНИЧЕ ПІДПРИЄМСТВО </string>
  <string>ПІДПРИЄМСТВО З ІНОЗЕМНИМ КАПІТАЛОМ</string>
  <string>ПІДПРИЄМСТВО З ІНОЗЕМНИМИ ІНВЕСТИЦІЯМИ</string>
  <string>ПРИВАТНЕ ВИРОБНИЧО-КОМЕРЦІЙНЕ ПІДПРИЄМСТВО</string>
  <string>ПРИВАТНА ВИРОБНИЧО-КОМЕРЦІЙНА ФІРМА</string>
  <string>ПРИВАТНЕ БАГАТОПРОФІЛЬНЕ ПІДПРИЄМСТВО</string>
  <string>ПРИВАТНЕ БАГАТОПРОФІЛЬНЕ МАЛЕ ПІДПРИЄМСТВО</string>
  <string>П-ВО З ІН.ІНВЕСТИЦІЯМИ</string>
  <string>П-ВО З ІНОЗ. ІНВЕСТИЦІЯМИ</string>
  <string>ПРИВАТНЕ ВТ ПІДПРИЄМСТВО </string>
  <string>ПІДПРИЄМСТВО</string>
  <string>ПРИВАТНЕ ПІДПРИЄМСТВО</string>
  <string>КОМЕРЦІЙНЕ ПІДПРИЄМСТВО</string>
  <string>ПРИВАТНА ФІРМА</string>
  <string>КОМЕРЦІЙНА ТУРИСТИЧНА ФІРМА</string>
  <string>КОМЕРЦІЙНА ФІРМА</string>
  <string>КОМПААНІЯ</string>
  <string>КОМПАНІЯ</string>
  <string>ФІРМА</string>
  <string>ПІДПР.</string>
  <string>ПІД-ВО</string>
  <string>ПВПП </string>
  <string>ПВТП </string>
  <string>ПВТФ </string>
  <string>ПВКФ </string>
  <string>ПВКП </string>
  <string>ПБМП </string>
  <string>ПБПП </string>
  <string>ПВП</string>
  <string>ПБП  </string>
  <string>ПП </string>
  <string>ПФ </string>
  <string>П </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNamePP {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNamePP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ФІЗИЧНА ОСОБА ПІДПРИЄМЕЦЬ</string>
  <string>ФІЗИЧНА ОСОБА  ПІДПРИЄМЕЦЬ</string>
  <string>ФІЗИЧНА ОСОБА- ПІДПРИЄМЕЦЬ</string>
  <string>ФІЗИЧНА ОСОБА-ПІДПРИЄМЕЦЬ</string>
  <string>ФІЗИЧНА ОСОБА - ПІДПРИЄМЕЦЬ</string>
  <string>СУБ'ЄКТ ПІДПРИЄМНИЦЬКОЇ ДІЯЛЬНОСТІ ФІЗИЧНА ОСОБА</string>
  <string>СУБ'ЄКТ ПІДПРИЄМНИЦЬКОЇ ДІЯЛЬНОСТІ -ФІЗИЧНА ОСОБА</string>
  <string>СУБ""ЄКТ ПІДПРИЄМНИЦЬКОЇ ДІЯЛЬНОСТІ - ФІЗИЧНА ОСОБА</string>
  <string>ФІЗИЧНА ОСОБА</string>
  <string>ПІДПРИЄМЕЦЬ</string>
  <string>ГРОМАДЯНИН</string>
  <string>ГРОМАДЯНКА</string>
  <string>СПД-ФО</string>
  <string>СПД-ФІЗИЧНА ОСОБА</string>
  <string>СПДФО</string>
  <string>ФО-П</string>
  <string>ФОП </string>
  <string>ФО </string>
  <string>СПД </string>
  <string>ГРН </string>
  <string>ГР-Н</string>
  <string>ГР-КА</string>
  <string>ГР.</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameFOP {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameFOP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>АДВОКАТСЬКА КОМПАНІЯ</string>
  <string>АДВОКАТСЬКА КОНТОРА</string>
  <string>АДВОКАТСЬКА ФІРМА</string>
  <string>АДВОКАТСЬКЕ БЮРО</string>
  <string>АДВОКАТСЬКЕ ОБ'ЄДНАННЯ</string>
  <string>АДВОКАЦЬКЕ ОБ'ЄДНАННЯ</string>
  <string>АДВОКАТСЬКЕ ОБ""ЄДНАННЯ</string>
  <string>АДВОКАТ.КОМПАНІЯ</string>
  <string>ОБ'ЄДНАННЯ АДВОКАТІВ</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameAdvBureau {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameAdvBureau"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>АКЦІОНЕРНИЙ ПОШТОВО-ПЕНСІЙНИЙ БАНК</string>
  <string>АКЦ. ПОШТОВО-ПЕНСІЙНИЙ БАНК</string>
  <string>АКЦІОНЕРНО-КОМЕРЦІЙНИЙ БАНК</string>
  <string>АКЦІОНЕРНО - КОМЕРЦІЙНИЙ БАНК</string>
  <string>АКЦІОНЕРНИЙ КОМЕРЦІЙНИЙ БАНК</string>
  <string>АКЦІОНЕРНИЙ КОМЕРЦ. БАНК</string>
  <string>АКЦІОНЕРНИЙ БАНК</string>
  <string>АК БАНК</string>
  <string>АКБ </string>
  <string>АБ </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameComBank {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameComBank"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ПРИВАТНИЙ АДВОКАТ</string>\r\n  <string>АДВОКАТ</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameAdvocate {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameAdvocate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ОБ'ЄДНАННЯ СПІВВЛАСНИКІВ БАГАТОКВАРТИРНИХ БУДИНКІВ</string>
  <string>ОБ'ЄДНАННЯ СПІВВЛАСНИКІВ БАГАТОПОВЕРХОВИХ БУДИНКІВ</string>
  <string>ОСББ</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameOSBB {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameOSBB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ПУБЛІЧНЕ АКЦІОНЕРНЕ ТОВАРИСТВО</string>
  <string>ВІДКРИТЕ АКЦІОНЕРНЕ ТОВАРИСТВО</string>
  <string>АКЦІОНЕРНЕ ТОВАРИСТВО ВІДКРИТОГО ТИПУ</string>
  <string>ПАТ </string>
  <string>ВАТ </string>
  <string>АТ ВТ</string>
  <string>АТВТ </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNamePAT {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNamePAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ЗАКРИТЕ АКЦІОНЕРНЕ ТОВАРИСТВО</string>
  <string>СПІЛЬНЕ ПІДПРИЄМСТВО У ФОРМІ ЗАКРИТОГО АКЦІОНЕРНОГО ТОВАРИСТВА</string>
  <string>СПІЛЬНЕ УКРАЇНСЬКО-АМЕРИКАНСЬКЕ ПІДПРИЄМСТВО У ФОРМІ ЗАКРИТОГО АКЦІОНЕРНОГО ТОВАРИСТВО</string>
  <string>СПІЛЬНЕ ПІДПРИЄМСТВО ЗАКРИТЕ АКЦІОНЕРНЕ ТОВАРИСТВО</string>
  <string>АКЦІОНЕРНЕ ТОВАРИСТВО ЗАКРИТОГО ТИПУ</string>
  <string>АКЦІОНЕРНЕ ОБ'ЄДНАННЯ ЗАКРИТЕ ТОВАРИСТВО</string>
  <string>СП У ФОРМІ ЗАТ</string>
  <string>СП ЗАТ</string>
  <string>ЗАТ </string>
  <string>АТ ЗТ</string>
  <string>АТЗТ </string>
  <string>АОЗТ </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameZAT {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameZAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ПІДПРИЄМСТВО ГРОМАДСЬКОЇ ОРГАНІЗАЦІЇ</string>
  <string>ВСЕУКРАЇНСЬКА ГРОМАДСЬКА ОРГАНІЗАЦІЯ</string>
  <string>МІЖНАРОДНА ГРОМАДСЬКА ОРГАНІЗАЦІЯ</string>
  <string>ГРОМАДСЬКА ОРГАНІЗАЦІЯ</string>
  <string>ПГО </string>
  <string>ГО </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameGromad {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameGromad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>КОМУНАЛЬНЕ ПІДПРИЄМСТВО</string>\r\n  <string>КП </string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection OrgNameKP {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameKP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ГОЛАНДСЬКИЙ КООПЕРАТИВ ФЕРМЕРІВ</string>
  <string>КООПЕРАТИВ</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameKoop {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameKoop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>АКЦІОНЕРНА ФІНАНСОВА ІНВЕСТИЦІЙНА КОМПАНІЯ</string>
  <string>АКЦІОНЕРНЕ ТОВАРИСТВО-ФІРМА</string>
  <string>АКЦІОНЕРНЕ ТОВАИСТВО</string>
  <string>АКЦІОНЕРНА КОМПАНІЯ</string>
  <string>АКЦІОНЕРНЕ ТОВАРИСТВО</string>
  <string>АКЦІОНЕРНЕ ПІДПРИЄМСТВО </string>
  <string>АКЦІОНЕРНЕ ОБ'ЄДНАННЯ</string>
  <string>АТФ </string>
  <string>АК </string>
  <string>АТ </string>
  <string>АО </string>
  <string>АП </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameAT {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>МІСЬКИЙ БЛАГОДІЙНИЙ ФОНД СОЦІАЛЬНОЇ РЕАБІЛІТАЦІЇ МОЛОДІ</string>
  <string>МІЖНАРОДНИЙ ЖІНОЧИЙ БЛАГОДІЙНИЙ ФОНД</string>
  <string>МІЖНАРОДНА БЛАГОДІЙНА ОРГАНІЗАЦІЯ</string>
  <string>МІЖНАРОДНИЙ БЛАГОДІЙНИЙ ДИТЯЧИЙ ФОНД</string>
  <string>МІЖНАРОДНИЙ БЛАГОДІЙНИЙ ФОНД</string>
  <string>БЛАГОДІЙНА ОРГАНІЗІЯ</string>
  <string>МІСЬКИЙ БЛАГОДІЙНИЙ ФОНД</string>
  <string>ВСЕУКРАЇНСЬКИЙ БЛАГОДІЙНИЙ ФОНД</string>
  <string>УКРАЇНСЬКИЙ БЛАГОДІЙНИЙ ФОНД</string>
  <string>МІСЦЕВИЙ БЛАГОДІЙНИЙ ФОНД</string>
  <string>БЛАГОДІЙНЕ ТОВАРИСТВО</string>
  <string>БЛАГ.МЕМОРІАЛЬНИЙ ФОНД</string>
  <string>БЛАГОДІЙНО-ЕКОЛОГІЧНИЙ ФОНД</string>
  <string>БЛАГОД.-ЕКОЛОГ. ФОНД</string>
  <string>БЛАГ.ОРГ.</string>
  <string>БЛАГОДІЙНА ОРГАНІЗАЦІЯ</string>
  <string>БЛАГОДІЙНИЙ ФОНД</string>
  <string>БЛАГОД.ОРГАНІЗАЦІЯ</string>
  <string>БЛАГ.ОРГАНІЗАЦІЯ</string>
  <string>БЛАГ.ОРГ-ЦІЯ</string>
  <string>БЛАГОД.ОРГ-ЦІЯ</string>
  <string>БЛАГ.ФОНД</string>
  <string>БЛАГОД.ТОВ-ВО</string>
  <string>БФІВ </string>
  <string>БО </string>
  <string>БФ </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameBlago {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameBlago"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>МІЖНАРОДНА БЛАГОДІЙНА АСОЦІАЦІЯ</string>
  <string>БЛАГОДІЙНА ГРОМАДСЬКА ОРГАНІЗАЦІЯ АСОЦІАЦІЯ</string>
  <string>КИЇВСЬКА АСОЦІАЦІЯ ІНВАЛІДІВ ЦЕРЕБРАЛЬНОГО ПАРАЛІЧУ</string>
  <string>АСОЦІАЦ.ІНВАЛІДІВ ЦЕРЕБРАЛЬНОГО ПАРАЛІЧУ</string>
  <string>АСОЦІАЦІЯ ДІЛОВОГО СПІВРОБІТНИЦТВА</string>
  <string>УКРАЇНСЬКА БАГАТОГАЛУЗЕВА ГОСПОДАРЧА АСОЦІАЦІЯ</string>
  <string>ВСЕУКРАЇНСЬКА АСОЦІАЦІЯ</string>
  <string>УКРАЇНСЬКА АСОЦІАЦІЯ</string>
  <string>ГОСПОДАРСЬКА АСОЦІАЦІЯ</string>
  <string>КИЇВСЬКА МІСЬКА АСОЦІАЦІЯ</string>
  <string>МЕДИКО-ФАРМАЦЕВТИЧНА АСОЦІАЦІЯ</string>
  <string>МІЖГАЛУЗЕВА АСОЦІАЦІЯ</string>
  <string>ГРОМАДСЬКА ОРГАНIЗАЦIЯ АСОЦIАЦIЯ</string>
  <string>АСАЦІАЦІЯ</string>
  <string>АСОЦІАЦІЯ</string>
  <string>АСОЦІАЦ.</string>
  <string>АСОЦ.</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameAssoc {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameAssoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ДЕРЖАВНЕ ПІДПРИЄМСТВО - УКРАЇНСЬКЕ ДЕРЖАВНЕ УПРАВЛІННЯ</string>
  <string>АДМІНІСТРАТИВНО-ГОСПОДАРЧЕ УПРАВЛІННЯ</string>
  <string>ГОЛОВНЕ ДЕРЖАВНЕ ОПЕРАТИВНЕ УПРАВЛІННЯ</string>
  <string>ГОЛОВНЕ УПРАВЛІННЯ ТОРГІВЛІ</string>
  <string>ГОЛОВНЕ ДЕРЖАВНЕ УПРАВЛІННЯ</string>
  <string>ГОЛОВНЕ УПРАВЛІННЯ</string>
  <string>ГОЛ. УПР. ТОРГІВЛІ</string>
  <string>ГОЛ.ДЕРЖ.УПР.</string>
  <string>ГОЛОВНЕ УПР.</string>
  <string>ГОЛОВНЕ УПРАВ.</string>
  <string>ГОЛОВНЕ УПРАВЛ.</string>
  <string>ГОЛОВ.УПР.</string>
  <string>ГОЛ.УПР.</string>
  <string>УКРАЇНСЬКЕ ДЕРЖАВНЕ УПРАВЛІННЯ</string>
  <string>КИЇВСЬКЕ МІСЬКЕ УПРАВЛІННЯ.</string>
  <string>КИЇВСЬКЕ МІСЬКЕ УПРАВЛІННЯ</string>
  <string>ДЕРЖАВНЕ УПРАВЛІННЯ</string>
  <string>УПРАВЛІННЯ</string>
  <string>УПРАВ.</string>
  <string>УПР-НЯ</string>
  <string>УП-НЯ</string>
  <string>УПР.</string>
  <string>АГУ </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameUpr {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameUpr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ЖИТЛОВО-БУДІВЕЛЬНИЙ КООПЕРАТИВ</string>\r\n  <string>ЖБК </string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameZHBK {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameZHBK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ЖИТЛОВО ЕКСПЛУАТАЦІЙНА КОНТОРА</string>
  <string>ЖЕК-</string>
  <string>ЖЕК </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNameZHEK {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNameZHEK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ДЕРЖАВНЕ ПІДПРИЄМСТВО ПОБУТУ</string>
  <string>ДЕРЖ. ПІДПРИЄМСТВО ПОБУТУ</string>
  <string>ТОВ ""БУДИНОК ПОБУТУ</string>
  <string>ТОВ БУДИНОК ПОБУТУ</string>
  <string>ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ ""БУДИНОК ПОБУТУ</string>
  <string>ТОВАРИСТВО З ОБМЕЖЕНОЮ ВІДПОВІДАЛЬНІСТЮ БУДИНОК ПОБУТУ</string>
  <string>АКЦІОНЕРНЕ ТОВАРИСТВО ВІДКРИТОГО ТИПУ БУДИНОК ПОБУТУ</string>
  <string>ОРЕНДНЕ ПІДПРИЄМСТВО БУДИНОК ПОБУТУ</string>
  <string>АТ ВТ БУДИНОК ПОБУТУ</string>
  <string>ОП БУДИНОК ПОБУТУ</string>
  <string>БУДИНОК ПОБУТУ</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrgNamePobut {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrgNamePobut"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kp-vm2")]
        public string Connection1NFServer {
            get {
                return ((string)(this["Connection1NFServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\database\\1nf\\1nf.gdb")]
        public string Connection1NFDatabase {
            get {
                return ((string)(this["Connection1NFDatabase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SYSDBA")]
        public string Connection1NFUser {
            get {
                return ((string)(this["Connection1NFUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("masterkey")]
        public string Connection1NFPassword {
            get {
                return ((string)(this["Connection1NFPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gukv-balans")]
        public string ConnectionBalansServer {
            get {
                return ((string)(this["ConnectionBalansServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\db\\Balans_Polygon.gdb")]
        public string ConnectionBalansDatabase {
            get {
                return ((string)(this["ConnectionBalansDatabase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SYSDBA")]
        public string ConnectionBalansUser {
            get {
                return ((string)(this["ConnectionBalansUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("masterkey")]
        public string ConnectionBalansPassword {
            get {
                return ((string)(this["ConnectionBalansPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kp-vm2")]
        public string ConnectionNJFServer {
            get {
                return ((string)(this["ConnectionNJFServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\database\\njf\\newnjf.gdb")]
        public string ConnectionNJFDatabase {
            get {
                return ((string)(this["ConnectionNJFDatabase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SYSDBA")]
        public string ConnectionNJFUser {
            get {
                return ((string)(this["ConnectionNJFUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("masterkey")]
        public string ConnectionNJFPassword {
            get {
                return ((string)(this["ConnectionNJFPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string ConnectionSQLServerServer {
            get {
                return ((string)(this["ConnectionSQLServerServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GUKV")]
        public string ConnectionSQLServerDatabase {
            get {
                return ((string)(this["ConnectionSQLServerDatabase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string ConnectionSQLServerUser {
            get {
                return ((string)(this["ConnectionSQLServerUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13579")]
        public string ConnectionSQLServerPassword {
            get {
                return ((string)(this["ConnectionSQLServerPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>БОЙЛЕРНА</string>
  <string>БОЙЛЕР</string>
  <string>ФАСАД</string>
  <string>САДИБА</string>
  <string>КОТЕЛЬНЯ</string>
  <string>ПОГРЕБ</string>
  <string>ГАРАЖ</string>
  <string>ГАРАЖІ</string>
  <string>БЮВЕТ</string>
  <string>СКВЕРБЮВЕТ</string>
  <string>ПРИБУДОВА</string>
  <string>ПРИБУД.</string>
  <string>ПРИМІЩ.</string>
  <string>БЕЗГОСП</string>
  <string>ВЕРАНДА</string>
  <string>САРАЙ</string>
  <string>НАМЕТ</string>
  <string>ПАВІЛЬЙОН</string>
  <string>ГОСП.СПОРУДА</string>
  <string>ГОСП.СПОР.</string>
  <string>ВИД</string>
  <string>АРЕНА</string>
  <string>НЕДОБУДОВА</string>
  <string>КІОСК</string>
  <string>ТУАЛЕТ</string>
  <string>МАЙСТЕРНЯ</string>
  <string>БОМБ</string>
  <string>БАСЕЙН</string>
  <string>МАЙДАНЧИК</string>
  <string>ВБИРАЛЬНЯ</string>
  <string>ДУШ</string>
  <string>НАСОСНА</string>
  <string>СКЛАД</string>
  <string>ТП ПРИБУДОВА</string>
  <string>СВЕРДЛОВИНА</string>
  <string>НС</string>
  <string>ТП</string>
  <string>СМ</string>
  <string>БУД</string>
  <string>КМ</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AddressMiscSuffixes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AddressMiscSuffixes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>М</string>\r\n  <string>МІСТО</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AddrTypeCity {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AddrTypeCity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>С</string>
  <string>С-ЩЕ</string>
  <string>СЕЛИЩЕ</string>
  <string>СМТ</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AddrTypeVillage {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AddrTypeVillage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>БУЛЬВ</string>\r\n  <string>БУЛЬВАР</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AddrTypeBoulevard {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AddrTypeBoulevard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ПРОВ</string>\r\n  <string>ПРОВУЛОК</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AddrTypeLane {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AddrTypeLane"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ПРОСП</string>\r\n  <string>ПРОСПЕКТ</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AddrTypeAvenue {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AddrTypeAvenue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ПЛ</string>\r\n  <string>ПЛОЩА</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AddrTypeSquare {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AddrTypeSquare"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ПАРК</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AddrTypePark {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AddrTypePark"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ТЕТЕРІВ</string>
  <string>ВОРЗЕЛЬ</string>
  <string>БОРИСПІЛЬ</string>
  <string>ГОСТОМЕЛЬ</string>
  <string>ЛИМАН ОДЕСЬКА ОБЛ</string>
  <string>ХЕРСОНСЬКА ОБЛ</string>
  <string>С.ЖУКИН</string>
  <string>МАКАРІВ</string>
  <string>ШЕВЧЕНКОВО</string>
  <string>ВОРОПАЇВ</string>
  <string>БРОВАРСЬКЕ ЛІСНИЦТВО</string>
  <string>М.ОБУХІВ</string>
  <string>ХОТЯНІВКА</string>
  <string>ГРЕБЕНІ</string>
  <string>М.СЕВАСТОПОЛЬ</string>
  <string>ІВАНКІВ</string>
  <string>М.ВИШГОРОД</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AddrKnownVillages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AddrKnownVillages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>40-РІЧЧЯ=СОРОКАРІЧЧЯ ЖОВТНЯ ПРОСП.</string>\r\n  <string>ЇЖАКЕВИЧА=ЇЖАКЕВИЧА" +
            " ІВАНА</string>\r\n  <string>БАЛЬЗАКА=БАЛЬЗАКА ОНОРЕ ДЕ</string>\r\n  <string>БЕРЕТТ" +
            "І=БЕРЕТТІ ВІКЕНТІЯ</string>\r\n  <string>БОРИСПІЛЬСЬКЕ=БОРИСПІЛЬСКЕ ШОСЕ</string>\r" +
            "\n  <string>ВАСИЛЕВСЬКОЇ=ВАСИЛЕВСЬКОЇ ВАНДИ</string>\r\n  <string>ВЕРНАДСЬКОГО=ВЕРН" +
            "АДСЬКОГО АКАДЕМІКА БУЛЬВ.</string>\r\n  <string>ВЕРБИЦЬКОГО=ВЕРБИЦЬКОГО АРХІТЕКТОР" +
            "А</string>\r\n  <string>ГАГАРІНА=ГАГАРІНА ЮРІЯ ПРОСП.</string>\r\n  <string>ГАВРО=ГА" +
            "ВРО ЛАЙОША</string>\r\n  <string>Б.ГАРІНА=ГАРІНА БОРИСА</string>\r\n  <string>Б. ГАР" +
            "ІНА=ГАРІНА БОРИСА</string>\r\n  <string>ГАРІНА Б=ГАРІНА БОРИСА</string>\r\n  <string" +
            ">\"ГАРІНА\"=ГАРІНА БОРИСА</string>\r\n  <string>ГЕТЬМАНА=ГЕТЬМАНА ВАДИМА</string>\r\n " +
            " <string>ГЛУШКОВА=ГЛУШКОВА АКАДЕМІКА</string>\r\n  <string>ГОНЧАРА=ГОНЧАРА ОЛЕСЯ</" +
            "string>\r\n  <string>ГОНГАДЗЕ=ГОНГАДЗЕ ГЕОРГІЯ ПРОСП.</string>\r\n  <string>ГОРОДЕЦЬ" +
            "КОГО=ГОРОДЕЦЬКОГО АРХІТЕКТОРА</string>\r\n  <string>ГРЕКОВА=ГРЕКОВА АКАДЕМІКА</str" +
            "ing>\r\n  <string>ГРІНЧЕНКА М=ГРІНЧЕНКА МИКОЛИ</string>\r\n  <string>ГРІНЧЕНКА Б=ГРІ" +
            "НЧЕНКА БОРИСА</string>\r\n  <string>ГРУШЕВСЬКОГО=ГРУШЕВСЬКОГО МИХАЙЛА</string>\r\n  " +
            "<string>НАБ. ДНІПРОВСЬКА=ДНІПРОВСЬКА НАБЕРЕЖНА</string>\r\n  <string>ДОБРОХОТОВА=Д" +
            "ОБРОХОТОВА АКАДЕМІКА</string>\r\n  <string>ДОВНАР=ДОВНАР-ЗАПОЛЬСЬКОГО</string>\r\n  " +
            "<string>ДРАЙЗЕРА=ДРАЙЗЕРА ТЕОДОРА</string>\r\n  <string>ДУБІНІНА=ДУБІНІНА ВОЛОДІ</" +
            "string>\r\n  <string>ЗАБОЛОТНОГО=ЗАБОЛОТНОГО АКАДЕМІКА</string>\r\n  <string>ЗАКРЕВС" +
            "ЬКОГО=ЗАКРЕВСЬКОГО МИКОЛИ</string>\r\n  <string>КИБАЛЬЧИЧА=КИБАЛЬЧИЧА МИКОЛИ</stri" +
            "ng>\r\n  <string>КОТЕЛЬНИКОВА=КОТЕЛЬНИКОВА МИХАЙЛА</string>\r\n  <string>КОЦЮБИНСЬКО" +
            "ГО Ю=КОЦЮБИНСЬКОГО ЮРІЯ</string>\r\n  <string>КОЦЮБИНСЬКОГО М=КОЦЮБИНСЬКОГО МИХАЙЛ" +
            "А</string>\r\n  <string>М. КОЦЮБИНСЬКОГО=КОЦЮБИНСЬКОГО МИХАЙЛА</string>\r\n  <string" +
            ">КОМАРОВА=КОМАРОВА КОСМОНАВТА ПРОСП.</string>\r\n  <string>КОРОЛЬОВА=КОРОЛЬОВА АКА" +
            "ДЕМІКА ПРОСП.</string>\r\n  <string>КРАМСЬКОГО=КРАМСЬКОГО ІВАНА</string>\r\n  <strin" +
            "g>КРАСИКОВА=КРАСИКОВА ПЕТРА</string>\r\n  <string>КРАСІКОВА=КРАСИКОВА ПЕТРА</strin" +
            "g>\r\n  <string>КОЗИЦЬКОГО=КОЗИЦЬКОГО ПИЛИПА</string>\r\n  <string>КРАВЧЕНКА=КРАВЧЕН" +
            "КА МИКОЛИ</string>\r\n  <string>КРАСНОВА=КРАСНОВА МИКОЛИ</string>\r\n  <string>ВУЛ. " +
            "М. КРИВОНОСА=КРИВОНОСА МАКСИМА</string>\r\n  <string>КУДРІ=КУДРІ ІВАНА</string>\r\n " +
            " <string>КУРБАСА=КУРБАСА ЛЕСЯ ПРОСП.</string>\r\n  <string>КУРЧАТОВА=КУРЧАТОВА АКА" +
            "ДЕМІКА</string>\r\n  <string>ЛАЗО=ЛАЗО СЕРГІЯ</string>\r\n  <string>ЛЕЙПЦ=ЛЕЙПЦИЗЬКА" +
            "</string>\r\n  <string>ЛЕПСЕ І=ЛЕПСЕ ІВАНА БУЛЬВ.</string>\r\n  <string>МАЗЕПИ=МАЗЕП" +
            "И ІВАНА</string>\r\n  <string>МАТЕЮКА=МАТЕЮКА МИКОЛИ</string>\r\n  <string>МАЙБОРОДИ" +
            "=ПЛАТОНА МАЙБОРОДИ</string>\r\n  <string>МАЯКОВСЬКОГО=МАЯКОВСЬКОГО В. ПРОСП.</stri" +
            "ng>\r\n  <string>МИЛЬЧАКОВА=МИЛЬЧАКОВА ОЛЕКСАНДРА</string>\r\n  <string>МІЛЬЧАКОВА=М" +
            "ИЛЬЧАКОВА ОЛЕКСАНДРА</string>\r\n  <string>МУРАШКА=МУРАШКА МИКОЛИ</string>\r\n  <str" +
            "ing>НАВОЇ=НАВОЇ АЛІШЕРА ПРОСП.</string>\r\n  <string>ОКІПНОЇ=ОКІПНОЇ РАЇСИ</string" +
            ">\r\n  <string>ПЕРВОМАЙСЬКОГО=ПЕРВОМАЙСЬКОГО ЛЕОНІДА</string>\r\n  <string>ПЕТЛЮРИ=П" +
            "ЕТЛЮРИ СИМОНА</string>\r\n  <string>ПІДВИСОЦЬКОГО=ПІДВИСОЦЬКОГО ПРОФЕСОРА</string>" +
            "\r\n  <string>ПІКА=ПІКА ВІЛЬГЕЛЬМА</string>\r\n  <string>ПИМОНЕНКА=ПИМОНЕНКА МИКОЛИ<" +
            "/string>\r\n  <string>ПОЛКОВІЙ=ПОЛКОВА</string>\r\n  <string>РАЄВСЬКОГО=РАЄВСЬКОГО М" +
            "ИКОЛИ</string>\r\n  <string>РАДЧЕНКА=РАДЧЕНКА ПЕТРА</string>\r\n  <string>РИБАЛКА=РИ" +
            "БАЛКА МАРШАЛА</string>\r\n  <string>РУДЕНКО=РУДЕНКО ЛАРИСИ</string>\r\n  <string>НАБ" +
            ". РУСАНІВСЬКА=РУСАНІВСЬКА НАБЕРЕЖНА</string>\r\n  <string>СЕРГІЄНКА=СЕРГІЄНКА ІВАН" +
            "А</string>\r\n  <string>СТАЛЬСЬКОГО=СТАЛЬСЬКОГО СУЛЕЙМАНА</string>\r\n  <string>ТЕЛІ" +
            "ГИ=ТЕЛІГИ ОЛЕНИ</string>\r\n  <string>ТИМОФІЄВОЇ=ТИМОФЄЄВОЇ ГАЛІ</string>\r\n  <stri" +
            "ng>ТИМОФЄЄВОЇ=ТИМОФЄЄВОЇ ГАЛІ</string>\r\n  <string>БЛ. УКРАЇНКИ Л=ЛЕСІ УКРАЇНКИ Б" +
            "УЛЬВ.</string>\r\n  <string>УКРАЇНКИ Б=ЛЕСІ УКРАЇНКИ БУЛЬВ.</string>\r\n  <string>ВУ" +
            "Л. ФРАНКА=ФРАНКА ІВАНА</string>\r\n  <string>ФЕДОРОВА=ФЕДОРОВА ІВАНА</string>\r\n  <" +
            "string>ХМЕЛЬНИЦЬКОГО Б=ХМЕЛЬНИЦЬКОГО БОГДАНА</string>\r\n  <string>ХОХЛОВИХ=ХОХЛОВ" +
            "ИХ СІМ\'Ї</string>\r\n  <string>ШАМРИЛА=ШАМРИЛА ТИМОФІЯ</string>\r\n  <string>БЛ. ШЕВ" +
            "ЧЕНКА Т=ШЕВЧЕНКА ТАРАСА БУЛЬВ.</string>\r\n  <string>ШЕПЕЛЄВА=ШЕПЕЛЄВА МИКОЛИ</str" +
            "ing>\r\n  <string>ШУМСЬКОГО=ШУМСЬКОГО ЮРІЯ</string>\r\n  <string>АЛЕЙХЕМ=ШОЛОМ-АЛЕЙХ" +
            "ЕМА</string>\r\n  <string>ЮНКЕРОВА=ЮНКЕРОВА МИКОЛИ</string>\r\n  <string>ЯРМОЛИ=ЯРМО" +
            "ЛИ ВІКТОРА</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StreetNameCorrections {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StreetNameCorrections"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ПРОСПЕКТ=ПРОСПЕКТ</string>
  <string>ПРОСП.=ПРОСПЕКТ</string>
  <string>ПР-КТ=ПРОСПЕКТ</string>
  <string>ПР-Т=ПРОСПЕКТ</string>
  <string>ПР.=ПРОСПЕКТ</string>
  <string>ПРОВ=ПРОВУЛОК</string>
  <string>ВУЛИЦЯ</string>
  <string>ВУЛ</string>
  <string>БУЛЬВАР=БУЛЬВАР</string>
  <string>БУЛЬВ=БУЛЬВАР</string>
  <string>БУЛ.=БУЛЬВАР</string>
  <string>ПЛОЩА=ПЛОЩА</string>
  <string>УЗВІЗ=УЗВІЗ</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RentPaymentStreetSuffix {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RentPaymentStreetSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ПР-Т</string>\r\n  <string>ПРОСП.</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StreetAvenuePrefixList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StreetAvenuePrefixList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>БУЛЬВ.</string>\r\n  <string>БЛ.</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StreetBoulevardPrefixList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StreetBoulevardPrefixList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ПРОВУЛ.</string>\r\n  <string>ПРОВ.</string>\r\n  <string>ПРОВ </string>\r\n</Ar" +
            "rayOfString>")]
        public global::System.Collections.Specialized.StringCollection StreetLanePrefixList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StreetLanePrefixList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ПЛОЩА</string>\r\n  <string>ПЛ.</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StreetSquarePrefixList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StreetSquarePrefixList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.10.4")]
        public string SmtpHost {
            get {
                return ((string)(this["SmtpHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int SmtpPort {
            get {
                return ((int)(this["SmtpPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a")]
        public string SmtpUser {
            get {
                return ((string)(this["SmtpUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SmtpPassword {
            get {
                return ((string)(this["SmtpPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("support@itgukraine.com")]
        public string SmtpReplyTo {
            get {
                return ((string)(this["SmtpReplyTo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GUM-KMDA")]
        public string SmtpDomain {
            get {
                return ((string)(this["SmtpDomain"]));
            }
        }
    }
}
