
CREATE FUNCTION [dbo].[fnTokenizeStringList]
(	
	@STRINGLIST AS VARCHAR(MAX),
	@DELIMETER AS VARCHAR(MAX)
)
RETURNS @OUTPUT TABLE (STRINGS VARCHAR(MAX))
AS
BEGIN
	DECLARE @TOKEN AS VARCHAR(MAX)
	DECLARE @VALUES AS VARCHAR(MAX)

	WHILE LEN(@STRINGLIST) > 0
	BEGIN

		SET @VALUES = CHARINDEX(@DELIMETER, @STRINGLIST)
		IF @VALUES > 0
		BEGIN
			SET @TOKEN = SUBSTRING(@STRINGLIST, 1, @VALUES - 1)
			SET @STRINGLIST = SUBSTRING(@STRINGLIST, @VALUES + 1, LEN(@STRINGLIST))
		END
		IF @VALUES = 0
		BEGIN
			SET @TOKEN = @STRINGLIST
			SET @STRINGLIST = ''
		END

		INSERT INTO @OUTPUT (STRINGS) VALUES (CAST(@TOKEN AS varchar(max)) )

	END
	RETURN
END
